import { WhoAmIItem } from "./types";

/**
 * BANCO DO "QUEM SOU EU?"
 *
 * Para adicionar uma coisa nova:
 * 1. Copie qualquer objeto abaixo.
 * 2. Troque `id`, `answer`, categoria, dificuldade e as 5 pistas.
 * 3. `aliases` são respostas alternativas aceitas (opcional).
 *
 * Para remover, apague o objeto inteiro.
 *
 * Regra das pistas:
 * - hints[0] deve ser a mais difícil.
 * - hints[4] deve ser a mais óbvia.
 *
 * "easy" foi pensado para coisas MUITO conhecidas até fora do próprio nicho.
 */
export const WHOAMI_ITEMS: WhoAmIItem[] = [
  // ───────────────────────── Filmes e Séries
  {
    id: "movie-harry-potter",
    answer: "Harry Potter",
    aliases: ["harry potter e a pedra filosofal"],
    category: "moviesSeries",
    difficulty: "easy",
    hints: [
      "Minha história começa com uma criança criada longe do mundo ao qual realmente pertence.",
      "Existe uma escola muito importante no centro da minha história.",
      "Varinhas, feitiços e criaturas mágicas aparecem o tempo todo.",
      "Uma cicatriz em forma de raio é um dos símbolos mais conhecidos da franquia.",
      "Meu protagonista se chama Harry e estuda em Hogwarts.",
    ],
  },
  {
    id: "movie-titanic",
    answer: "Titanic",
    category: "moviesSeries",
    difficulty: "easy",
    hints: [
      "Minha história mistura personagens fictícios com um acontecimento histórico real.",
      "Grande parte da trama acontece durante uma viagem.",
      "Um romance nasce entre duas pessoas de classes sociais diferentes.",
      "Um iceberg muda completamente o rumo da história.",
      "Jack e Rose são o casal mais lembrado de mim.",
    ],
  },
  {
    id: "series-stranger-things",
    answer: "Stranger Things",
    aliases: ["stranger things"],
    category: "moviesSeries",
    difficulty: "easy",
    hints: [
      "Minha história se passa principalmente nos anos 1980.",
      "Um pequeno grupo de crianças se envolve com acontecimentos muito estranhos.",
      "Experimentos secretos fazem parte da trama.",
      "Existe uma dimensão sombria conhecida como Mundo Invertido.",
      "Eleven é uma das personagens mais famosas de mim.",
    ],
  },
  {
    id: "movie-frozen",
    answer: "Frozen",
    category: "moviesSeries",
    difficulty: "medium",
    hints: [
      "Minha história gira em torno de duas irmãs de uma família real.",
      "O medo de perder o controle causa o principal conflito da trama.",
      "Um boneco de neve falante acompanha a aventura.",
      "Uma das protagonistas possui poderes ligados ao gelo.",
      "A música 'Let It Go' ficou fortemente associada a mim.",
    ],
  },
  {
    id: "series-la-casa-de-papel",
    answer: "La Casa de Papel",
    aliases: ["la casa de papel", "money heist"],
    category: "moviesSeries",
    difficulty: "medium",
    hints: [
      "Meu grupo principal usa nomes de cidades em vez de nomes verdadeiros.",
      "Um homem conhecido como Professor coordena os acontecimentos de longe.",
      "Macacões vermelhos viraram uma marca visual da série.",
      "Máscaras de Salvador Dalí aparecem com frequência.",
      "Minha trama ficou famosa por grandes assaltos planejados.",
    ],
  },
  {
    id: "movie-star-wars",
    answer: "Star Wars",
    aliases: ["guerra nas estrelas"],
    category: "moviesSeries",
    difficulty: "medium",
    hints: [
      "Minha história acontece em uma galáxia muito distante.",
      "Uma energia invisível pode ser usada por certos personagens.",
      "Conflitos entre impérios, rebeldes e diferentes gerações movem a saga.",
      "Sabres de luz são uma das minhas maiores marcas.",
      "Darth Vader é um dos personagens mais famosos de mim.",
    ],
  },
  {
    id: "series-breaking-bad",
    answer: "Breaking Bad",
    category: "moviesSeries",
    difficulty: "hard",
    hints: [
      "Minha história acompanha uma transformação moral cada vez mais intensa.",
      "O protagonista começa a trama trabalhando como professor.",
      "Grande parte da história se passa no Novo México.",
      "Química tem papel central no começo da trama.",
      "Walter White e Jesse Pinkman são meus protagonistas mais conhecidos.",
    ],
  },
  {
    id: "series-the-walking-dead",
    answer: "The Walking Dead",
    aliases: ["walking dead"],
    category: "moviesSeries",
    difficulty: "hard",
    hints: [
      "O maior perigo da minha história nem sempre são as criaturas que dão fama à série.",
      "Sobreviventes formam e perdem comunidades ao longo de muitos anos.",
      "Um policial acorda e encontra o mundo completamente mudado.",
      "Mortos-vivos dominam o cenário da trama.",
      "Rick Grimes é um dos meus personagens centrais.",
    ],
  },

  // ───────────────────────── Games
  {
    id: "game-minecraft",
    answer: "Minecraft",
    category: "games",
    difficulty: "easy",
    hints: [
      "Meu mundo pode ser gerado de forma praticamente infinita.",
      "Construir e explorar são atividades tão importantes quanto lutar.",
      "Minhas criaturas aparecem de formas diferentes durante o dia e a noite.",
      "Quase tudo em mim é formado por blocos.",
      "Creepers verdes são uma das minhas criaturas mais famosas.",
    ],
  },
  {
    id: "game-super-mario",
    answer: "Super Mario",
    aliases: ["mario", "super mario bros", "mario bros"],
    category: "games",
    difficulty: "easy",
    hints: [
      "Minha franquia existe há várias gerações de videogames.",
      "Cogumelos podem mudar o tamanho do personagem principal.",
      "Canos verdes aparecem bastante nos meus mundos.",
      "Uma princesa costuma precisar ser salva.",
      "Meu protagonista é um encanador italiano de boné vermelho.",
    ],
  },
  {
    id: "game-gta",
    answer: "GTA",
    aliases: ["grand theft auto", "gta 5", "gta v", "grand theft auto v"],
    category: "games",
    difficulty: "easy",
    hints: [
      "Minhas cidades costumam ser versões satíricas de lugares dos Estados Unidos.",
      "O jogador tem muita liberdade para ignorar a missão principal.",
      "Carros e perseguições fazem parte da experiência com frequência.",
      "Polícia e estrelas de procurado são elementos bem conhecidos da série.",
      "Meu nome é a sigla de Grand Theft Auto.",
    ],
  },
  {
    id: "game-roblox",
    answer: "Roblox",
    category: "games",
    difficulty: "medium",
    hints: [
      "Eu sou mais uma plataforma de experiências do que um único jogo.",
      "Meu conteúdo é criado em grande parte pela própria comunidade.",
      "Avatares personalizáveis são parte importante de mim.",
      "Existem milhares de jogos diferentes dentro de mim.",
      "Robux é a minha moeda virtual mais conhecida.",
    ],
  },
  {
    id: "game-fortnite",
    answer: "Fortnite",
    category: "games",
    difficulty: "medium",
    hints: [
      "Minha aparência mudou bastante desde o lançamento.",
      "Eventos e colaborações com filmes, músicos e outros jogos são comuns.",
      "Uma tempestade força os jogadores a se aproximarem.",
      "Construções ficaram famosas como parte do meu combate.",
      "Sou um dos battle royales mais populares do mundo.",
    ],
  },
  {
    id: "game-free-fire",
    answer: "Free Fire",
    aliases: ["garena free fire"],
    category: "games",
    difficulty: "medium",
    hints: [
      "Fiquei especialmente popular em celulares mais simples.",
      "As partidas colocam vários jogadores numa mesma área de sobrevivência.",
      "Personagens possuem habilidades próprias.",
      "Minha comunidade é enorme no Brasil.",
      "Sou um battle royale mobile publicado pela Garena.",
    ],
  },
  {
    id: "game-resident-evil",
    answer: "Resident Evil",
    aliases: ["biohazard"],
    category: "games",
    difficulty: "hard",
    hints: [
      "Uma corporação fictícia está por trás de muitos dos meus maiores problemas.",
      "Minha série mistura ação, terror e experiências biológicas.",
      "Raccoon City é um local muito importante na franquia.",
      "Zumbis e armas biológicas aparecem em vários jogos.",
      "A Umbrella Corporation é uma das marcas mais conhecidas de mim.",
    ],
  },
  {
    id: "game-league-of-legends",
    answer: "League of Legends",
    aliases: ["lol", "league"],
    category: "games",
    difficulty: "hard",
    hints: [
      "Duas equipes disputam uma partida num mapa simétrico.",
      "Cada jogador controla um personagem com habilidades próprias.",
      "Torres protegem o caminho até a base.",
      "O objetivo final é destruir o Nexus inimigo.",
      "Sou conhecido mundialmente pela sigla LoL.",
    ],
  },

  // ───────────────────────── Personagens
  {
    id: "character-batman",
    answer: "Batman",
    aliases: ["homem morcego", "homem-morcego"],
    category: "characters",
    difficulty: "easy",
    hints: [
      "Minha maior arma não é um superpoder.",
      "Uma tragédia familiar definiu boa parte da minha vida.",
      "Sou bilionário quando não estou combatendo o crime.",
      "Gotham é a cidade que protejo.",
      "Uso uma roupa inspirada em um morcego.",
    ],
  },
  {
    id: "character-spiderman",
    answer: "Homem-Aranha",
    aliases: ["homem aranha", "spider-man", "spiderman", "spider man", "peter parker"],
    category: "characters",
    difficulty: "easy",
    hints: [
      "Tento equilibrar uma vida comum com uma grande responsabilidade.",
      "Tenho uma ligação muito forte com Nova York.",
      "Minha origem envolve a picada de um animal.",
      "Costumo me locomover entre prédios usando teias.",
      "Peter Parker é meu nome mais conhecido.",
    ],
  },
  {
    id: "character-shrek",
    answer: "Shrek",
    category: "characters",
    difficulty: "easy",
    hints: [
      "Eu valorizo muito a tranquilidade do lugar onde moro.",
      "No começo, não gosto nada de receber visitas inesperadas.",
      "Um burro falante se torna meu grande companheiro.",
      "Sou apaixonado por uma princesa chamada Fiona.",
      "Sou um ogro verde que vive num pântano.",
    ],
  },
  {
    id: "character-superman",
    answer: "Superman",
    aliases: ["super homem", "super-homem", "clark kent"],
    category: "characters",
    difficulty: "medium",
    hints: [
      "Nasci muito longe do planeta onde cresci.",
      "Minha identidade cotidiana trabalha com jornalismo.",
      "Uma pedra específica pode me deixar extremamente fraco.",
      "Uso um símbolo no peito e uma capa.",
      "Clark Kent é minha identidade humana.",
    ],
  },
  {
    id: "character-darth-vader",
    answer: "Darth Vader",
    aliases: ["vader", "anakin skywalker"],
    category: "characters",
    difficulty: "medium",
    hints: [
      "Minha respiração é quase tão reconhecível quanto minha aparência.",
      "Já estive do outro lado do conflito antes de me tornar quem sou.",
      "Tenho ligação direta com a família Skywalker.",
      "Uso armadura preta e um sabre de luz vermelho.",
      "Sou um dos maiores vilões de Star Wars.",
    ],
  },
  {
    id: "character-joker",
    answer: "Coringa",
    aliases: ["joker"],
    category: "characters",
    difficulty: "medium",
    hints: [
      "Minha origem muda dependendo da versão da história.",
      "Gosto de transformar crimes em espetáculos.",
      "Tenho uma relação de obsessão com um herói específico.",
      "Sorrisos, cartas e maquiagem são ligados à minha imagem.",
      "Sou o inimigo mais famoso do Batman.",
    ],
  },
  {
    id: "character-wolverine",
    answer: "Wolverine",
    aliases: ["logan"],
    category: "characters",
    difficulty: "hard",
    hints: [
      "Minha memória e meu passado costumam ser complicados.",
      "Meu corpo se recupera de ferimentos muito rapidamente.",
      "Um metal raro foi ligado ao meu esqueleto.",
      "Faço parte dos X-Men em muitas histórias.",
      "Tenho garras que saem das mãos e me chamo Logan.",
    ],
  },
  {
    id: "character-deadpool",
    answer: "Deadpool",
    aliases: ["wade wilson"],
    category: "characters",
    difficulty: "hard",
    hints: [
      "Costumo perceber que faço parte de uma obra de ficção.",
      "Meu jeito de falar é tão importante quanto minhas habilidades.",
      "Tenho grande capacidade de regeneração.",
      "Uso roupa vermelha e preta e sou extremamente tagarela.",
      "Wade Wilson é meu nome.",
    ],
  },

  // ───────────────────────── Anime e Desenhos
  {
    id: "cartoon-spongebob",
    answer: "Bob Esponja",
    aliases: ["bob esponja calca quadrada", "bob esponja calça quadrada", "spongebob"],
    category: "animeCartoons",
    difficulty: "easy",
    hints: [
      "Meu trabalho é uma parte surpreendentemente importante da minha rotina.",
      "Meu melhor amigo mora perto de mim e não é muito inteligente.",
      "Vivo no fundo do mar.",
      "Moro dentro de um abacaxi.",
      "Trabalho no Siri Cascudo preparando hambúrgueres.",
    ],
  },
  {
    id: "anime-goku",
    answer: "Goku",
    aliases: ["son goku", "kakaroto", "kakarot"],
    category: "animeCartoons",
    difficulty: "easy",
    hints: [
      "Passei boa parte da vida procurando ficar cada vez mais forte.",
      "Minha origem não é exatamente terrestre.",
      "Minha transformação mais famosa muda bastante meu cabelo.",
      "As Esferas do Dragão fazem parte do meu universo.",
      "Sou o protagonista mais conhecido de Dragon Ball.",
    ],
  },
  {
    id: "anime-naruto",
    answer: "Naruto",
    aliases: ["naruto uzumaki"],
    category: "animeCartoons",
    difficulty: "easy",
    hints: [
      "Passei a infância buscando reconhecimento das pessoas ao meu redor.",
      "Carrego dentro de mim uma criatura muito poderosa.",
      "Meu grande objetivo é liderar minha vila.",
      "Uso técnicas ninja e costumo vestir laranja.",
      "Quero me tornar Hokage.",
    ],
  },
  {
    id: "cartoon-mickey",
    answer: "Mickey Mouse",
    aliases: ["mickey", "mickey mouse"],
    category: "animeCartoons",
    difficulty: "medium",
    hints: [
      "Minha aparência mudou bastante ao longo de quase um século.",
      "Tenho dois grandes círculos que fazem parte da minha silhueta.",
      "Minha companheira mais conhecida se chama Minnie.",
      "Sou um dos principais símbolos da Disney.",
      "Sou um rato de desenho animado chamado Mickey.",
    ],
  },
  {
    id: "cartoon-scooby",
    answer: "Scooby-Doo",
    aliases: ["scooby doo", "scooby"],
    category: "animeCartoons",
    difficulty: "medium",
    hints: [
      "Viajo bastante com um grupo de amigos.",
      "Quase sempre há um mistério por trás do que parece sobrenatural.",
      "Meu melhor amigo humano é tão medroso e faminto quanto eu.",
      "Viajo numa van chamada Máquina de Mistério.",
      "Sou um cachorro chamado Scooby-Doo.",
    ],
  },
  {
    id: "cartoon-simpsons",
    answer: "Os Simpsons",
    aliases: ["simpsons", "the simpsons"],
    category: "animeCartoons",
    difficulty: "medium",
    hints: [
      "Minha cidade possui muitos moradores recorrentes há décadas.",
      "Uma família é o centro de praticamente todas as histórias.",
      "Uma usina nuclear é um local importante para um dos protagonistas.",
      "Meus personagens são famosos pela pele amarela.",
      "Homer, Marge, Bart, Lisa e Maggie formam minha família principal.",
    ],
  },
  {
    id: "anime-luffy",
    answer: "Luffy",
    aliases: ["monkey d luffy", "monkey d. luffy"],
    category: "animeCartoons",
    difficulty: "hard",
    hints: [
      "Meu sonho depende de chegar ao fim de uma viagem muito longa.",
      "Reúno companheiros com objetivos próprios para formar minha tripulação.",
      "Meu corpo ganhou propriedades incomuns após eu comer uma fruta.",
      "Uso um chapéu de palha.",
      "Quero me tornar o Rei dos Piratas em One Piece.",
    ],
  },
  {
    id: "cartoon-rick",
    answer: "Rick Sanchez",
    aliases: ["rick", "rick sanchez"],
    category: "animeCartoons",
    difficulty: "hard",
    hints: [
      "Minha inteligência costuma causar tantos problemas quanto resolve.",
      "Viajo com frequência por realidades diferentes.",
      "Meu parceiro de aventuras é meu próprio neto.",
      "Uma arma em forma de pistola abre portais.",
      "Sou o cientista de cabelo azul de Rick and Morty.",
    ],
  },

  // ───────────────────────── Famosos
  {
    id: "famous-neymar",
    answer: "Neymar",
    aliases: ["neymar jr", "neymar junior"],
    category: "famous",
    difficulty: "easy",
    hints: [
      "Comecei a ganhar enorme destaque profissional ainda muito jovem.",
      "Minha carreira me levou do Brasil para grandes clubes europeus.",
      "Já usei a camisa 10 da seleção brasileira.",
      "Fiquei mundialmente conhecido jogando futebol.",
      "Sou Neymar Jr.",
    ],
  },
  {
    id: "famous-cristiano",
    answer: "Cristiano Ronaldo",
    aliases: ["cr7", "cristiano", "ronaldo"],
    category: "famous",
    difficulty: "easy",
    hints: [
      "Nasci numa ilha portuguesa.",
      "Minha carreira passou por alguns dos maiores clubes da Europa.",
      "Tenho uma comemoração de gol reconhecida no mundo inteiro.",
      "Usei por muitos anos o número 7.",
      "Sou conhecido pela sigla CR7.",
    ],
  },
  {
    id: "famous-messi",
    answer: "Lionel Messi",
    aliases: ["messi", "lionel messi"],
    category: "famous",
    difficulty: "easy",
    hints: [
      "Saí do meu país ainda jovem para desenvolver minha carreira.",
      "Passei a maior parte da carreira europeia em um único clube espanhol.",
      "Sou conhecido pelo controle de bola e pela perna esquerda.",
      "Ganhei a Copa do Mundo com a Argentina.",
      "Meu sobrenome é Messi.",
    ],
  },
  {
    id: "famous-michael-jackson",
    answer: "Michael Jackson",
    aliases: ["michael jackson", "mj"],
    category: "famous",
    difficulty: "medium",
    hints: [
      "Comecei a carreira artística ainda criança ao lado dos meus irmãos.",
      "Meus videoclipes ajudaram a transformar a cultura pop.",
      "Uma luva brilhante ficou ligada à minha imagem.",
      "Moonwalk é um passo de dança associado a mim.",
      "Fiquei conhecido como Rei do Pop.",
    ],
  },
  {
    id: "famous-anitta",
    answer: "Anitta",
    category: "famous",
    difficulty: "medium",
    hints: [
      "Minha carreira começou no Brasil e depois ganhou forte projeção internacional.",
      "Canto em português, espanhol e inglês em diferentes trabalhos.",
      "Nasci no Rio de Janeiro.",
      "Fiquei conhecida nacionalmente no funk e no pop.",
      "Meu nome artístico é Anitta.",
    ],
  },
  {
    id: "famous-taylor-swift",
    answer: "Taylor Swift",
    aliases: ["taylor", "taylor swift"],
    category: "famous",
    difficulty: "medium",
    hints: [
      "Comecei a carreira com uma presença forte na música country.",
      "Sou conhecida por escrever músicas inspiradas em experiências pessoais.",
      "Regravei vários dos meus próprios álbuns.",
      "Minha turnê Eras se tornou um fenômeno mundial.",
      "Meu primeiro nome é Taylor e meu sobrenome é Swift.",
    ],
  },
  {
    id: "famous-beyonce",
    answer: "Beyoncé",
    aliases: ["beyonce", "beyoncé knowles"],
    category: "famous",
    difficulty: "hard",
    hints: [
      "Antes da carreira solo, fiz parte de um grupo feminino muito famoso.",
      "Minha carreira mistura música, dança e grandes produções visuais.",
      "Sou casada com um rapper e empresário muito conhecido.",
      "Destiny's Child fez parte da minha trajetória.",
      "Sou conhecida mundialmente como Beyoncé.",
    ],
  },
  {
    id: "famous-keanu",
    answer: "Keanu Reeves",
    aliases: ["keanu", "keanu reeves"],
    category: "famous",
    difficulty: "hard",
    hints: [
      "Participei de duas franquias de ação muito diferentes e muito populares.",
      "Minha imagem pública é frequentemente associada a um jeito discreto.",
      "Interpretei um assassino chamado John Wick.",
      "Também fui Neo em Matrix.",
      "Meu nome é Keanu Reeves.",
    ],
  },

  // ───────────────────────── Animais
  {
    id: "animal-dog",
    answer: "Cachorro",
    aliases: ["cao", "cão", "cachorra"],
    category: "animals",
    difficulty: "easy",
    hints: [
      "Fui domesticado há milhares de anos.",
      "Posso trabalhar ajudando humanos de várias maneiras.",
      "Meu olfato costuma ser muito mais forte que o dos humanos.",
      "Sou conhecido como melhor amigo do homem.",
      "Eu lato.",
    ],
  },
  {
    id: "animal-cat",
    answer: "Gato",
    aliases: ["gata"],
    category: "animals",
    difficulty: "easy",
    hints: [
      "Fui associado a diferentes culturas ao longo da história.",
      "Meu corpo é muito flexível e costumo cair em pé.",
      "Gosto de lugares altos e posso passar bastante tempo dormindo.",
      "Tenho bigodes muito sensíveis.",
      "Eu mio.",
    ],
  },
  {
    id: "animal-elephant",
    answer: "Elefante",
    category: "animals",
    difficulty: "easy",
    hints: [
      "Vivo em grupos sociais complexos.",
      "Tenho uma memória popularmente considerada muito boa.",
      "Minhas orelhas podem ser enormes.",
      "Uso uma tromba para respirar, pegar objetos e beber.",
      "Sou o maior animal terrestre vivo.",
    ],
  },
  {
    id: "animal-penguin",
    answer: "Pinguim",
    category: "animals",
    difficulty: "medium",
    hints: [
      "Algumas espécies minhas vivem muito longe de regiões congeladas.",
      "Sou uma ave, mas não voo.",
      "Sou excelente nadador.",
      "Minha aparência lembra um pequeno terno preto e branco.",
      "Sou muito associado à Antártida.",
    ],
  },
  {
    id: "animal-shark",
    answer: "Tubarão",
    category: "animals",
    difficulty: "medium",
    hints: [
      "Meu esqueleto não é formado por ossos como o seu.",
      "Existem centenas de espécies minhas.",
      "Posso detectar sinais elétricos produzidos por outros animais.",
      "Meus dentes são substituídos ao longo da vida.",
      "Sou um grande predador marinho.",
    ],
  },
  {
    id: "animal-kangaroo",
    answer: "Canguru",
    category: "animals",
    difficulty: "medium",
    hints: [
      "Minha locomoção mais famosa economiza bastante energia em grandes distâncias.",
      "Uso uma cauda forte para equilíbrio.",
      "Sou um marsupial.",
      "A fêmea carrega o filhote numa bolsa.",
      "Sou um dos maiores símbolos da Austrália.",
    ],
  },
  {
    id: "animal-chameleon",
    answer: "Camaleão",
    category: "animals",
    difficulty: "hard",
    hints: [
      "Meus olhos conseguem se mover de forma bastante independente.",
      "Minha língua pode alcançar uma presa muito rapidamente.",
      "Mudar de aparência também serve para comunicação e temperatura.",
      "Sou famoso por alterar a cor do corpo.",
      "Sou um réptil conhecido pelo disfarce.",
    ],
  },
  {
    id: "animal-platypus",
    answer: "Ornitorrinco",
    category: "animals",
    difficulty: "hard",
    hints: [
      "Sou um mamífero de um grupo bastante incomum.",
      "Os machos possuem uma estrutura capaz de liberar veneno.",
      "Apesar de mamífero, coloco ovos.",
      "Tenho bico largo e pés adaptados à água.",
      "Sou um animal australiano chamado ornitorrinco.",
    ],
  },

  // ───────────────────────── Lugares
  {
    id: "place-brazil",
    answer: "Brasil",
    category: "places",
    difficulty: "easy",
    hints: [
      "Ocupo uma grande parte do meu continente.",
      "Tenho fronteira com quase todos os países da América do Sul.",
      "Minha língua oficial é o português.",
      "Minha bandeira é verde, amarela, azul e branca.",
      "Brasília é minha capital.",
    ],
  },
  {
    id: "place-japan",
    answer: "Japão",
    aliases: ["japao"],
    category: "places",
    difficulty: "easy",
    hints: [
      "Meu território é formado por milhares de ilhas.",
      "Tenho uma das maiores áreas metropolitanas do mundo.",
      "Anime e mangá são fortes partes da minha cultura popular.",
      "Minha bandeira possui um círculo vermelho.",
      "Tóquio é minha capital.",
    ],
  },
  {
    id: "place-france",
    answer: "França",
    aliases: ["franca"],
    category: "places",
    difficulty: "easy",
    hints: [
      "Tive enorme influência na arte, filosofia e política mundial.",
      "Sou um dos países mais visitados do mundo.",
      "Minha culinária é famosa por pães, queijos e confeitaria.",
      "A Torre Eiffel fica em mim.",
      "Paris é minha capital.",
    ],
  },
  {
    id: "place-egypt",
    answer: "Egito",
    category: "places",
    difficulty: "medium",
    hints: [
      "Uma das civilizações mais famosas da Antiguidade se desenvolveu em mim.",
      "Um grande rio foi essencial para minha história.",
      "Hieróglifos fazem parte do meu passado.",
      "Tenho pirâmides mundialmente famosas.",
      "O rio Nilo atravessa meu território.",
    ],
  },
  {
    id: "place-usa",
    answer: "Estados Unidos",
    aliases: ["eua", "estados unidos da america", "estados unidos da américa", "usa"],
    category: "places",
    difficulty: "medium",
    hints: [
      "Meu território principal se estende entre dois grandes oceanos.",
      "Sou formado por 50 estados.",
      "Hollywood e o Vale do Silício ficam em mim.",
      "Minha bandeira tem estrelas e listras.",
      "Washington, D.C. é minha capital.",
    ],
  },
  {
    id: "place-australia",
    answer: "Austrália",
    aliases: ["australia"],
    category: "places",
    difficulty: "medium",
    hints: [
      "Sou ao mesmo tempo um país e parte de um continente.",
      "Grande parte do meu interior é pouco povoada.",
      "Tenho animais que quase não existem naturalmente em outros lugares.",
      "Cangurus e coalas são fortemente associados a mim.",
      "Sydney é minha cidade mais conhecida, embora não seja minha capital.",
    ],
  },
  {
    id: "place-antarctica",
    answer: "Antártida",
    aliases: ["antartida", "antártica", "antartica"],
    category: "places",
    difficulty: "hard",
    hints: [
      "Não possuo população humana permanente.",
      "Guardo grande parte da água doce congelada do planeta.",
      "Sou considerado um deserto apesar de estar coberto de gelo.",
      "Fico ao redor do Polo Sul.",
      "Sou o continente mais frio da Terra.",
    ],
  },
  {
    id: "place-iceland",
    answer: "Islândia",
    aliases: ["islandia"],
    category: "places",
    difficulty: "hard",
    hints: [
      "Minha energia e paisagem são fortemente influenciadas pela atividade geológica.",
      "Tenho uma população pequena para o tamanho do território.",
      "Gêiseres, vulcões e fontes termais são comuns em mim.",
      "Fico no Atlântico Norte.",
      "Reykjavík é minha capital.",
    ],
  },

  // ───────────────────────── Comidas
  {
    id: "food-pizza",
    answer: "Pizza",
    category: "food",
    difficulty: "easy",
    hints: [
      "Posso variar tanto que quase cada lugar cria sua própria versão.",
      "Minha base normalmente é assada.",
      "Molho de tomate e queijo aparecem em muitas versões.",
      "Costumo ser cortada em fatias triangulares.",
      "Sou uma comida italiana redonda muito popular.",
    ],
  },
  {
    id: "food-hamburger",
    answer: "Hambúrguer",
    aliases: ["hamburguer", "burger"],
    category: "food",
    difficulty: "easy",
    hints: [
      "Minha versão moderna é fortemente associada à alimentação rápida.",
      "Posso ser feito com carne, frango, vegetais e muitas outras opções.",
      "Normalmente fico entre duas partes de um pão.",
      "Queijo, alface e molho são acompanhamentos comuns.",
      "Sou o sanduíche mais associado a redes de fast-food.",
    ],
  },
  {
    id: "food-brigadeiro",
    answer: "Brigadeiro",
    category: "food",
    difficulty: "easy",
    hints: [
      "Sou especialmente comum em festas no Brasil.",
      "Minha receita tradicional leva poucos ingredientes.",
      "Costumo ser servido em pequenas forminhas.",
      "Leite condensado e chocolate fazem parte da receita clássica.",
      "Sou uma bolinha doce normalmente coberta com granulado.",
    ],
  },
  {
    id: "food-sushi",
    answer: "Sushi",
    category: "food",
    difficulty: "medium",
    hints: [
      "Tenho muitas variações e nem todas levam peixe cru.",
      "Um tipo específico de arroz é essencial para mim.",
      "Posso usar alga marinha em várias versões.",
      "Sou servido frequentemente com shoyu.",
      "Sou um dos pratos japoneses mais conhecidos do mundo.",
    ],
  },
  {
    id: "food-acaraje",
    answer: "Acarajé",
    aliases: ["acaraje"],
    category: "food",
    difficulty: "medium",
    hints: [
      "Minha história no Brasil está fortemente ligada à cultura afro-brasileira.",
      "Minha massa tradicional usa feijão-fradinho.",
      "Sou frito em azeite de dendê.",
      "Vatapá e camarão podem aparecer no recheio.",
      "Sou uma comida muito associada à Bahia.",
    ],
  },
  {
    id: "food-lasagna",
    answer: "Lasanha",
    aliases: ["lasagna"],
    category: "food",
    difficulty: "medium",
    hints: [
      "Minha montagem é tão importante quanto meus ingredientes.",
      "Posso ter versões com carne, queijo, legumes e vários molhos.",
      "Sou preparada em camadas.",
      "Massa, molho e queijo costumam se repetir várias vezes.",
      "Sou um prato italiano assado chamado lasanha.",
    ],
  },
  {
    id: "food-risotto",
    answer: "Risoto",
    aliases: ["risotto"],
    category: "food",
    difficulty: "hard",
    hints: [
      "Meu preparo tradicional depende de adicionar líquido aos poucos.",
      "O amido do ingrediente principal ajuda a criar minha textura.",
      "Costumo ficar cremoso sem precisar de muito creme.",
      "Arroz arbóreo é uma variedade frequentemente usada.",
      "Sou um prato italiano de arroz chamado risoto.",
    ],
  },
  {
    id: "food-yakisoba",
    answer: "Yakisoba",
    aliases: ["yakissoba"],
    category: "food",
    difficulty: "hard",
    hints: [
      "Meu nome está ligado à ideia de algo grelhado ou frito.",
      "Tenho versões diferentes dependendo do país e da adaptação local.",
      "Legumes e molho costumam acompanhar meu ingrediente principal.",
      "Sou preparado com macarrão salteado.",
      "Sou conhecido no Brasil como yakisoba.",
    ],
  },

  // ───────────────────────── Objetos
  {
    id: "object-phone",
    answer: "Celular",
    aliases: ["telefone", "smartphone", "telefone celular"],
    category: "objects",
    difficulty: "easy",
    hints: [
      "Hoje faço muitas tarefas que antes exigiam vários aparelhos diferentes.",
      "Posso saber onde você está mesmo sem ser usado para fazer uma ligação.",
      "Minha bateria virou uma preocupação diária para muita gente.",
      "Tenho uma tela que você toca com os dedos.",
      "Você provavelmente está com um perto de você agora.",
    ],
  },
  {
    id: "object-umbrella",
    answer: "Guarda-chuva",
    aliases: ["guarda chuva", "sombrinha"],
    category: "objects",
    difficulty: "easy",
    hints: [
      "Passo bastante tempo fechado e quase sem ocupar espaço.",
      "Uma estrutura de varetas sustenta minha parte principal.",
      "Posso virar do avesso com vento forte.",
      "Sou aberto acima da cabeça.",
      "Sirvo para proteger da chuva.",
    ],
  },
  {
    id: "object-key",
    answer: "Chave",
    category: "objects",
    difficulty: "easy",
    hints: [
      "Posso ser minúscula e ainda assim impedir alguém de entrar.",
      "Existem versões físicas e digitais de mim.",
      "Costumo acompanhar algo que precisa ser protegido.",
      "Posso ficar num chaveiro.",
      "Sou usada para abrir uma fechadura.",
    ],
  },
  {
    id: "object-fridge",
    answer: "Geladeira",
    aliases: ["refrigerador", "frigorifico", "frigorífico"],
    category: "objects",
    difficulty: "medium",
    hints: [
      "Trabalho praticamente o dia inteiro.",
      "Tenho partes com temperaturas diferentes.",
      "Ajudo a diminuir a velocidade com que certos alimentos estragam.",
      "Normalmente fico na cozinha.",
      "Mantenho alimentos e bebidas frios.",
    ],
  },
  {
    id: "object-mirror",
    answer: "Espelho",
    category: "objects",
    difficulty: "medium",
    hints: [
      "O que mostro depende completamente do que está diante de mim.",
      "Posso fazer um espaço parecer maior.",
      "Minha superfície precisa refletir luz de maneira regular.",
      "Você costuma me usar para ver o próprio rosto.",
      "Mostro seu reflexo.",
    ],
  },
  {
    id: "object-keyboard",
    answer: "Teclado",
    category: "objects",
    difficulty: "medium",
    hints: [
      "Meu layout pode mudar conforme o idioma ou o país.",
      "Tenho teclas que raramente são usadas por algumas pessoas.",
      "Posso ser mecânico, de membrana ou até virtual.",
      "Normalmente fico na frente de um computador.",
      "Tenho letras, números, Enter e barra de espaço.",
    ],
  },
  {
    id: "object-compass",
    answer: "Bússola",
    aliases: ["bussola"],
    category: "objects",
    difficulty: "hard",
    hints: [
      "Consigo ser útil mesmo sem bateria ou conexão.",
      "Meu funcionamento tradicional depende do campo magnético da Terra.",
      "Tenho uma agulha que busca uma direção específica.",
      "Ajudo na orientação e navegação.",
      "Aponto para o norte magnético.",
    ],
  },
  {
    id: "object-extinguisher",
    answer: "Extintor",
    aliases: ["extintor de incendio", "extintor de incêndio"],
    category: "objects",
    difficulty: "hard",
    hints: [
      "Existem tipos diferentes de mim para problemas diferentes.",
      "Uma escolha errada do meu conteúdo pode piorar certas situações.",
      "Costumo ficar visível em prédios e veículos.",
      "Tenho pino de segurança e mangueira em muitas versões.",
      "Sou usado para combater princípios de incêndio.",
    ],
  },

  // ───────────────────────── Geral
  {
    id: "general-sun",
    answer: "Sol",
    category: "general",
    difficulty: "easy",
    hints: [
      "Represento quase toda a massa do sistema ao qual pertenço.",
      "Minha energia leva alguns minutos para chegar até vocês.",
      "Sou uma estrela.",
      "A Terra gira ao meu redor.",
      "Ilumino o dia.",
    ],
  },
  {
    id: "general-moon",
    answer: "Lua",
    category: "general",
    difficulty: "easy",
    hints: [
      "Minha aparência parece mudar em um ciclo regular.",
      "Não produzo a luz que normalmente vemos vindo de mim.",
      "Influencio fortemente as marés.",
      "Sou o satélite natural da Terra.",
      "Costumo aparecer no céu durante a noite.",
    ],
  },
  {
    id: "general-earth",
    answer: "Terra",
    aliases: ["planeta terra"],
    category: "general",
    difficulty: "easy",
    hints: [
      "Tenho uma superfície dominada por uma substância líquida.",
      "Possuo apenas um satélite natural grande.",
      "Sou o terceiro planeta a partir da minha estrela.",
      "Até hoje sou o único planeta conhecido com vida.",
      "É aqui que nós vivemos.",
    ],
  },
  {
    id: "general-rainbow",
    answer: "Arco-íris",
    aliases: ["arco iris"],
    category: "general",
    difficulty: "medium",
    hints: [
      "Dependo da posição de quem observa para ser visto.",
      "Não sou um objeto físico em um lugar fixo.",
      "Surjo quando a luz é separada em diferentes comprimentos de onda.",
      "Costumo aparecer quando há luz solar e gotas de água.",
      "Sou formado por várias cores em forma de arco.",
    ],
  },
  {
    id: "general-internet",
    answer: "Internet",
    category: "general",
    difficulty: "medium",
    hints: [
      "Não sou uma única máquina nem pertenço a uma única empresa.",
      "Conecto redes espalhadas pelo planeta.",
      "Posso continuar funcionando mesmo quando partes minhas ficam indisponíveis.",
      "Sites, mensagens e vídeos dependem de mim.",
      "Você está me usando para acessar muita coisa online.",
    ],
  },
  {
    id: "general-wifi",
    answer: "Wi-Fi",
    aliases: ["wifi", "wi fi"],
    category: "general",
    difficulty: "medium",
    hints: [
      "Posso existir mesmo quando a internet em si está fora do ar.",
      "Uso ondas de rádio para conectar dispositivos próximos.",
      "Roteadores domésticos costumam me fornecer.",
      "Minha força costuma aparecer em barrinhas no celular.",
      "Sou a conexão sem fio chamada Wi-Fi.",
    ],
  },
  {
    id: "general-eclipse",
    answer: "Eclipse",
    aliases: ["eclipse solar", "eclipse lunar"],
    category: "general",
    difficulty: "hard",
    hints: [
      "Só aconteço quando certos corpos celestes ficam alinhados.",
      "Posso ser parcial ou total.",
      "Existem versões minhas envolvendo a sombra da Terra ou da Lua.",
      "Durante uma das minhas formas, o dia pode escurecer por alguns minutos.",
      "Aconteço quando um astro encobre outro para um observador.",
    ],
  },
  {
    id: "general-aurora",
    answer: "Aurora Boreal",
    aliases: ["aurora", "northern lights", "luzes do norte"],
    category: "general",
    difficulty: "hard",
    hints: [
      "Sou causada por partículas vindas do espaço interagindo com a atmosfera.",
      "Apareço com maior frequência em regiões próximas aos polos.",
      "Posso formar cortinas e faixas que parecem se mover.",
      "Verde é uma das minhas cores mais comuns.",
      "Sou conhecida como luzes do norte.",
    ],
  },

  // ───────────────────────── NOVOS: Filmes e Séries
  {
    id: "movie-avengers",
    answer: "Os Vingadores",
    aliases: ["vingadores", "the avengers"],
    category: "moviesSeries",
    difficulty: "easy",
    hints: [
      "Reúno personagens que antes estrelavam histórias separadas.",
      "Uma ameaça externa força heróis muito diferentes a trabalharem juntos.",
      "Um bilionário de armadura e um deus nórdico fazem parte do grupo.",
      "Meu universo cinematográfico é da Marvel.",
      "Meu grupo inclui Homem de Ferro, Thor, Hulk e Capitão América.",
    ],
  },
  {
    id: "series-friends",
    answer: "Friends",
    category: "moviesSeries",
    difficulty: "easy",
    hints: [
      "Minha história acompanha um grupo de adultos jovens ao longo de vários anos.",
      "Grande parte das conversas acontece em apartamentos e num café.",
      "Sou ambientada em Nova York.",
      "Central Perk é um lugar recorrente.",
      "Ross, Rachel, Monica, Chandler, Joey e Phoebe são meus protagonistas.",
    ],
  },
  {
    id: "movie-toy-story",
    answer: "Toy Story",
    aliases: ["toy story"],
    category: "moviesSeries",
    difficulty: "easy",
    hints: [
      "Meu conflito inicial envolve ciúme e medo de ser substituído.",
      "Meus protagonistas fingem ser inanimados quando humanos aparecem.",
      "Um quarto infantil é um cenário importante.",
      "Tenho um cowboy e um patrulheiro espacial como protagonistas.",
      "Woody e Buzz Lightyear são meus personagens centrais.",
    ],
  },
  {
    id: "movie-jurassic-park",
    answer: "Jurassic Park",
    aliases: ["parque dos dinossauros", "jurassic park"],
    category: "moviesSeries",
    difficulty: "easy",
    hints: [
      "Uma tecnologia científica torna possível algo que deveria pertencer ao passado.",
      "Um parque de atrações é construído em uma ilha.",
      "A segurança falha de forma catastrófica.",
      "Dinossauros são a principal atração e também o principal perigo.",
      "Meu título em inglês é Jurassic Park.",
    ],
  },
  {
    id: "series-game-of-thrones",
    answer: "Game of Thrones",
    aliases: ["got", "game of thrones"],
    category: "moviesSeries",
    difficulty: "medium",
    hints: [
      "Famílias poderosas disputam influência ao longo de vários territórios.",
      "Meu mundo mistura política, guerra e fantasia.",
      "Um trono feito de espadas simboliza poder.",
      "Dragões e uma ameaça vinda do norte têm grande importância.",
      "Stark, Lannister e Targaryen são famílias centrais.",
    ],
  },
  {
    id: "movie-matrix",
    answer: "Matrix",
    aliases: ["the matrix", "matrix"],
    category: "moviesSeries",
    difficulty: "medium",
    hints: [
      "Minha história questiona se a realidade percebida é realmente verdadeira.",
      "Máquinas e inteligência artificial têm papel decisivo no mundo.",
      "Uma escolha entre duas pílulas virou símbolo cultural.",
      "Meu protagonista é conhecido como Neo.",
      "Minha realidade virtual é chamada Matrix.",
    ],
  },
  {
    id: "series-the-office",
    answer: "The Office",
    aliases: ["the office us", "the office"],
    category: "moviesSeries",
    difficulty: "medium",
    hints: [
      "Meu humor vem de situações extremamente comuns transformadas em constrangimento.",
      "A câmera é tratada como parte do ambiente.",
      "A maior parte da história acontece em um local de trabalho.",
      "Dunder Mifflin vende papel.",
      "Michael Scott é um dos meus personagens mais famosos.",
    ],
  },
  {
    id: "movie-lord-of-the-rings",
    answer: "O Senhor dos Anéis",
    aliases: ["senhor dos aneis", "o senhor dos anéis", "lord of the rings", "lotr"],
    category: "moviesSeries",
    difficulty: "medium",
    hints: [
      "Uma jornada precisa impedir que um objeto extremamente poderoso volte ao seu criador.",
      "Meu mundo possui povos como elfos, anões e hobbits.",
      "A Sociedade é formada para cumprir uma missão.",
      "Mordor é um destino central.",
      "Frodo carrega um anel que precisa ser destruído.",
    ],
  },
  {
    id: "series-dark",
    answer: "Dark",
    category: "moviesSeries",
    difficulty: "hard",
    hints: [
      "Minha narrativa exige atenção a relações familiares e acontecimentos separados por décadas.",
      "Uma pequena cidade esconde conexões que atravessam gerações.",
      "Cavernas têm papel importante na trama.",
      "Viagens no tempo estão no centro da história.",
      "Sou uma série alemã chamada Dark.",
    ],
  },
  {
    id: "movie-pulp-fiction",
    answer: "Pulp Fiction",
    aliases: ["tempos de violencia", "tempos de violência"],
    category: "moviesSeries",
    difficulty: "hard",
    hints: [
      "Minha narrativa não segue uma ordem cronológica simples.",
      "Histórias de criminosos se cruzam em Los Angeles.",
      "Uma maleta misteriosa aparece em momentos importantes.",
      "Vincent Vega e Jules Winnfield são personagens centrais.",
      "Sou um filme de Quentin Tarantino chamado Pulp Fiction.",
    ],
  },
  {
    id: "series-better-call-saul",
    answer: "Better Call Saul",
    aliases: ["better call saul"],
    category: "moviesSeries",
    difficulty: "hard",
    hints: [
      "Minha história acompanha a transformação gradual de um profissional ambicioso.",
      "Sou ligada a outra série criminal muito famosa.",
      "Meu protagonista começa usando outro nome profissional.",
      "Kim Wexler é uma personagem fundamental.",
      "Jimmy McGill acaba se tornando Saul Goodman.",
    ],
  },
  {
    id: "movie-shawshank",
    answer: "Um Sonho de Liberdade",
    aliases: ["shawshank redemption", "the shawshank redemption", "um sonho de liberdade"],
    category: "moviesSeries",
    difficulty: "hard",
    hints: [
      "Minha história gira em torno de esperança mantida por muitos anos.",
      "Grande parte da trama acontece dentro de uma prisão.",
      "Uma amizade entre dois detentos é o coração da narrativa.",
      "Andy Dufresne é o protagonista.",
      "Meu título em inglês é The Shawshank Redemption.",
    ],
  },

  // ───────────────────────── NOVOS: Games
  {
    id: "game-pokemon",
    answer: "Pokémon",
    aliases: ["pokemon"],
    category: "games",
    difficulty: "easy",
    hints: [
      "Minha franquia gira em torno de colecionar e treinar criaturas.",
      "Combates são parte importante da progressão.",
      "Existem tipos com vantagens e fraquezas.",
      "Pikachu é meu mascote mais conhecido.",
      "Meu lema popular envolve capturar todos.",
    ],
  },
  {
    id: "game-sonic",
    answer: "Sonic",
    aliases: ["sonic the hedgehog", "sonic"],
    category: "games",
    difficulty: "easy",
    hints: [
      "Meu protagonista é conhecido principalmente por uma característica física extraordinária.",
      "Anéis aparecem como item recorrente.",
      "Meu rival clássico é um cientista.",
      "Sou associado à empresa Sega.",
      "Meu protagonista é um ouriço azul muito veloz.",
    ],
  },
  {
    id: "game-the-sims",
    answer: "The Sims",
    aliases: ["sims", "the sims"],
    category: "games",
    difficulty: "easy",
    hints: [
      "Não tenho um objetivo final obrigatório.",
      "Você controla necessidades, relacionamentos e rotina de personagens.",
      "Construir e decorar casas é uma parte importante.",
      "Meus personagens falam Simlish.",
      "Sou um simulador de vida chamado The Sims.",
    ],
  },
  {
    id: "game-counter-strike",
    answer: "Counter-Strike",
    aliases: ["cs", "csgo", "cs2", "counter strike"],
    category: "games",
    difficulty: "easy",
    hints: [
      "Minhas partidas colocam duas equipes com objetivos opostos.",
      "Economia e compra de armas fazem parte de cada rodada.",
      "Alguns mapas giram em torno de plantar ou desarmar um dispositivo.",
      "Terroristas e contra-terroristas são os lados clássicos.",
      "Sou conhecido pelas siglas CS, CS:GO e CS2.",
    ],
  },
  {
    id: "game-zelda",
    answer: "The Legend of Zelda",
    aliases: ["zelda", "legend of zelda", "the legend of zelda"],
    category: "games",
    difficulty: "medium",
    hints: [
      "Minha série costuma reinventar o mesmo conflito em eras diferentes.",
      "Exploração e resolução de quebra-cabeças são muito importantes.",
      "Uma relíquia formada por três partes aparece em várias histórias.",
      "Meu herói normalmente se chama Link.",
      "Meu título é The Legend of Zelda.",
    ],
  },
  {
    id: "game-red-dead-redemption",
    answer: "Red Dead Redemption",
    aliases: ["red dead", "rdr", "rdr2", "red dead redemption 2"],
    category: "games",
    difficulty: "medium",
    hints: [
      "Minha história se passa num período de transição entre velho e novo mundo.",
      "Gangues e foras da lei são centrais na narrativa.",
      "Cavalos são fundamentais para locomoção.",
      "O Velho Oeste é meu cenário.",
      "Arthur Morgan é o protagonista mais lembrado do meu segundo jogo.",
    ],
  },
  {
    id: "game-valorant",
    answer: "Valorant",
    category: "games",
    difficulty: "medium",
    hints: [
      "Combino tiro tático com habilidades específicas de personagens.",
      "Cada rodada exige economia de equipamentos.",
      "Dois times alternam entre ataque e defesa.",
      "Um dispositivo chamado Spike é central em muitos rounds.",
      "Sou um FPS competitivo da Riot Games.",
    ],
  },
  {
    id: "game-god-of-war",
    answer: "God of War",
    aliases: ["god of war"],
    category: "games",
    difficulty: "medium",
    hints: [
      "Meu protagonista teve uma relação complicada com deuses ao longo da série.",
      "Minha franquia mudou de mitologia ao longo do tempo.",
      "Machados e lâminas são armas marcantes.",
      "Atreus acompanha o protagonista em jogos recentes.",
      "Kratos é meu personagem principal.",
    ],
  },
  {
    id: "game-hollow-knight",
    answer: "Hollow Knight",
    aliases: ["hollow knight"],
    category: "games",
    difficulty: "hard",
    hints: [
      "Exploração de um reino subterrâneo em decadência define minha experiência.",
      "Meu mundo é habitado por criaturas semelhantes a insetos.",
      "A progressão abre caminhos anteriormente inacessíveis.",
      "Hallownest é meu reino.",
      "Meu protagonista pequeno usa um ferrão como arma.",
    ],
  },
  {
    id: "game-bloodborne",
    answer: "Bloodborne",
    category: "games",
    difficulty: "hard",
    hints: [
      "Meu mundo mistura horror gótico com algo muito mais cósmico.",
      "O combate recompensa agressividade após receber dano.",
      "Yharnam é uma cidade central.",
      "Caçadores enfrentam feras e criaturas incompreensíveis.",
      "Sou um RPG de ação da FromSoftware chamado Bloodborne.",
    ],
  },
  {
    id: "game-dota2",
    answer: "Dota 2",
    aliases: ["dota", "dota2"],
    category: "games",
    difficulty: "hard",
    hints: [
      "Sou descendente de um mapa criado dentro de outro jogo.",
      "Duas equipes disputam três rotas principais.",
      "Heróis possuem habilidades e funções diferentes.",
      "O objetivo é destruir uma estrutura chamada Ancient.",
      "Sou um MOBA chamado Dota 2.",
    ],
  },
  {
    id: "game-death-stranding",
    answer: "Death Stranding",
    aliases: ["death stranding"],
    category: "games",
    difficulty: "hard",
    hints: [
      "Conectar locais separados é mais importante que derrotar inimigos.",
      "Carga, equilíbrio e terreno fazem parte do desafio.",
      "Fenômenos sobrenaturais alteraram profundamente o mundo.",
      "Sam Porter Bridges é o protagonista.",
      "Sou um jogo dirigido por Hideo Kojima chamado Death Stranding.",
    ],
  },

  // ───────────────────────── NOVOS: Personagens
  {
    id: "character-ironman",
    answer: "Homem de Ferro",
    aliases: ["homem de ferro", "iron man", "tony stark"],
    category: "characters",
    difficulty: "easy",
    hints: [
      "Minha maior habilidade vem principalmente de tecnologia criada por mim.",
      "Sou conhecido por um estilo de vida luxuoso e personalidade confiante.",
      "Tenho uma inteligência excepcional para engenharia.",
      "Tony Stark é minha identidade.",
      "Uso uma armadura tecnológica vermelha e dourada.",
    ],
  },
  {
    id: "character-hulk",
    answer: "Hulk",
    aliases: ["bruce banner"],
    category: "characters",
    difficulty: "easy",
    hints: [
      "Minha transformação está ligada a um acidente científico.",
      "Minha força aumenta drasticamente quando perco o controle emocional.",
      "Minha outra identidade é um cientista.",
      "Bruce Banner é meu nome humano.",
      "Sou um gigante verde extremamente forte.",
    ],
  },
  {
    id: "character-wonder-woman",
    answer: "Mulher-Maravilha",
    aliases: ["mulher maravilha", "wonder woman", "diana prince"],
    category: "characters",
    difficulty: "easy",
    hints: [
      "Minha origem está ligada a uma ilha isolada do mundo comum.",
      "Fui criada entre guerreiras.",
      "Uso um laço muito famoso.",
      "Diana Prince é uma das minhas identidades.",
      "Sou a heroína amazona conhecida como Mulher-Maravilha.",
    ],
  },
  {
    id: "character-thanos",
    answer: "Thanos",
    category: "characters",
    difficulty: "easy",
    hints: [
      "Meu objetivo é apresentado por mim como uma forma extrema de equilíbrio.",
      "Procuro reunir objetos de poder cósmico.",
      "Uma luva permite usar esse poder.",
      "Sou um grande vilão do universo Marvel.",
      "Fiquei famoso por usar as Joias do Infinito.",
    ],
  },
  {
    id: "character-captain-america",
    answer: "Capitão América",
    aliases: ["capitao america", "captain america", "steve rogers"],
    category: "characters",
    difficulty: "medium",
    hints: [
      "Antes de me tornar herói, eu não tinha o físico necessário para lutar.",
      "Um experimento mudou meu corpo.",
      "Fiquei fora de meu tempo original por décadas.",
      "Steve Rogers é meu nome.",
      "Uso um escudo circular com estrela.",
    ],
  },
  {
    id: "character-hermione",
    answer: "Hermione Granger",
    aliases: ["hermione"],
    category: "characters",
    difficulty: "medium",
    hints: [
      "Meu conhecimento costuma resolver problemas que força bruta não resolve.",
      "Nasci fora da comunidade mágica tradicional.",
      "Sou uma das melhores alunas da minha geração.",
      "Faço parte do trio principal de Harry Potter.",
      "Meu nome é Hermione Granger.",
    ],
  },
  {
    id: "character-elsa",
    answer: "Elsa",
    aliases: ["rainha elsa"],
    category: "characters",
    difficulty: "medium",
    hints: [
      "Passei muito tempo escondendo uma capacidade que não conseguia controlar.",
      "Meu medo afeta diretamente quem está ao meu redor.",
      "Minha irmã é extremamente importante para mim.",
      "Posso criar gelo e neve.",
      "Sou a rainha Elsa de Frozen.",
    ],
  },
  {
    id: "character-jack-sparrow",
    answer: "Jack Sparrow",
    aliases: ["capitao jack sparrow", "capitão jack sparrow", "jack sparrow"],
    category: "characters",
    difficulty: "medium",
    hints: [
      "Minha reputação é maior do que minha confiabilidade.",
      "Costumo escapar de situações usando improviso e sorte.",
      "Tenho uma relação complicada com um navio específico.",
      "Sou um pirata excêntrico.",
      "Meu nome é Capitão Jack Sparrow.",
    ],
  },
  {
    id: "character-neo",
    answer: "Neo",
    aliases: ["thomas anderson", "neo matrix"],
    category: "characters",
    difficulty: "hard",
    hints: [
      "Minha identidade cotidiana não é a que realmente define meu papel.",
      "Descubro que o mundo percebido por mim esconde uma verdade muito maior.",
      "Tenho uma relação central com uma escolha entre duas pílulas.",
      "Morpheus acredita que sou alguém especial.",
      "Sou o protagonista de Matrix conhecido como Neo.",
    ],
  },
  {
    id: "character-geralt",
    answer: "Geralt de Rívia",
    aliases: ["geralt", "geralt de rivia", "geralt de rívia"],
    category: "characters",
    difficulty: "hard",
    hints: [
      "Fui treinado desde jovem para exercer uma profissão perigosa.",
      "Meu corpo foi alterado para melhorar minhas capacidades.",
      "Viajo aceitando contratos ligados a criaturas.",
      "Sou conhecido como Lobo Branco.",
      "Sou o bruxo Geralt de Rívia.",
    ],
  },
  {
    id: "character-tyrion",
    answer: "Tyrion Lannister",
    aliases: ["tyrion"],
    category: "characters",
    difficulty: "hard",
    hints: [
      "Minha inteligência e habilidade verbal são minhas principais armas.",
      "Nasci numa família extremamente poderosa e conflituosa.",
      "Minha relação com meu pai é marcada por desprezo.",
      "Sou um Lannister.",
      "Meu nome é Tyrion Lannister.",
    ],
  },
  {
    id: "character-voldemort",
    answer: "Voldemort",
    aliases: ["lord voldemort", "tom riddle", "tom riddlle", "tom marvolo riddle"],
    category: "characters",
    difficulty: "hard",
    hints: [
      "Meu medo da morte influencia muitas das minhas escolhas.",
      "Dividi algo essencial de mim para tentar evitar meu fim.",
      "Minha aparência mudou profundamente ao longo da vida.",
      "Meu nome de nascimento é Tom Riddle.",
      "Sou o principal vilão de Harry Potter.",
    ],
  },

  // ───────────────────────── NOVOS: Anime e Desenhos
  {
    id: "anime-pikachu",
    answer: "Pikachu",
    category: "animeCartoons",
    difficulty: "easy",
    hints: [
      "Sou pequeno, mas tenho uma habilidade ofensiva muito conhecida.",
      "Minha espécie é reconhecida por duas cores principais.",
      "Tenho ligação forte com um treinador chamado Ash.",
      "Uso eletricidade em combate.",
      "Sou o Pokémon amarelo mais famoso.",
    ],
  },
  {
    id: "cartoon-tom-jerry",
    answer: "Tom e Jerry",
    aliases: ["tom & jerry", "tom and jerry", "tom e jerry"],
    category: "animeCartoons",
    difficulty: "easy",
    hints: [
      "Minha dinâmica principal quase nunca muda, mesmo depois de muitas décadas.",
      "Um vive perseguindo o outro.",
      "Grande parte do humor é físico e quase sem diálogos.",
      "Sou uma dupla formada por um gato e um rato.",
      "Meus nomes são Tom e Jerry.",
    ],
  },
  {
    id: "cartoon-bugs-bunny",
    answer: "Pernalonga",
    aliases: ["bugs bunny", "pernalonga"],
    category: "animeCartoons",
    difficulty: "easy",
    hints: [
      "Costumo manter a calma enquanto provoco meus adversários.",
      "Minha imagem está ligada a uma comida específica.",
      "Sou um personagem clássico da Warner.",
      "Sou um coelho cinza.",
      "Minha frase é frequentemente associada a perguntar 'o que é que há, velhinho?'.",
    ],
  },
  {
    id: "anime-sailor-moon",
    answer: "Sailor Moon",
    aliases: ["sailor moon"],
    category: "animeCartoons",
    difficulty: "easy",
    hints: [
      "Minha vida comum muda quando descubro uma identidade especial.",
      "Minhas amigas também possuem poderes e identidades próprias.",
      "A Lua é central na minha história.",
      "Uso transformação mágica para lutar.",
      "Sou a heroína Sailor Moon.",
    ],
  },
  {
    id: "anime-vegeta",
    answer: "Vegeta",
    category: "animeCartoons",
    difficulty: "medium",
    hints: [
      "Meu orgulho é uma das características mais marcantes da minha personalidade.",
      "Comecei como adversário antes de me tornar aliado recorrente.",
      "Sou príncipe de uma raça guerreira.",
      "Minha rivalidade com Goku é famosa.",
      "Sou Vegeta de Dragon Ball.",
    ],
  },
  {
    id: "anime-sasuke",
    answer: "Sasuke Uchiha",
    aliases: ["sasuke", "sasuke uchiha"],
    category: "animeCartoons",
    difficulty: "medium",
    hints: [
      "Minha infância foi marcada por uma tragédia envolvendo minha própria família.",
      "Passei grande parte da história buscando poder e respostas.",
      "Faço parte de um clã com uma habilidade ocular especial.",
      "Sou rival e amigo de Naruto.",
      "Meu sobrenome é Uchiha.",
    ],
  },
  {
    id: "cartoon-avatar-aang",
    answer: "Aang",
    aliases: ["avatar aang", "aang"],
    category: "animeCartoons",
    difficulty: "medium",
    hints: [
      "Passei muito tempo ausente enquanto o mundo entrava em guerra.",
      "Sou o último sobrevivente conhecido de meu povo.",
      "Preciso dominar vários elementos.",
      "Sou o Avatar.",
      "Tenho uma seta azul na cabeça.",
    ],
  },
  {
    id: "cartoon-scooby-shaggy",
    answer: "Salsicha",
    aliases: ["shaggy", "norville rogers", "salsicha rogers"],
    category: "animeCartoons",
    difficulty: "medium",
    hints: [
      "Minha coragem costuma desaparecer justamente quando mais preciso dela.",
      "Tenho um melhor amigo não humano.",
      "Comida é uma grande motivação para mim.",
      "Faço parte da turma do Scooby-Doo.",
      "Sou conhecido no Brasil como Salsicha.",
    ],
  },
  {
    id: "anime-light-yagami",
    answer: "Light Yagami",
    aliases: ["light", "kira", "light yagami"],
    category: "animeCartoons",
    difficulty: "hard",
    hints: [
      "Começo acreditando que posso criar um mundo melhor por meio de uma justiça extrema.",
      "Um objeto aparentemente simples me dá enorme poder.",
      "Sou perseguido por um investigador extremamente inteligente.",
      "Uso o nome Kira.",
      "Sou o protagonista de Death Note chamado Light Yagami.",
    ],
  },
  {
    id: "anime-edward-elric",
    answer: "Edward Elric",
    aliases: ["edward", "edward elric"],
    category: "animeCartoons",
    difficulty: "hard",
    hints: [
      "Uma tentativa de quebrar uma regra fundamental mudou meu corpo e minha família.",
      "Procuro recuperar algo perdido junto com meu irmão.",
      "Uso uma forma de ciência fictícia baseada em troca equivalente.",
      "Sou conhecido como Alquimista de Aço.",
      "Meu nome é Edward Elric.",
    ],
  },
  {
    id: "anime-levi",
    answer: "Levi Ackerman",
    aliases: ["levi", "levi ackerman"],
    category: "animeCartoons",
    difficulty: "hard",
    hints: [
      "Sou extremamente disciplinado e conhecido por minha habilidade em combate.",
      "Minha infância aconteceu em condições difíceis.",
      "Faço parte de uma organização militar de exploração.",
      "Combato gigantes usando equipamento de mobilidade.",
      "Sou o capitão Levi de Attack on Titan.",
    ],
  },
  {
    id: "cartoon-bojack",
    answer: "BoJack Horseman",
    aliases: ["bojack", "bojack horseman"],
    category: "animeCartoons",
    difficulty: "hard",
    hints: [
      "Minha fama veio de uma carreira que já passou do auge.",
      "Minha história mistura humor com temas bastante pesados.",
      "Vivo em um mundo onde humanos e animais antropomórficos convivem.",
      "Fui astro de uma sitcom chamada Horsin' Around.",
      "Sou um cavalo chamado BoJack Horseman.",
    ],
  },

  // ───────────────────────── NOVOS: Famosos
  {
    id: "famous-pele",
    answer: "Pelé",
    aliases: ["pele", "edson arantes do nascimento"],
    category: "famous",
    difficulty: "easy",
    hints: [
      "Comecei a ganhar destaque internacional ainda adolescente.",
      "Minha carreira ficou fortemente ligada a um clube brasileiro.",
      "Venci várias vezes a principal competição de seleções do futebol.",
      "Sou um dos maiores nomes da história do futebol.",
      "Fiquei conhecido como Rei do Futebol.",
    ],
  },
  {
    id: "famous-silvio-santos",
    answer: "Silvio Santos",
    aliases: ["silvio santos", "senor abravanel"],
    category: "famous",
    difficulty: "easy",
    hints: [
      "Minha carreira começou muito antes de eu me tornar dono de uma emissora.",
      "Minha forma de falar e interagir com plateias virou marca registrada.",
      "Apresentei programas de auditório por décadas.",
      "Fui o rosto mais famoso do SBT.",
      "Meu nome artístico é Silvio Santos.",
    ],
  },
  {
    id: "famous-lady-gaga",
    answer: "Lady Gaga",
    aliases: ["gaga", "lady gaga"],
    category: "famous",
    difficulty: "easy",
    hints: [
      "Minha carreira mistura música, moda e performances visuais marcantes.",
      "Já atuei em filmes além de cantar.",
      "Usei figurinos extremamente chamativos em eventos públicos.",
      "'Poker Face' e 'Bad Romance' são músicas minhas.",
      "Meu nome artístico é Lady Gaga.",
    ],
  },
  {
    id: "famous-dwayne-johnson",
    answer: "Dwayne Johnson",
    aliases: ["the rock", "dwayne the rock johnson", "dwayne johnson"],
    category: "famous",
    difficulty: "easy",
    hints: [
      "Minha carreira de entretenimento começou em outro tipo de espetáculo.",
      "Depois migrei com enorme sucesso para o cinema.",
      "Fiquei conhecido por um apelido curto.",
      "Atuei como lutador profissional.",
      "Sou Dwayne 'The Rock' Johnson.",
    ],
  },
  {
    id: "famous-adele",
    answer: "Adele",
    aliases: ["adele adkins", "adele"],
    category: "famous",
    difficulty: "medium",
    hints: [
      "Minha carreira é marcada por álbuns nomeados com números.",
      "Minha voz é uma das minhas principais marcas.",
      "Sou britânica.",
      "'Someone Like You' é uma das minhas músicas mais famosas.",
      "Meu nome artístico é Adele.",
    ],
  },
  {
    id: "famous-leonardo-dicaprio",
    answer: "Leonardo DiCaprio",
    aliases: ["dicaprio", "leonardo dicaprio"],
    category: "famous",
    difficulty: "medium",
    hints: [
      "Comecei a atuar ainda jovem e me tornei um dos atores mais conhecidos de minha geração.",
      "Trabalhei várias vezes com diretores muito famosos.",
      "Interpretei um personagem chamado Jack em um grande romance trágico.",
      "Ganhei o Oscar por O Regresso.",
      "Meu nome é Leonardo DiCaprio.",
    ],
  },
  {
    id: "famous-ivete-sangalo",
    answer: "Ivete Sangalo",
    aliases: ["ivete", "ivete sangalo"],
    category: "famous",
    difficulty: "medium",
    hints: [
      "Minha carreira é fortemente ligada à música e ao carnaval brasileiro.",
      "Antes da carreira solo, fui vocalista de uma banda.",
      "Tenho forte ligação com a Bahia.",
      "Fui vocalista da Banda Eva.",
      "Meu nome é Ivete Sangalo.",
    ],
  },
  {
    id: "famous-kevin-hart",
    answer: "Kevin Hart",
    aliases: ["kevin hart"],
    category: "famous",
    difficulty: "medium",
    hints: [
      "Fiquei conhecido primeiro por apresentações de humor.",
      "Depois me tornei presença frequente em grandes comédias de Hollywood.",
      "Minha altura é frequentemente usada como tema de piadas.",
      "Já contracenei várias vezes com Dwayne Johnson.",
      "Sou o comediante e ator Kevin Hart.",
    ],
  },
  {
    id: "famous-hayao-miyazaki",
    answer: "Hayao Miyazaki",
    aliases: ["miyazaki", "hayao miyazaki"],
    category: "famous",
    difficulty: "hard",
    hints: [
      "Minha obra é marcada por mundos imaginativos e temas ambientais.",
      "Sou conhecido mais por dirigir e animar do que por aparecer em frente às câmeras.",
      "Ajudei a fundar um estúdio japonês muito famoso.",
      "Dirigi A Viagem de Chihiro.",
      "Meu sobrenome é Miyazaki.",
    ],
  },
  {
    id: "famous-nikola-tesla",
    answer: "Nikola Tesla",
    aliases: ["tesla", "nikola tesla"],
    category: "famous",
    difficulty: "hard",
    hints: [
      "Trabalhei com eletricidade em uma época de intensa disputa tecnológica.",
      "Minhas ideias envolveram sistemas de corrente alternada.",
      "Meu sobrenome hoje também é conhecido por uma empresa de carros elétricos.",
      "Fui inventor e engenheiro.",
      "Meu nome é Nikola Tesla.",
    ],
  },
  {
    id: "famous-frida-kahlo",
    answer: "Frida Kahlo",
    aliases: ["frida", "frida kahlo"],
    category: "famous",
    difficulty: "hard",
    hints: [
      "Minha vida pessoal e minha dor física influenciaram fortemente minha arte.",
      "Produzi muitos autorretratos.",
      "Tive relação com outro artista mexicano muito famoso.",
      "Minhas sobrancelhas são uma característica visual muito reconhecida.",
      "Sou a pintora mexicana Frida Kahlo.",
    ],
  },
  {
    id: "famous-freddie-mercury",
    answer: "Freddie Mercury",
    aliases: ["freddie", "freddie mercury"],
    category: "famous",
    difficulty: "hard",
    hints: [
      "Minha presença de palco foi tão marcante quanto minha voz.",
      "Fui vocalista de uma banda britânica de rock.",
      "Participei de uma apresentação histórica no Live Aid.",
      "'Bohemian Rhapsody' está fortemente ligada à minha carreira.",
      "Sou o vocalista do Queen, Freddie Mercury.",
    ],
  },

  // ───────────────────────── NOVOS: Animais
  {
    id: "animal-lion",
    answer: "Leão",
    aliases: ["leao"],
    category: "animals",
    difficulty: "easy",
    hints: [
      "Vivo em grupos sociais mais estruturados que muitos outros grandes felinos.",
      "Machos e fêmeas podem ter papéis diferentes na caça e defesa.",
      "Uma juba é comum nos machos adultos.",
      "Sou chamado de rei dos animais.",
      "Sou um grande felino africano conhecido como leão.",
    ],
  },
  {
    id: "animal-giraffe",
    answer: "Girafa",
    category: "animals",
    difficulty: "easy",
    hints: [
      "Meu corpo possui adaptações para alcançar alimentos muito acima do chão.",
      "Minha pressão sanguínea precisa lidar com uma grande distância vertical.",
      "Tenho manchas pelo corpo.",
      "Meu pescoço é extremamente longo.",
      "Sou a girafa.",
    ],
  },
  {
    id: "animal-dolphin",
    answer: "Golfinho",
    aliases: ["delfim"],
    category: "animals",
    difficulty: "easy",
    hints: [
      "Sou um mamífero que vive na água.",
      "Tenho comportamento social complexo.",
      "Uso sons para comunicação e localização.",
      "Sou conhecido por nadar ao lado de barcos.",
      "Sou um cetáceo chamado golfinho.",
    ],
  },
  {
    id: "animal-monkey",
    answer: "Macaco",
    aliases: ["macaca"],
    category: "animals",
    difficulty: "easy",
    hints: [
      "Faço parte de um grupo de mamíferos com grande habilidade manual.",
      "Algumas espécies vivem em sociedades muito complexas.",
      "Muitas espécies passam bastante tempo em árvores.",
      "Sou um primata.",
      "Sou conhecido popularmente como macaco.",
    ],
  },
  {
    id: "animal-owl",
    answer: "Coruja",
    category: "animals",
    difficulty: "medium",
    hints: [
      "Minha audição ajuda a localizar presas mesmo com pouca luz.",
      "Tenho adaptações que tornam meu voo silencioso.",
      "Meus olhos ficam voltados para frente.",
      "Sou uma ave frequentemente ativa à noite.",
      "Sou a coruja.",
    ],
  },
  {
    id: "animal-octopus",
    answer: "Polvo",
    category: "animals",
    difficulty: "medium",
    hints: [
      "Meu sistema nervoso é distribuído de forma incomum pelo corpo.",
      "Posso resolver problemas e abrir recipientes.",
      "Consigo mudar cor e textura.",
      "Tenho oito braços.",
      "Sou um molusco chamado polvo.",
    ],
  },
  {
    id: "animal-koala",
    answer: "Coala",
    aliases: ["koala"],
    category: "animals",
    difficulty: "medium",
    hints: [
      "Minha dieta é extremamente especializada.",
      "Passo grande parte do dia descansando.",
      "Sou marsupial.",
      "Como folhas de eucalipto.",
      "Sou um animal australiano chamado coala.",
    ],
  },
  {
    id: "animal-crocodile",
    answer: "Crocodilo",
    category: "animals",
    difficulty: "medium",
    hints: [
      "Minha linhagem existe há muito tempo com poucas mudanças fundamentais.",
      "Posso ficar quase imóvel antes de atacar.",
      "Tenho uma mordida extremamente forte.",
      "Sou um grande réptil semiaquático.",
      "Sou o crocodilo.",
    ],
  },
  {
    id: "animal-axolotl",
    answer: "Axolote",
    aliases: ["axolotl", "axolote"],
    category: "animals",
    difficulty: "hard",
    hints: [
      "Conservo características juvenis durante toda a vida.",
      "Tenho uma capacidade de regeneração extraordinária.",
      "Sou um anfíbio.",
      "Minhas brânquias externas parecem penas ao redor da cabeça.",
      "Sou conhecido como axolote.",
    ],
  },
  {
    id: "animal-narwhal",
    answer: "Narval",
    category: "animals",
    difficulty: "hard",
    hints: [
      "Vivo em águas frias do hemisfério norte.",
      "Uma estrutura longa e espiralada é na verdade um dente.",
      "Sou um cetáceo.",
      "Sou chamado às vezes de unicórnio do mar.",
      "Sou o narval.",
    ],
  },
  {
    id: "animal-mantis-shrimp",
    answer: "Camarão-louva-a-deus",
    aliases: ["camarao louva a deus", "camarão mantis", "mantis shrimp"],
    category: "animals",
    difficulty: "hard",
    hints: [
      "Minha visão detecta informações que humanos não percebem.",
      "Algumas espécies golpeiam com aceleração impressionante.",
      "Apesar do nome, não sou um camarão verdadeiro.",
      "Sou um crustáceo extremamente colorido.",
      "Sou conhecido como camarão-louva-a-deus.",
    ],
  },
  {
    id: "animal-tardigrade",
    answer: "Tardígrado",
    aliases: ["tardigrado", "urso d agua", "urso-d'água", "urso d'água"],
    category: "animals",
    difficulty: "hard",
    hints: [
      "Posso entrar em um estado quase sem atividade metabólica.",
      "Resisto a condições extremas por períodos surpreendentes.",
      "Sou microscópico.",
      "Tenho oito pequenas pernas.",
      "Sou conhecido como urso-d'água ou tardígrado.",
    ],
  },

  // ───────────────────────── NOVOS: Lugares
  {
    id: "place-italy",
    answer: "Itália",
    aliases: ["italia"],
    category: "places",
    difficulty: "easy",
    hints: [
      "Minha história influenciou profundamente arte, religião e política ocidental.",
      "Tenho uma forma geográfica frequentemente comparada a uma peça de roupa.",
      "Pizza e massas são fortemente associadas a mim.",
      "Roma fica em meu território.",
      "Sou o país em formato de bota.",
    ],
  },
  {
    id: "place-england",
    answer: "Inglaterra",
    aliases: ["england"],
    category: "places",
    difficulty: "easy",
    hints: [
      "Sou parte de um país maior formado por quatro nações constituintes.",
      "Minha língua se espalhou mundialmente.",
      "O futebol moderno foi codificado em meu território.",
      "Londres é minha capital.",
      "Sou a Inglaterra.",
    ],
  },
  {
    id: "place-china",
    answer: "China",
    category: "places",
    difficulty: "easy",
    hints: [
      "Minha civilização possui milhares de anos de história registrada.",
      "Tenho uma das maiores populações do planeta.",
      "Uma muralha gigantesca é fortemente associada a mim.",
      "Pequim é minha capital.",
      "Sou a China.",
    ],
  },
  {
    id: "place-canada",
    answer: "Canadá",
    aliases: ["canada"],
    category: "places",
    difficulty: "easy",
    hints: [
      "Tenho uma das maiores áreas territoriais do planeta.",
      "Meu território possui enorme quantidade de lagos.",
      "Uma folha aparece em minha bandeira.",
      "Faço fronteira terrestre com os Estados Unidos.",
      "Ottawa é minha capital.",
    ],
  },
  {
    id: "place-greece",
    answer: "Grécia",
    aliases: ["grecia"],
    category: "places",
    difficulty: "medium",
    hints: [
      "Minha história antiga influenciou filosofia, política e artes do Ocidente.",
      "Sou formado por uma parte continental e muitas ilhas.",
      "Deuses como Zeus e Atena fazem parte de minha mitologia.",
      "Atenas é minha capital.",
      "Sou o país onde nasceram os Jogos Olímpicos antigos.",
    ],
  },
  {
    id: "place-india",
    answer: "Índia",
    aliases: ["india"],
    category: "places",
    difficulty: "medium",
    hints: [
      "Meu território reúne enorme diversidade de línguas e tradições.",
      "Sou um dos países mais populosos do mundo.",
      "Bollywood é uma grande indústria cultural ligada a mim.",
      "O Taj Mahal fica em meu território.",
      "Nova Délhi é minha capital.",
    ],
  },
  {
    id: "place-mexico",
    answer: "México",
    aliases: ["mexico"],
    category: "places",
    difficulty: "medium",
    hints: [
      "Minha história inclui civilizações como maias e astecas.",
      "Tenho forte influência indígena e espanhola.",
      "Sou conhecido por culinária com tortillas e pimentas.",
      "Faço fronteira ao norte com os Estados Unidos.",
      "Cidade do México é minha capital.",
    ],
  },
  {
    id: "place-south-africa",
    answer: "África do Sul",
    aliases: ["africa do sul", "áfrica do sul", "south africa"],
    category: "places",
    difficulty: "medium",
    hints: [
      "Tenho várias línguas oficiais.",
      "Meu território reúne paisagens e ecossistemas muito diferentes.",
      "Nelson Mandela é fortemente ligado à minha história recente.",
      "Fico na extremidade sul do continente africano.",
      "Sou a África do Sul.",
    ],
  },
  {
    id: "place-mongolia",
    answer: "Mongólia",
    aliases: ["mongolia"],
    category: "places",
    difficulty: "hard",
    hints: [
      "Tenho densidade populacional muito baixa.",
      "Grande parte do meu território é formada por estepes.",
      "Minha história está ligada a um dos maiores impérios terrestres da história.",
      "Fico entre Rússia e China.",
      "Ulaanbaatar é minha capital.",
    ],
  },
  {
    id: "place-bhutan",
    answer: "Butão",
    aliases: ["butao", "bhutan"],
    category: "places",
    difficulty: "hard",
    hints: [
      "Sou um pequeno país montanhoso da Ásia.",
      "Minha política ficou famosa por valorizar um indicador de felicidade.",
      "O budismo influencia fortemente minha cultura.",
      "Fico nos Himalaias.",
      "Minha capital é Thimphu.",
    ],
  },
  {
    id: "place-madagascar",
    answer: "Madagascar",
    category: "places",
    difficulty: "hard",
    hints: [
      "Meu isolamento geográfico criou muitas espécies únicas.",
      "Sou uma grande ilha.",
      "Lêmures são fortemente associados a mim.",
      "Fico no oceano Índico, perto da costa africana.",
      "Sou Madagascar.",
    ],
  },
  {
    id: "place-petra",
    answer: "Petra",
    category: "places",
    difficulty: "hard",
    hints: [
      "Fui uma importante cidade em antigas rotas comerciais.",
      "Muitas estruturas minhas foram esculpidas diretamente na rocha.",
      "Fico em uma região desértica.",
      "Minha fachada mais famosa é chamada Al-Khazneh.",
      "Sou a cidade histórica de Petra, na Jordânia.",
    ],
  },

  // ───────────────────────── NOVOS: Comidas
  {
    id: "food-hotdog",
    answer: "Cachorro-quente",
    aliases: ["cachorro quente", "hot dog", "hotdog"],
    category: "food",
    difficulty: "easy",
    hints: [
      "Minha forma moderna está fortemente ligada a comida rápida.",
      "Costumo ser servido em eventos e lanches de rua.",
      "Posso receber muitos acompanhamentos diferentes.",
      "Uma salsicha fica dentro de um pão.",
      "Sou o cachorro-quente.",
    ],
  },
  {
    id: "food-icecream",
    answer: "Sorvete",
    aliases: ["gelado"],
    category: "food",
    difficulty: "easy",
    hints: [
      "Posso existir em dezenas de sabores.",
      "Preciso ser mantido em baixa temperatura.",
      "Posso ser servido em pote ou casquinha.",
      "Derreto quando aqueço.",
      "Sou uma sobremesa congelada.",
    ],
  },
  {
    id: "food-chocolate",
    answer: "Chocolate",
    category: "food",
    difficulty: "easy",
    hints: [
      "Minha matéria-prima vem de uma planta tropical.",
      "Posso ser amargo, ao leite ou branco.",
      "Sou muito usado em doces e sobremesas.",
      "Sou feito a partir do cacau.",
      "Sou chocolate.",
    ],
  },
  {
    id: "food-french-fries",
    answer: "Batata frita",
    aliases: ["batata frita", "fritas", "french fries"],
    category: "food",
    difficulty: "easy",
    hints: [
      "Minha versão mais comum usa um tubérculo.",
      "Sou um acompanhamento frequente de fast-food.",
      "Posso ser cortada em diferentes formatos.",
      "Sou preparada em óleo ou air fryer.",
      "Sou a batata frita.",
    ],
  },
  {
    id: "food-feijoada",
    answer: "Feijoada",
    category: "food",
    difficulty: "medium",
    hints: [
      "Minha história está profundamente ligada à culinária brasileira.",
      "Sou preparada lentamente.",
      "Feijão escuro é meu ingrediente principal em muitas versões.",
      "Carnes variadas costumam acompanhar o feijão.",
      "Sou a feijoada.",
    ],
  },
  {
    id: "food-taco",
    answer: "Taco",
    category: "food",
    difficulty: "medium",
    hints: [
      "Tenho inúmeras variações regionais.",
      "Minha base pode ser feita de milho ou trigo.",
      "Carne, vegetais e molhos podem compor meu recheio.",
      "Sou associado à culinária mexicana.",
      "Sou um taco.",
    ],
  },
  {
    id: "food-pastel",
    answer: "Pastel",
    category: "food",
    difficulty: "medium",
    hints: [
      "Sou muito comum em feiras brasileiras.",
      "Minha massa é fina.",
      "Posso ter recheios salgados ou doces.",
      "Costumo ser frito.",
      "Sou o pastel.",
    ],
  },
  {
    id: "food-pao-de-queijo",
    answer: "Pão de queijo",
    aliases: ["pao de queijo"],
    category: "food",
    difficulty: "medium",
    hints: [
      "Minha textura combina casca mais firme com interior macio.",
      "Minha receita tradicional não depende de farinha de trigo comum.",
      "Polvilho é um ingrediente importante.",
      "Sou muito associado a Minas Gerais.",
      "Sou o pão de queijo.",
    ],
  },
  {
    id: "food-gnocchi",
    answer: "Nhoque",
    aliases: ["gnocchi"],
    category: "food",
    difficulty: "hard",
    hints: [
      "Minha massa pode ser feita de diferentes bases.",
      "Costumo ser servido com molho.",
      "Batata é um ingrediente frequente em minha versão mais conhecida.",
      "Sou uma massa italiana em pequenos pedaços.",
      "Sou chamado de nhoque.",
    ],
  },
  {
    id: "food-ceviche",
    answer: "Ceviche",
    category: "food",
    difficulty: "hard",
    hints: [
      "Meu preparo usa acidez em vez de calor para modificar o ingrediente principal.",
      "Sou muito associado à costa do Pacífico sul-americano.",
      "Cebola e cítricos aparecem com frequência.",
      "Peixe cru marinado é minha base clássica.",
      "Sou o ceviche.",
    ],
  },
  {
    id: "food-falafel",
    answer: "Falafel",
    category: "food",
    difficulty: "hard",
    hints: [
      "Sou comum em várias culinárias do Oriente Médio.",
      "Minha base é vegetal.",
      "Grão-de-bico ou fava podem ser usados.",
      "Costumo ser moldado em bolinhas e frito.",
      "Sou o falafel.",
    ],
  },
  {
    id: "food-baklava",
    answer: "Baklava",
    category: "food",
    difficulty: "hard",
    hints: [
      "Sou uma sobremesa associada a várias culturas do Mediterrâneo oriental e Oriente Médio.",
      "Minha preparação usa muitas camadas finas.",
      "Nozes e calda doce aparecem com frequência.",
      "Massa filo é um ingrediente marcante.",
      "Sou a baklava.",
    ],
  },

  // ───────────────────────── NOVOS: Objetos
  {
    id: "object-television",
    answer: "Televisão",
    aliases: ["tv", "televisao", "televisor"],
    category: "objects",
    difficulty: "easy",
    hints: [
      "Passei por enormes mudanças de tecnologia ao longo das décadas.",
      "Posso receber conteúdo por antena, cabo ou internet.",
      "Normalmente fico em salas ou quartos.",
      "Mostro imagens em movimento e som.",
      "Sou a televisão.",
    ],
  },
  {
    id: "object-glasses",
    answer: "Óculos",
    aliases: ["oculos"],
    category: "objects",
    difficulty: "easy",
    hints: [
      "Posso ser funcional ou apenas estético.",
      "Fico apoiado em três pontos do rosto.",
      "Minhas lentes podem corrigir visão.",
      "Fico diante dos olhos.",
      "Sou um par de óculos.",
    ],
  },
  {
    id: "object-clock",
    answer: "Relógio",
    aliases: ["relogio"],
    category: "objects",
    difficulty: "easy",
    hints: [
      "Posso existir em formatos mecânicos, digitais ou inteligentes.",
      "Meu objetivo principal é medir algo que nunca para.",
      "Posso ficar no pulso ou na parede.",
      "Tenho horas e minutos.",
      "Sou um relógio.",
    ],
  },
  {
    id: "object-chair",
    answer: "Cadeira",
    category: "objects",
    difficulty: "easy",
    hints: [
      "Posso ter designs extremamente simples ou sofisticados.",
      "Normalmente tenho apoio para costas.",
      "Fico presente em casas, escolas e escritórios.",
      "Sirvo para uma pessoa se sentar.",
      "Sou uma cadeira.",
    ],
  },
  {
    id: "object-microwave",
    answer: "Micro-ondas",
    aliases: ["microondas", "micro ondas"],
    category: "objects",
    difficulty: "medium",
    hints: [
      "Meu método de aquecimento não funciona como um forno tradicional.",
      "Posso aquecer alimentos muito rapidamente.",
      "Tenho uma porta com proteção específica.",
      "Uso radiação eletromagnética em uma faixa própria.",
      "Sou o forno de micro-ondas.",
    ],
  },
  {
    id: "object-camera",
    answer: "Câmera",
    aliases: ["camera", "camera fotografica", "câmera fotográfica"],
    category: "objects",
    difficulty: "medium",
    hints: [
      "Meu funcionamento depende de controlar a entrada de luz.",
      "Posso ter lentes intercambiáveis.",
      "Registro imagens.",
      "Tenho sensor ou filme.",
      "Sou uma câmera.",
    ],
  },
  {
    id: "object-vacuum",
    answer: "Aspirador de pó",
    aliases: ["aspirador", "aspirador de po"],
    category: "objects",
    difficulty: "medium",
    hints: [
      "Meu funcionamento cria diferença de pressão para mover sujeira.",
      "Tenho filtros e reservatório ou saco.",
      "Sou usado principalmente em limpeza.",
      "Puxo poeira e pequenos resíduos.",
      "Sou um aspirador de pó.",
    ],
  },
  {
    id: "object-headphones",
    answer: "Fone de ouvido",
    aliases: ["fone", "headphone", "headphones", "fone de ouvido"],
    category: "objects",
    difficulty: "medium",
    hints: [
      "Posso funcionar com ou sem fio.",
      "Fico muito próximo de uma parte sensível do corpo.",
      "Transformo sinais elétricos em som.",
      "Sou usado para ouvir áudio de forma privada.",
      "Sou um fone de ouvido.",
    ],
  },
  {
    id: "object-sextant",
    answer: "Sextante",
    category: "objects",
    difficulty: "hard",
    hints: [
      "Fui extremamente importante antes da navegação eletrônica.",
      "Uso ângulos para determinar posição.",
      "Observo astros e horizonte.",
      "Sou um instrumento de navegação.",
      "Sou chamado de sextante.",
    ],
  },
  {
    id: "object-abacus",
    answer: "Ábaco",
    aliases: ["abaco"],
    category: "objects",
    difficulty: "hard",
    hints: [
      "Sou uma ferramenta de cálculo muito anterior aos computadores.",
      "Uso posições para representar valores.",
      "Tenho contas que deslizam em hastes.",
      "Posso realizar operações matemáticas.",
      "Sou um ábaco.",
    ],
  },
  {
    id: "object-metronome",
    answer: "Metrônomo",
    aliases: ["metronomo"],
    category: "objects",
    difficulty: "hard",
    hints: [
      "Ajudo a manter uma regularidade que pode ser ajustada.",
      "Sou muito usado em estudo musical.",
      "Produzo pulsos em intervalos constantes.",
      "Minha velocidade costuma ser medida em BPM.",
      "Sou um metrônomo.",
    ],
  },
  {
    id: "object-caliper",
    answer: "Paquímetro",
    aliases: ["paquimetro"],
    category: "objects",
    difficulty: "hard",
    hints: [
      "Sou usado quando uma régua comum não oferece precisão suficiente.",
      "Tenho partes que deslizam uma sobre a outra.",
      "Posso medir dimensões internas, externas e profundidade.",
      "Sou uma ferramenta de medição precisa.",
      "Sou chamado de paquímetro.",
    ],
  },

  // ───────────────────────── NOVOS: Geral
  {
    id: "general-fire",
    answer: "Fogo",
    category: "general",
    difficulty: "easy",
    hints: [
      "Sou resultado visível de uma reação química.",
      "Preciso de condições específicas para continuar existindo.",
      "Posso aquecer, iluminar ou destruir.",
      "Produzo calor e luz.",
      "Sou o fogo.",
    ],
  },
  {
    id: "general-snow",
    answer: "Neve",
    category: "general",
    difficulty: "easy",
    hints: [
      "Minha forma depende das condições da atmosfera.",
      "Sou feita da mesma substância que a chuva, mas em outro estado.",
      "Posso cobrir grandes paisagens de branco.",
      "Caio do céu em cristais congelados.",
      "Sou neve.",
    ],
  },
  {
    id: "general-volcano",
    answer: "Vulcão",
    aliases: ["vulcao"],
    category: "general",
    difficulty: "easy",
    hints: [
      "Minha atividade está ligada ao interior do planeta.",
      "Posso permanecer quieto por longos períodos.",
      "Libero gases, cinzas e material derretido.",
      "Posso entrar em erupção.",
      "Sou um vulcão.",
    ],
  },
  {
    id: "general-ocean",
    answer: "Oceano",
    category: "general",
    difficulty: "easy",
    hints: [
      "Cubro a maior parte da superfície do planeta.",
      "Tenho enormes diferenças de profundidade.",
      "Sou formado por água salgada.",
      "Separo e conecto continentes.",
      "Sou um oceano.",
    ],
  },
  {
    id: "general-gravity",
    answer: "Gravidade",
    category: "general",
    difficulty: "medium",
    hints: [
      "Atuo mesmo quando você não percebe.",
      "Minha intensidade depende de massa e distância.",
      "Mantenho planetas em órbita.",
      "Faço objetos caírem em direção ao chão.",
      "Sou a gravidade.",
    ],
  },
  {
    id: "general-electricity",
    answer: "Eletricidade",
    category: "general",
    difficulty: "medium",
    hints: [
      "Posso ser gerada de muitas maneiras diferentes.",
      "Meu uso moderno depende de redes extensas.",
      "Movimento de cargas elétricas está ligado a mim.",
      "Faço funcionar grande parte dos aparelhos modernos.",
      "Sou eletricidade.",
    ],
  },
  {
    id: "general-dna",
    answer: "DNA",
    aliases: ["acido desoxirribonucleico", "ácido desoxirribonucleico"],
    category: "general",
    difficulty: "medium",
    hints: [
      "Minha estrutura permite armazenar informação biológica.",
      "Sou copiado quando células se dividem.",
      "Tenho uma forma famosa de dupla hélice.",
      "Carrego instruções genéticas.",
      "Sou o DNA.",
    ],
  },
  {
    id: "general-black-hole",
    answer: "Buraco Negro",
    aliases: ["buraco negro"],
    category: "general",
    difficulty: "medium",
    hints: [
      "Minha presença pode ser percebida pelo efeito sobre o que está ao redor.",
      "Tenho uma região da qual nem a luz consegue escapar.",
      "Posso se formar após o colapso de estrelas muito massivas.",
      "Minha gravidade é extrema.",
      "Sou um buraco negro.",
    ],
  },
  {
    id: "general-photosynthesis",
    answer: "Fotossíntese",
    aliases: ["fotossintese"],
    category: "general",
    difficulty: "hard",
    hints: [
      "Transformo energia luminosa em energia química.",
      "Aconteço em organismos capazes de produzir seu próprio alimento.",
      "Dióxido de carbono e água participam do processo.",
      "Plantas realizam meu processo usando luz.",
      "Sou a fotossíntese.",
    ],
  },
  {
    id: "general-tectonic-plates",
    answer: "Placas tectônicas",
    aliases: ["placas tectonicas"],
    category: "general",
    difficulty: "hard",
    hints: [
      "Meu movimento é lento, mas muda a superfície do planeta em escala geológica.",
      "Interajo em limites que podem se afastar, colidir ou deslizar.",
      "Terremotos e vulcões estão frequentemente ligados a mim.",
      "Formo grandes blocos da litosfera.",
      "Sou o conjunto de placas tectônicas.",
    ],
  },
  {
    id: "general-quantum",
    answer: "Mecânica Quântica",
    aliases: ["mecanica quantica", "física quântica", "fisica quantica"],
    category: "general",
    difficulty: "hard",
    hints: [
      "Descrevo fenômenos que desafiam a intuição cotidiana.",
      "Probabilidade tem papel fundamental em minhas previsões.",
      "Sou essencial para explicar partículas e átomos.",
      "Trabalho em escalas extremamente pequenas.",
      "Sou a mecânica quântica.",
    ],
  },
  {
    id: "general-supernova",
    answer: "Supernova",
    category: "general",
    difficulty: "hard",
    hints: [
      "Sou um evento que pode liberar enorme quantidade de energia em pouco tempo.",
      "Posso produzir e espalhar elementos pesados pelo espaço.",
      "Estou ligada ao fim de certas estrelas.",
      "Posso brilhar mais que uma galáxia por um período curto.",
      "Sou uma explosão estelar chamada supernova.",
    ],
  },
];
