/**
 * Banco de palavras compartilhado (PT-BR) usado pelo Palavras Cruzadas e pelo
 * Caça-Palavras. Cada entrada tem a palavra em MAIÚSCULAS sem acentos/espaços
 * (para digitação e busca na grade) e uma dica em português para o Palavras
 * Cruzadas (o Caça-Palavras usa só `word`).
 *
 * Para adicionar novas palavras, basta incluir um novo item no array abaixo —
 * nenhum outro arquivo precisa mudar.
 */

export interface WordBankEntry {
  word: string;
  clue: string;
  category: string;
}

export const WORD_BANK: WordBankEntry[] = [
  { word: "GATO", clue: "Animal doméstico que mia", category: "animais" },
  { word: "CACHORRO", clue: "Melhor amigo do homem", category: "animais" },
  { word: "LEAO", clue: "Rei da selva", category: "animais" },
  { word: "TIGRE", clue: "Felino listrado da Ásia", category: "animais" },
  { word: "ELEFANTE", clue: "Mamífero com tromba", category: "animais" },
  { word: "GIRAFA", clue: "Animal de pescoço longo", category: "animais" },
  { word: "MACACO", clue: "Primata que gosta de bananas", category: "animais" },
  { word: "COELHO", clue: "Animal de orelhas compridas que pula", category: "animais" },
  { word: "CAVALO", clue: "Animal usado para montaria", category: "animais" },
  { word: "GALINHA", clue: "Ave que põe ovos", category: "animais" },
  { word: "PATO", clue: "Ave aquática que faz quá-quá", category: "animais" },
  { word: "URSO", clue: "Animal grande que hiberna", category: "animais" },
  { word: "LOBO", clue: "Animal selvagem que uiva", category: "animais" },
  { word: "RAPOSA", clue: "Animal astuto de cauda peluda", category: "animais" },
  { word: "TARTARUGA", clue: "Animal de casco lento", category: "animais" },
  { word: "BORBOLETA", clue: "Inseto colorido que sai do casulo", category: "animais" },
  { word: "ABELHA", clue: "Inseto que produz mel", category: "animais" },
  { word: "ARANHA", clue: "Animal de oito patas que tece teia", category: "animais" },
  { word: "PEIXE", clue: "Animal que vive na água e tem guelras", category: "animais" },
  { word: "GOLFINHO", clue: "Mamífero marinho muito inteligente", category: "animais" },
  { word: "TUBARAO", clue: "Predador temido dos oceanos", category: "animais" },
  { word: "COBRA", clue: "Réptil sem pernas", category: "animais" },
  { word: "JACARE", clue: "Réptil de rios que tem muitos dentes", category: "animais" },
  { word: "PINGUIM", clue: "Ave que não voa e vive no gelo", category: "animais" },
  { word: "CORUJA", clue: "Ave de rapina que enxerga à noite", category: "animais" },
  { word: "ZEBRA", clue: "Animal africano com listras", category: "animais" },
  { word: "CANGURU", clue: "Animal australiano que carrega filhote na bolsa", category: "animais" },
  { word: "FORMIGA", clue: "Inseto que vive em colônias organizadas", category: "animais" },
  { word: "ARVORE", clue: "Planta de tronco e copa", category: "natureza" },
  { word: "FLOR", clue: "Parte colorida e perfumada da planta", category: "natureza" },
  { word: "RIO", clue: "Curso de água que deságua no mar", category: "natureza" },
  { word: "MONTANHA", clue: "Grande elevação de terreno", category: "natureza" },
  { word: "OCEANO", clue: "Grande massa de água salgada", category: "natureza" },
  { word: "FLORESTA", clue: "Área com muitas árvores", category: "natureza" },
  { word: "DESERTO", clue: "Região seca e arenosa", category: "natureza" },
  { word: "VULCAO", clue: "Montanha que pode expelir lava", category: "natureza" },
  { word: "CACHOEIRA", clue: "Queda d'água natural", category: "natureza" },
  { word: "PRAIA", clue: "Faixa de areia à beira-mar", category: "natureza" },
  { word: "ILHA", clue: "Terra cercada de água por todos os lados", category: "natureza" },
  { word: "NUVEM", clue: "Massa de vapor no céu", category: "natureza" },
  { word: "CHUVA", clue: "Água que cai do céu", category: "natureza" },
  { word: "NEVE", clue: "Precipitação branca e gelada", category: "natureza" },
  { word: "VENTO", clue: "Ar em movimento", category: "natureza" },
  { word: "SOL", clue: "Astro que ilumina a Terra de dia", category: "natureza" },
  { word: "LUA", clue: "Satélite natural da Terra", category: "natureza" },
  { word: "ESTRELA", clue: "Ponto luminoso visível no céu à noite", category: "natureza" },
  { word: "PEDRA", clue: "Fragmento sólido e duro da natureza", category: "natureza" },
  { word: "AREIA", clue: "Material fino encontrado na praia", category: "natureza" },
  { word: "MESA", clue: "Móvel onde se faz as refeições", category: "casa" },
  { word: "CADEIRA", clue: "Móvel usado para sentar", category: "casa" },
  { word: "SOFA", clue: "Móvel estofado da sala", category: "casa" },
  { word: "CAMA", clue: "Móvel usado para dormir", category: "casa" },
  { word: "JANELA", clue: "Abertura da parede com vidro", category: "casa" },
  { word: "PORTA", clue: "Estrutura usada para entrar e sair", category: "casa" },
  { word: "TELHADO", clue: "Cobertura da casa", category: "casa" },
  { word: "PAREDE", clue: "Estrutura vertical que separa cômodos", category: "casa" },
  { word: "COZINHA", clue: "Cômodo onde se prepara comida", category: "casa" },
  { word: "BANHEIRO", clue: "Cômodo com chuveiro e vaso sanitário", category: "casa" },
  { word: "ESPELHO", clue: "Objeto que reflete a imagem", category: "casa" },
  { word: "CHAVE", clue: "Objeto que abre fechaduras", category: "casa" },
  { word: "LAMPADA", clue: "Objeto que ilumina os cômodos", category: "casa" },
  { word: "GELADEIRA", clue: "Eletrodoméstico que mantém alimentos frios", category: "casa" },
  { word: "TRAVESSEIRO", clue: "Usado para apoiar a cabeça ao dormir", category: "casa" },
  { word: "COBERTOR", clue: "Usado para se aquecer na cama", category: "casa" },
  { word: "VASO", clue: "Recipiente usado para plantas", category: "casa" },
  { word: "TAPETE", clue: "Peça de tecido colocada no chão", category: "casa" },
  { word: "ARROZ", clue: "Cereal branco muito consumido no Brasil", category: "comida" },
  { word: "FEIJAO", clue: "Combina com arroz no prato brasileiro", category: "comida" },
  { word: "PAO", clue: "Feito de farinha, comum no café da manhã", category: "comida" },
  { word: "QUEIJO", clue: "Derivado do leite", category: "comida" },
  { word: "LEITE", clue: "Bebida branca tirada da vaca", category: "comida" },
  { word: "OVO", clue: "Alimento posto pelas galinhas", category: "comida" },
  { word: "BANANA", clue: "Fruta amarela e curva", category: "comida" },
  { word: "MACA", clue: "Fruta vermelha ou verde, crocante", category: "comida" },
  { word: "LARANJA", clue: "Fruta cítrica usada em sucos", category: "comida" },
  { word: "ABACAXI", clue: "Fruta tropical com casca espinhosa", category: "comida" },
  { word: "MANGA", clue: "Fruta doce e suculenta de caroço grande", category: "comida" },
  { word: "MORANGO", clue: "Fruta vermelha pequena e doce", category: "comida" },
  { word: "UVA", clue: "Fruta usada para fazer vinho", category: "comida" },
  { word: "MELANCIA", clue: "Fruta grande, verde por fora e vermelha por dentro", category: "comida" },
  { word: "CHOCOLATE", clue: "Doce feito de cacau", category: "comida" },
  { word: "BOLO", clue: "Doce assado, comum em aniversários", category: "comida" },
  { word: "SORVETE", clue: "Sobremesa gelada e doce", category: "comida" },
  { word: "PIZZA", clue: "Prato italiano redondo com cobertura", category: "comida" },
  { word: "MACARRAO", clue: "Massa comum em pratos italianos", category: "comida" },
  { word: "CAFE", clue: "Bebida quente e escura, muito estimulante", category: "comida" },
  { word: "AGUA", clue: "Líquido essencial à vida", category: "comida" },
  { word: "SAL", clue: "Tempero branco e granulado", category: "comida" },
  { word: "ACUCAR", clue: "Tempero doce e granulado", category: "comida" },
  { word: "MEL", clue: "Substância doce produzida pelas abelhas", category: "comida" },
  { word: "CABECA", clue: "Parte superior do corpo", category: "corpo" },
  { word: "OLHO", clue: "Órgão da visão", category: "corpo" },
  { word: "NARIZ", clue: "Órgão do olfato", category: "corpo" },
  { word: "BOCA", clue: "Órgão usado para comer e falar", category: "corpo" },
  { word: "ORELHA", clue: "Órgão da audição", category: "corpo" },
  { word: "MAO", clue: "Parte do corpo com dedos usada para pegar", category: "corpo" },
  { word: "BRACO", clue: "Membro superior do corpo", category: "corpo" },
  { word: "PERNA", clue: "Membro inferior do corpo", category: "corpo" },
  { word: "CORACAO", clue: "Órgão que bombeia o sangue", category: "corpo" },
  { word: "CABELO", clue: "Cresce na cabeça", category: "corpo" },
  { word: "DENTE", clue: "Usado para mastigar", category: "corpo" },
  { word: "MEDICO", clue: "Profissional que cuida da saúde", category: "profissoes" },
  { word: "PROFESSOR", clue: "Profissional que ensina", category: "profissoes" },
  { word: "ENGENHEIRO", clue: "Profissional que projeta construções e sistemas", category: "profissoes" },
  { word: "ADVOGADO", clue: "Profissional que atua na área jurídica", category: "profissoes" },
  { word: "DENTISTA", clue: "Cuida da saúde dos dentes", category: "profissoes" },
  { word: "COZINHEIRO", clue: "Prepara refeições profissionalmente", category: "profissoes" },
  { word: "BOMBEIRO", clue: "Profissional que apaga incêndios", category: "profissoes" },
  { word: "POLICIAL", clue: "Profissional que garante a segurança pública", category: "profissoes" },
  { word: "PINTOR", clue: "Profissional que pinta quadros ou paredes", category: "profissoes" },
  { word: "MOTORISTA", clue: "Profissional que dirige veículos", category: "profissoes" },
  { word: "ENFERMEIRO", clue: "Auxilia médicos e cuida de pacientes", category: "profissoes" },
  { word: "PILOTO", clue: "Profissional que conduz aviões", category: "profissoes" },
  { word: "ATOR", clue: "Profissional que interpreta personagens", category: "profissoes" },
  { word: "CANTOR", clue: "Profissional que canta músicas", category: "profissoes" },
  { word: "JORNALISTA", clue: "Profissional que produz notícias", category: "profissoes" },
  { word: "COMPUTADOR", clue: "Máquina usada para processar dados", category: "tecnologia" },
  { word: "CELULAR", clue: "Telefone portátil", category: "tecnologia" },
  { word: "INTERNET", clue: "Rede mundial de computadores", category: "tecnologia" },
  { word: "TECLADO", clue: "Usado para digitar no computador", category: "tecnologia" },
  { word: "MOUSE", clue: "Periférico usado para clicar na tela", category: "tecnologia" },
  { word: "TELA", clue: "Onde as imagens do computador aparecem", category: "tecnologia" },
  { word: "IMPRESSORA", clue: "Equipamento que imprime documentos", category: "tecnologia" },
  { word: "CAMERA", clue: "Equipamento usado para tirar fotos", category: "tecnologia" },
  { word: "ROBO", clue: "Máquina automatizada que imita ações humanas", category: "tecnologia" },
  { word: "SENHA", clue: "Código secreto para acessar uma conta", category: "tecnologia" },
  { word: "BRASIL", clue: "País onde se fala português na América do Sul", category: "geografia" },
  { word: "CIDADE", clue: "Área urbana onde as pessoas vivem", category: "geografia" },
  { word: "PAIS", clue: "Território com governo próprio", category: "geografia" },
  { word: "CAPITAL", clue: "Principal cidade de um estado ou país", category: "geografia" },
  { word: "CONTINENTE", clue: "Grande extensão de terra, como a América", category: "geografia" },
  { word: "MAPA", clue: "Representação gráfica de um território", category: "geografia" },
  { word: "PONTE", clue: "Construção que liga duas margens", category: "geografia" },
  { word: "ESTRADA", clue: "Via usada para viajar de carro", category: "geografia" },
  { word: "AZUL", clue: "Cor do céu em dia claro", category: "cores" },
  { word: "VERMELHO", clue: "Cor do morango maduro", category: "cores" },
  { word: "AMARELO", clue: "Cor do sol e da banana", category: "cores" },
  { word: "VERDE", clue: "Cor das folhas", category: "cores" },
  { word: "ROSA", clue: "Cor associada ao romantismo", category: "cores" },
  { word: "PRETO", clue: "Cor da noite escura", category: "cores" },
  { word: "BRANCO", clue: "Cor da neve", category: "cores" },
  { word: "ROXO", clue: "Cor obtida misturando azul e vermelho", category: "cores" },
  { word: "FUTEBOL", clue: "Esporte mais popular do Brasil", category: "esportes" },
  { word: "VOLEI", clue: "Esporte jogado com uma rede e uma bola", category: "esportes" },
  { word: "BASQUETE", clue: "Esporte com cestas e bola laranja", category: "esportes" },
  { word: "NATACAO", clue: "Esporte praticado na piscina", category: "esportes" },
  { word: "TENIS", clue: "Esporte jogado com raquete", category: "esportes" },
  { word: "CORRIDA", clue: "Prova de velocidade a pé", category: "esportes" },
  { word: "CICLISMO", clue: "Esporte praticado com bicicleta", category: "esportes" },
  { word: "SURFE", clue: "Esporte praticado sobre as ondas", category: "esportes" },
  { word: "CARRO", clue: "Veículo de quatro rodas usado no dia a dia", category: "transporte" },
  { word: "ONIBUS", clue: "Transporte coletivo urbano", category: "transporte" },
  { word: "BICICLETA", clue: "Veículo de duas rodas movido a pedal", category: "transporte" },
  { word: "AVIAO", clue: "Veículo que voa e transporta passageiros", category: "transporte" },
  { word: "TREM", clue: "Veículo que anda sobre trilhos", category: "transporte" },
  { word: "BARCO", clue: "Veículo usado para navegar", category: "transporte" },
  { word: "MOTO", clue: "Veículo de duas rodas com motor", category: "transporte" },
  { word: "METRO", clue: "Transporte subterrâneo das grandes cidades", category: "transporte" },
  { word: "VIOLAO", clue: "Instrumento de cordas dedilhado", category: "musica" },
  { word: "PIANO", clue: "Instrumento de teclas", category: "musica" },
  { word: "BATERIA", clue: "Instrumento de percussão com pratos e tambores", category: "musica" },
  { word: "FLAUTA", clue: "Instrumento de sopro fino e longo", category: "musica" },
  { word: "GUITARRA", clue: "Instrumento de cordas elétrico", category: "musica" },
  { word: "MUSICA", clue: "Arte de combinar sons", category: "musica" },
  { word: "CANCAO", clue: "Composição musical cantada", category: "musica" },
  { word: "VERAO", clue: "Estação mais quente do ano", category: "tempo" },
  { word: "INVERNO", clue: "Estação mais fria do ano", category: "tempo" },
  { word: "OUTONO", clue: "Estação em que as folhas caem", category: "tempo" },
  { word: "PRIMAVERA", clue: "Estação das flores", category: "tempo" },
  { word: "SEMANA", clue: "Período de sete dias", category: "tempo" },
  { word: "MES", clue: "Período de cerca de trinta dias", category: "tempo" },
  { word: "ANO", clue: "Período de doze meses", category: "tempo" },
  { word: "LIVRO", clue: "Objeto usado para leitura", category: "objetos" },
  { word: "CANETA", clue: "Objeto usado para escrever com tinta", category: "objetos" },
  { word: "LAPIS", clue: "Objeto usado para escrever ou desenhar", category: "objetos" },
  { word: "RELOGIO", clue: "Objeto usado para ver as horas", category: "objetos" },
  { word: "BOLSA", clue: "Objeto usado para carregar pertences", category: "objetos" },
  { word: "OCULOS", clue: "Objeto usado para melhorar a visão", category: "objetos" },
  { word: "GUARDACHUVA", clue: "Objeto usado para proteger da chuva", category: "objetos" },
  { word: "TESOURA", clue: "Objeto usado para cortar papel ou tecido", category: "objetos" },
  { word: "AGULHA", clue: "Objeto fino usado para costurar", category: "objetos" },
  { word: "ESPADA", clue: "Arma antiga de lâmina longa", category: "objetos" },
  { word: "BOLA", clue: "Objeto redondo usado em muitos esportes", category: "objetos" },
  { word: "PIPA", clue: "Brinquedo que voa preso a uma linha", category: "objetos" },
  { word: "BONECA", clue: "Brinquedo em forma de pessoa", category: "objetos" },
  { word: "QUEBRACABECA", clue: "Jogo de montar peças que formam uma imagem", category: "objetos" },
  { word: "ORNITORRINCO", clue: "Mamífero australiano que põe ovos e possui bico", category: "animais" },
  { word: "CAMALEAO", clue: "Réptil conhecido pela capacidade de mudar de cor", category: "animais" },
  { word: "HIPOPOTAMO", clue: "Grande mamífero africano que passa muito tempo na água", category: "animais" },
  { word: "RINOCERONTE", clue: "Grande mamífero herbívoro com um ou dois chifres", category: "animais" },
  { word: "CHIMPANZE", clue: "Primata considerado um dos parentes vivos mais próximos do ser humano", category: "animais" },
  { word: "ORANGOTANGO", clue: "Grande primata de pelos alaranjados encontrado na Ásia", category: "animais" },
  { word: "ESCORPIAO", clue: "Aracnídeo que possui ferrão na extremidade da cauda", category: "animais" },
  { word: "CARANGUEJO", clue: "Crustáceo com carapaça e grandes pinças", category: "animais" },
  { word: "LAGARTIXA", clue: "Pequeno réptil frequentemente encontrado em paredes e casas", category: "animais" },
  { word: "SALAMANDRA", clue: "Anfíbio de corpo alongado e cauda geralmente bem desenvolvida", category: "animais" },
  { word: "TAMANDUA", clue: "Mamífero sul-americano especializado em comer formigas e cupins", category: "animais" },
  { word: "CAPIVARA", clue: "Maior roedor do mundo, comum em áreas próximas à água", category: "animais" },
  { word: "JAGUATIRICA", clue: "Felino selvagem de pequeno porte encontrado nas Américas", category: "animais" },
  { word: "PREGUICA", clue: "Mamífero arborícola conhecido por seus movimentos lentos", category: "animais" },
  { word: "BICHO-PREGUICA", clue: "Mamífero que passa grande parte do tempo pendurado em árvores", category: "animais" },
  { word: "ECOSSISTEMA", clue: "Conjunto formado pelos seres vivos e pelo ambiente onde vivem", category: "natureza" },
  { word: "BIODIVERSIDADE", clue: "Variedade de seres vivos existente em determinada região ou no planeta", category: "natureza" },
  { word: "FOTOSSINTESE", clue: "Processo pelo qual plantas produzem matéria orgânica usando luz", category: "natureza" },
  { word: "EVAPORACAO", clue: "Processo em que um líquido passa para o estado gasoso", category: "natureza" },
  { word: "CONDENSACAO", clue: "Processo em que um gás passa para o estado líquido", category: "natureza" },
  { word: "PRECIPITACAO", clue: "Queda de água da atmosfera na forma de chuva, neve ou granizo", category: "natureza" },
  { word: "ATMOSFERA", clue: "Camada de gases que envolve um planeta", category: "natureza" },
  { word: "HORIZONTE", clue: "Linha aparente onde o céu parece encontrar a superfície", category: "natureza" },
  { word: "ARCOIRIS", clue: "Fenômeno óptico colorido que pode surgir após a chuva", category: "natureza" },
  { word: "GELEIRA", clue: "Grande massa de gelo formada pelo acúmulo e compactação de neve", category: "natureza" },
  { word: "ESTALACTITE", clue: "Formação mineral que cresce no teto de cavernas", category: "natureza" },
  { word: "ESTALAGMITE", clue: "Formação mineral que cresce no chão de cavernas", category: "natureza" },
  { word: "GRAVIDADE", clue: "Força que atrai corpos com massa uns em direção aos outros", category: "ciencia" },
  { word: "ELETRON", clue: "Partícula subatômica de carga elétrica negativa", category: "ciencia" },
  { word: "PROTON", clue: "Partícula subatômica de carga elétrica positiva encontrada no núcleo", category: "ciencia" },
  { word: "NEUTRON", clue: "Partícula subatômica sem carga elétrica encontrada no núcleo", category: "ciencia" },
  { word: "ATOMO", clue: "Unidade básica da matéria que conserva as propriedades de um elemento", category: "ciencia" },
  { word: "MOLECULA", clue: "Conjunto de dois ou mais átomos ligados quimicamente", category: "ciencia" },
  { word: "CROMOSSOMO", clue: "Estrutura que contém material genético dentro das células", category: "ciencia" },
  { word: "MITOCONDRIA", clue: "Estrutura celular responsável por grande parte da produção de energia", category: "ciencia" },
  { word: "GRAVITACAO", clue: "Fenômeno de atração entre corpos que possuem massa", category: "ciencia" },
  { word: "ASTRONOMIA", clue: "Ciência que estuda os astros e os fenômenos do universo", category: "ciencia" },
  { word: "BIOLOGIA", clue: "Ciência que estuda os seres vivos", category: "ciencia" },
  { word: "QUIMICA", clue: "Ciência que estuda a matéria, suas propriedades e transformações", category: "ciencia" },
  { word: "FISICA", clue: "Ciência que estuda a matéria, energia, movimento e suas interações", category: "ciencia" },
  { word: "GENETICA", clue: "Área da biologia que estuda a hereditariedade", category: "ciencia" },
  { word: "EVOLUCAO", clue: "Processo de mudança das características das espécies ao longo das gerações", category: "ciencia" },
  { word: "ARQUIPÉLAGO", clue: "Conjunto de ilhas próximas umas das outras", category: "geografia" },
  { word: "PENINSULA", clue: "Porção de terra cercada de água em quase todos os lados", category: "geografia" },
  { word: "CORDILHEIRA", clue: "Grande conjunto ou cadeia de montanhas", category: "geografia" },
  { word: "MERIDIANO", clue: "Linha imaginária que liga os polos da Terra", category: "geografia" },
  { word: "PARALELO", clue: "Linha imaginária traçada paralelamente ao Equador", category: "geografia" },
  { word: "EQUADOR", clue: "Linha imaginária que divide a Terra nos hemisférios Norte e Sul", category: "geografia" },
  { word: "LATITUDE", clue: "Distância angular de um ponto em relação ao Equador", category: "geografia" },
  { word: "LONGITUDE", clue: "Distância angular de um ponto em relação ao meridiano de Greenwich", category: "geografia" },
  { word: "ARIDEZ", clue: "Característica de uma região com pouca disponibilidade de água", category: "geografia" },
  { word: "PLANALTO", clue: "Forma de relevo geralmente elevada e relativamente plana", category: "geografia" },
  { word: "PLANICIE", clue: "Área de relevo predominantemente plano e pouco elevado", category: "geografia" },
  { word: "DEPRESSAO", clue: "Área do relevo mais baixa que as regiões ao seu redor", category: "geografia" },
  { word: "ESTUARIO", clue: "Área onde um rio encontra o mar, geralmente com mistura de águas", category: "geografia" },
  { word: "NASCENTE", clue: "Local onde um rio começa", category: "geografia" },
  { word: "AFLUENTE", clue: "Rio ou curso de água que deságua em outro rio", category: "geografia" },
  { word: "RENASCIMENTO", clue: "Movimento cultural europeu associado à valorização da arte e da cultura clássica", category: "historia" },
  { word: "FEUDALISMO", clue: "Sistema social e econômico predominante na Europa medieval", category: "historia" },
  { word: "ABSOLUTISMO", clue: "Sistema político em que o monarca concentra grande parte do poder", category: "historia" },
  { word: "REVOLUCAO", clue: "Transformação política ou social profunda e geralmente rápida", category: "historia" },
  { word: "COLONIZACAO", clue: "Processo de ocupação e controle de um território por outro povo ou país", category: "historia" },
  { word: "INDEPENDENCIA", clue: "Condição de um território que deixa de estar subordinado a outro Estado", category: "historia" },
  { word: "MONARQUIA", clue: "Forma de governo em que o chefe de Estado é um monarca", category: "historia" },
  { word: "DEMOCRACIA", clue: "Sistema político baseado na participação dos cidadãos nas decisões públicas", category: "historia" },
  { word: "IMPERIO", clue: "Grande Estado formado por diferentes territórios sob um poder central", category: "historia" },
  { word: "ARQUEOLOGIA", clue: "Ciência que estuda sociedades antigas por meio de vestígios materiais", category: "historia" },
  { word: "ANTIGUIDADE", clue: "Período histórico associado às primeiras grandes civilizações", category: "historia" },
  { word: "PREHISTORIA", clue: "Período anterior ao surgimento da escrita", category: "historia" },
  { word: "ALGORITMO", clue: "Sequência de instruções usada para resolver um problema ou realizar uma tarefa", category: "tecnologia" },
  { word: "PROGRAMACAO", clue: "Processo de criação de instruções para computadores", category: "tecnologia" },
  { word: "INTELIGENCIA", clue: "Capacidade de aprender, compreender e resolver problemas", category: "tecnologia" },
  { word: "CRIPTOGRAFIA", clue: "Técnica utilizada para proteger informações por meio de codificação", category: "tecnologia" },
  { word: "PROCESSADOR", clue: "Componente responsável por executar instruções em um computador", category: "tecnologia" },
  { word: "MEMORIA", clue: "Componente usado para armazenar temporariamente dados e instruções", category: "tecnologia" },
  { word: "SERVIDOR", clue: "Computador ou sistema que fornece serviços ou recursos para outros dispositivos", category: "tecnologia" },
  { word: "BANCODEDADOS", clue: "Sistema organizado para armazenar e consultar informações", category: "tecnologia" },
  { word: "SOFTWARE", clue: "Conjunto de programas e instruções executados por um dispositivo", category: "tecnologia" },
  { word: "HARDWARE", clue: "Parte física de um computador ou dispositivo eletrônico", category: "tecnologia" },
  { word: "INTERFACE", clue: "Meio pelo qual uma pessoa interage com um sistema", category: "tecnologia" },
  { word: "AUTOMACAO", clue: "Uso de tecnologia para realizar tarefas com pouca intervenção humana", category: "tecnologia" },
  { word: "METAFORA", clue: "Figura de linguagem que estabelece uma comparação implícita", category: "linguagem" },
  { word: "IRONIA", clue: "Figura de linguagem em que se expressa algo sugerindo sentido diferente", category: "linguagem" },
  { word: "HIPERBOLE", clue: "Figura de linguagem que utiliza exagero para enfatizar uma ideia", category: "linguagem" },
  { word: "ONOMATOPEIA", clue: "Palavra que procura representar um som ou ruído", category: "linguagem" },
  { word: "ANTITESE", clue: "Figura de linguagem que aproxima ideias de sentidos opostos", category: "linguagem" },
  { word: "PARADOXO", clue: "Ideia ou afirmação que parece contraditória, mas pode conter uma verdade", category: "linguagem" },
  { word: "SINONIMO", clue: "Palavra que apresenta significado semelhante ao de outra", category: "linguagem" },
  { word: "ANTONIMO", clue: "Palavra que apresenta significado contrário ao de outra", category: "linguagem" },
  { word: "SUBSTANTIVO", clue: "Classe de palavras usada para nomear seres, objetos, lugares ou conceitos", category: "linguagem" },
  { word: "ADJETIVO", clue: "Classe de palavras que caracteriza ou qualifica um substantivo", category: "linguagem" },
  { word: "VERBO", clue: "Classe de palavras que geralmente indica ação, estado ou fenômeno", category: "linguagem" },
  { word: "FILOSOFIA", clue: "Busca racional pelo conhecimento e pela compreensão de questões fundamentais", category: "filosofia" },
  { word: "ETICA", clue: "Área da filosofia que estuda princípios relacionados ao certo e ao errado", category: "filosofia" },
  { word: "MORAL", clue: "Conjunto de princípios e valores que orientam comportamentos", category: "filosofia" },
  { word: "LOGICA", clue: "Área que estuda princípios do raciocínio válido", category: "filosofia" },
  { word: "EPISTEMOLOGIA", clue: "Área da filosofia dedicada ao estudo do conhecimento", category: "filosofia" },
  { word: "EXISTENCIALISMO", clue: "Corrente filosófica que enfatiza liberdade, escolha e existência humana", category: "filosofia" },
  { word: "EMPIRISMO", clue: "Corrente filosófica que destaca a experiência como fonte do conhecimento", category: "filosofia" },
  { word: "RACIONALISMO", clue: "Corrente filosófica que atribui grande importância à razão", category: "filosofia" },
  { word: "CEREBELO", clue: "Parte do encéfalo relacionada à coordenação dos movimentos e ao equilíbrio", category: "corpo" },
  { word: "CEREBRO", clue: "Principal parte do encéfalo, responsável por diversas funções cognitivas", category: "corpo" },
  { word: "PULMAO", clue: "Órgão responsável pelas trocas gasosas da respiração", category: "corpo" },
  { word: "ESTOMAGO", clue: "Órgão do sistema digestório que participa da digestão dos alimentos", category: "corpo" },
  { word: "INTESTINO", clue: "Órgão do sistema digestório responsável pela absorção de nutrientes e água", category: "corpo" },
  { word: "PANCREAS", clue: "Órgão que produz substâncias importantes para a digestão e hormônios", category: "corpo" },
  { word: "FIGADO", clue: "Órgão que desempenha diversas funções metabólicas e produz a bile", category: "corpo" },
  { word: "ESOFAGO", clue: "Tubo que conduz o alimento da boca até o estômago", category: "corpo" },
  { word: "DIAFRAGMA", clue: "Músculo que participa dos movimentos respiratórios", category: "corpo" },
  { word: "ARTERIA", clue: "Vaso sanguíneo que geralmente leva sangue para fora do coração", category: "corpo" },
  { word: "VEIA", clue: "Vaso sanguíneo que geralmente conduz sangue em direção ao coração", category: "corpo" },
  { word: "ATLETISMO", clue: "Conjunto de modalidades que inclui corridas, saltos e lançamentos", category: "esportes" },
  { word: "GINASTICA", clue: "Esporte que envolve movimentos de força, flexibilidade, equilíbrio e coordenação", category: "esportes" },
  { word: "ESGRIMA", clue: "Esporte de combate praticado com armas brancas específicas", category: "esportes" },
  { word: "ALPINISMO", clue: "Prática esportiva de escalada e ascensão de montanhas", category: "esportes" },
  { word: "MOTOCICLISMO", clue: "Modalidade esportiva que envolve competições com motocicletas", category: "esportes" },
  { word: "PARAQUEDISMO", clue: "Esporte praticado com saltos utilizando um paraquedas", category: "esportes" },
  { word: "TRIATLO", clue: "Competição que combina natação, ciclismo e corrida", category: "esportes" },
  { word: "GUACAMOLE", clue: "Preparação mexicana feita principalmente com abacate", category: "comida" },
  { word: "RATATOUILLE", clue: "Prato francês preparado com diversos vegetais", category: "comida" },
  { word: "ESPAGUETE", clue: "Tipo de massa italiana longa e fina", category: "comida" },
  { word: "PARMEZAO", clue: "Queijo duro de sabor intenso, usado frequentemente ralado", category: "comida" },
  { word: "GORGONZOLA", clue: "Queijo italiano conhecido por suas veias azuladas", category: "comida" },
  { word: "MOZZARELLA", clue: "Queijo italiano de textura macia, muito usado em pizzas", category: "comida" },
  { word: "BRIGADEIRO", clue: "Doce brasileiro feito tradicionalmente com leite condensado e chocolate", category: "comida" },
  { word: "FEIJOADA", clue: "Prato brasileiro preparado tradicionalmente com feijão preto e carnes", category: "comida" },
  { word: "ACARAJE", clue: "Comida baiana feita com massa de feijão-fradinho frita no azeite de dendê", category: "comida" },
  { word: "VATAPA", clue: "Prato de origem afro-brasileira muito associado à culinária baiana", category: "comida" },
  { word: "MOQUECA", clue: "Prato brasileiro preparado tradicionalmente com peixe ou frutos do mar", category: "comida" },
  { word: "AMPULHETA", clue: "Objeto que mede um intervalo de tempo usando areia", category: "objetos" },
  { word: "BINOCULO", clue: "Instrumento óptico usado para observar objetos distantes", category: "objetos" },
  { word: "TELESCOPIO", clue: "Instrumento óptico utilizado para observar objetos distantes no céu", category: "objetos" },
  { word: "MICROSCOPIO", clue: "Instrumento usado para observar estruturas muito pequenas", category: "objetos" },
  { word: "TERMOMETRO", clue: "Instrumento usado para medir temperatura", category: "objetos" },
  { word: "BAROMETRO", clue: "Instrumento utilizado para medir a pressão atmosférica", category: "objetos" },
  { word: "COMPASSO", clue: "Instrumento utilizado para traçar círculos e medir distâncias em desenhos", category: "objetos" },
  { word: "ESQUADRO", clue: "Instrumento usado para traçar e verificar ângulos, especialmente retos", category: "objetos" },
  { word: "PARAFUSO", clue: "Peça metálica rosqueada usada para fixação", category: "objetos" },
  { word: "ENGRENAGEM", clue: "Peça dentada usada para transmitir movimento entre mecanismos", category: "objetos" },
  { word: "ALICATE", clue: "Ferramenta usada para segurar, dobrar ou cortar determinados materiais", category: "objetos" },
  { word: "CHAVEIRO", clue: "Objeto usado para reunir e transportar chaves", category: "objetos" },
  { word: "PANTERA", clue: "Felino de pelagem escura conhecido por sua agilidade", category: "animais" },
  { word: "ONCA", clue: "Grande felino americano de pelagem com manchas", category: "animais" },
  { word: "LEOPARDO", clue: "Grande felino ágil com pelagem coberta por manchas", category: "animais" },
  { word: "HIENA", clue: "Mamífero africano conhecido por vocalizações que lembram risadas", category: "animais" },
  { word: "BUFALO", clue: "Grande mamífero herbívoro de corpo robusto e chifres", category: "animais" },
  { word: "BISAO", clue: "Grande mamífero de pelagem espessa encontrado em regiões frias", category: "animais" },
  { word: "ALCE", clue: "Grande cervídeo de longas pernas e grandes galhadas", category: "animais" },
  { word: "CERVO", clue: "Mamífero herbívoro cujos machos geralmente possuem galhadas", category: "animais" },
  { word: "VEADO", clue: "Mamífero herbívoro ágil, parente do cervo", category: "animais" },
  { word: "ANTA", clue: "Grande mamífero herbívoro de focinho curto e flexível", category: "animais" },
  { word: "TATU", clue: "Mamífero protegido por placas duras que formam uma carapaça", category: "animais" },
  { word: "LONTRA", clue: "Mamífero semiaquático ágil e excelente nadador", category: "animais" },
  { word: "FOCA", clue: "Mamífero marinho de corpo adaptado à natação", category: "animais" },
  { word: "MORSA", clue: "Mamífero marinho de grandes presas e bigodes", category: "animais" },
  { word: "BALEIA", clue: "Grande mamífero marinho que respira por pulmões", category: "animais" },
  { word: "POLVO", clue: "Molusco marinho com oito braços", category: "animais" },
  { word: "LULA", clue: "Molusco marinho de corpo alongado e tentáculos", category: "animais" },
  { word: "AGUIA", clue: "Ave de rapina conhecida por sua excelente visão", category: "animais" },
  { word: "FALCAO", clue: "Ave de rapina muito veloz durante o voo", category: "animais" },
  { word: "PAPAGAIO", clue: "Ave colorida conhecida por imitar sons e palavras", category: "animais" },
  { word: "TUCANO", clue: "Ave tropical de bico grande e colorido", category: "animais" },
  { word: "AVESTRUZ", clue: "Maior ave existente, incapaz de voar", category: "animais" },
  { word: "FLAMINGO", clue: "Ave de pernas longas e plumagem geralmente rosada", category: "animais" },
  { word: "SAPO", clue: "Anfíbio terrestre de pele geralmente áspera", category: "animais" },
  { word: "IGUANA", clue: "Grande lagarto herbívoro comum em regiões tropicais", category: "animais" },
  { word: "CROCODILO", clue: "Grande réptil semiaquático de focinho alongado", category: "animais" },
  { word: "LAGOSTA", clue: "Crustáceo marinho de carapaça dura e grandes antenas", category: "animais" },
  { word: "CAMARAO", clue: "Pequeno crustáceo muito utilizado na alimentação", category: "animais" },
  { word: "MINHOCA", clue: "Animal alongado que vive no solo e ajuda a arejá-lo", category: "animais" },
  { word: "VALE", clue: "Área baixa situada entre montanhas ou elevações", category: "natureza" },
  { word: "CAVERNA", clue: "Cavidade natural formada em rochas", category: "natureza" },
  { word: "GRUTA", clue: "Cavidade natural menor encontrada em formações rochosas", category: "natureza" },
  { word: "LAGOA", clue: "Porção de água cercada por terra, geralmente menor que um lago", category: "natureza" },
  { word: "LAGO", clue: "Grande porção de água cercada por terra", category: "natureza" },
  { word: "PANTANO", clue: "Área de solo encharcado com água parada ou de pouca corrente", category: "natureza" },
  { word: "MANGUE", clue: "Ecossistema costeiro de água salobra e vegetação adaptada", category: "natureza" },
  { word: "SAVANA", clue: "Formação vegetal com gramíneas e árvores espaçadas", category: "natureza" },
  { word: "TUNDRA", clue: "Bioma frio com vegetação rasteira e solo frequentemente congelado", category: "natureza" },
  { word: "TAIGA", clue: "Bioma frio dominado principalmente por florestas de coníferas", category: "natureza" },
  { word: "RECIFE", clue: "Formação rochosa ou coralínea próxima à superfície do mar", category: "natureza" },
  { word: "CORAL", clue: "Organismo marinho que pode formar grandes recifes", category: "natureza" },
  { word: "LAVA", clue: "Rocha derretida expelida por um vulcão", category: "natureza" },
  { word: "MAGMA", clue: "Material rochoso derretido existente abaixo da superfície terrestre", category: "natureza" },
  { word: "TERREMOTO", clue: "Tremor da crosta terrestre causado por liberação de energia", category: "natureza" },
  { word: "TSUNAMI", clue: "Grande onda do mar provocada por deslocamentos bruscos de água", category: "natureza" },
  { word: "FURACAO", clue: "Tempestade tropical intensa com ventos muito fortes", category: "natureza" },
  { word: "TORNADO", clue: "Coluna de ar em rotação que se estende de uma nuvem ao solo", category: "natureza" },
  { word: "NEBLINA", clue: "Conjunto de pequenas gotas de água suspensas próximas ao solo", category: "natureza" },
  { word: "ORVALHO", clue: "Pequenas gotas de água formadas sobre superfícies durante a noite", category: "natureza" },
  { word: "GEADA", clue: "Camada fina de gelo que se forma sobre superfícies frias", category: "natureza" },
  { word: "GRANIZO", clue: "Precipitação formada por pedras de gelo", category: "natureza" },
  { word: "RELAMPAGO", clue: "Clarão produzido por uma descarga elétrica na atmosfera", category: "natureza" },
  { word: "TROVAO", clue: "Som produzido pela rápida expansão do ar após um relâmpago", category: "natureza" },
  { word: "SEMENTE", clue: "Estrutura vegetal capaz de originar uma nova planta", category: "natureza" },
  { word: "RAIZ", clue: "Parte da planta que geralmente fixa e absorve água do solo", category: "natureza" },
  { word: "CAULE", clue: "Parte da planta que sustenta folhas, flores e frutos", category: "natureza" },
  { word: "FOLHA", clue: "Estrutura vegetal geralmente responsável pela fotossíntese", category: "natureza" },
  { word: "PETALA", clue: "Parte colorida que compõe muitas flores", category: "natureza" },
  { word: "POLEN", clue: "Conjunto de grãos produzidos por estruturas reprodutivas das plantas", category: "natureza" },
  { word: "ARMARIO", clue: "Móvel usado para guardar roupas, utensílios ou objetos", category: "casa" },
  { word: "ESTANTE", clue: "Móvel com prateleiras usado para guardar livros e objetos", category: "casa" },
  { word: "PRATELEIRA", clue: "Superfície horizontal usada para apoiar ou guardar objetos", category: "casa" },
  { word: "GAVETA", clue: "Compartimento deslizante usado para guardar objetos", category: "casa" },
  { word: "GUARDAROUPA", clue: "Móvel usado principalmente para armazenar roupas", category: "casa" },
  { word: "FOGAO", clue: "Eletrodoméstico usado para cozinhar alimentos", category: "casa" },
  { word: "FORNO", clue: "Equipamento usado para assar ou aquecer alimentos", category: "casa" },
  { word: "MICROONDAS", clue: "Eletrodoméstico que aquece alimentos rapidamente", category: "casa" },
  { word: "LIQUIDIFICADOR", clue: "Eletrodoméstico usado para triturar e misturar alimentos", category: "casa" },
  { word: "VENTILADOR", clue: "Aparelho que movimenta o ar para refrescar o ambiente", category: "casa" },
  { word: "CHUVEIRO", clue: "Equipamento do banheiro usado para tomar banho", category: "casa" },
  { word: "TORNEIRA", clue: "Dispositivo que controla a saída de água", category: "casa" },
  { word: "PIA", clue: "Estrutura com cuba usada para lavar mãos, louças ou alimentos", category: "casa" },
  { word: "VARANDA", clue: "Espaço aberto ou semiaberto ligado a uma residência", category: "casa" },
  { word: "GARAGEM", clue: "Espaço destinado a guardar veículos", category: "casa" },
  { word: "QUINTAL", clue: "Área externa de uma casa, geralmente situada nos fundos", category: "casa" },
  { word: "ESCADA", clue: "Estrutura formada por degraus usada para vencer desníveis", category: "casa" },
  { word: "CORTINA", clue: "Tecido usado para cobrir janelas e controlar a entrada de luz", category: "casa" },
  { word: "ALMOFADA", clue: "Objeto macio usado como apoio ou decoração", category: "casa" },
  { word: "COLCHAO", clue: "Peça acolchoada colocada sobre a cama para dormir", category: "casa" },
  { word: "PERA", clue: "Fruta de casca fina e formato arredondado na base", category: "comida" },
  { word: "GOIABA", clue: "Fruta tropical que pode ter polpa branca ou rosada", category: "comida" },
  { word: "MARACUJA", clue: "Fruta de sabor ácido muito usada em sucos e sobremesas", category: "comida" },
  { word: "MAMAO", clue: "Fruta tropical de polpa alaranjada e muitas sementes", category: "comida" },
  { word: "COCO", clue: "Fruto de casca dura que contém água e polpa branca", category: "comida" },
  { word: "KIWI", clue: "Fruta de casca marrom e polpa verde com pequenas sementes", category: "comida" },
  { word: "PESSEGO", clue: "Fruta de casca aveludada e polpa suculenta", category: "comida" },
  { word: "AMEIXA", clue: "Fruta pequena de polpa macia e caroço central", category: "comida" },
  { word: "CEREJA", clue: "Pequena fruta geralmente vermelha com caroço", category: "comida" },
  { word: "LIMAO", clue: "Fruta cítrica de sabor bastante ácido", category: "comida" },
  { word: "TANGERINA", clue: "Fruta cítrica de gomos facilmente separáveis", category: "comida" },
  { word: "ABACATE", clue: "Fruta de polpa cremosa rica em gorduras naturais", category: "comida" },
  { word: "CENOURA", clue: "Raiz alaranjada muito utilizada em saladas e pratos cozidos", category: "comida" },
  { word: "BATATA", clue: "Tubérculo muito utilizado em diversos pratos", category: "comida" },
  { word: "TOMATE", clue: "Fruto vermelho muito usado em saladas e molhos", category: "comida" },
  { word: "CEBOLA", clue: "Vegetal de camadas usado como tempero em muitos pratos", category: "comida" },
  { word: "ALHO", clue: "Ingrediente de sabor marcante muito usado como tempero", category: "comida" },
  { word: "ALFACE", clue: "Folha verde muito comum em saladas", category: "comida" },
  { word: "BROCOLIS", clue: "Vegetal verde formado por pequenos ramos florais", category: "comida" },
  { word: "MILHO", clue: "Cereal de grãos amarelos usado em muitos alimentos", category: "comida" },
  { word: "PIPOCA", clue: "Milho estourado pelo calor, comum em sessões de cinema", category: "comida" },
  { word: "HAMBURGUER", clue: "Sanduíche preparado geralmente com um disco de carne", category: "comida" },
  { word: "LASANHA", clue: "Prato feito com camadas de massa, molho e recheio", category: "comida" },
  { word: "PASTEL", clue: "Massa fina recheada e geralmente frita", category: "comida" },
  { word: "COXINHA", clue: "Salgado brasileiro normalmente recheado com frango", category: "comida" },
  { word: "TAPIOCA", clue: "Preparação feita com fécula de mandioca aquecida", category: "comida" },
  { word: "CUSCUZ", clue: "Prato feito com grãos ou flocos cozidos no vapor ou hidratados", category: "comida" },
  { word: "PUDIM", clue: "Sobremesa cremosa geralmente feita com leite e ovos", category: "comida" },
  { word: "BISCOITO", clue: "Alimento assado, pequeno e crocante ou macio", category: "comida" },
  { word: "IOGURTE", clue: "Alimento cremoso produzido pela fermentação do leite", category: "comida" },
  { word: "PESCOCO", clue: "Parte do corpo que liga a cabeça ao tronco", category: "corpo" },
  { word: "OMBRO", clue: "Região que liga o braço ao tronco", category: "corpo" },
  { word: "COTOVELO", clue: "Articulação localizada entre o braço e o antebraço", category: "corpo" },
  { word: "PULSO", clue: "Região que liga a mão ao antebraço", category: "corpo" },
  { word: "DEDO", clue: "Cada uma das extremidades articuladas das mãos e dos pés", category: "corpo" },
  { word: "UNHA", clue: "Estrutura dura que recobre a ponta dos dedos", category: "corpo" },
  { word: "PE", clue: "Extremidade inferior do corpo usada para apoio e locomoção", category: "corpo" },
  { word: "JOELHO", clue: "Articulação localizada entre a coxa e a perna", category: "corpo" },
  { word: "TORNOZELO", clue: "Articulação que liga a perna ao pé", category: "corpo" },
  { word: "COSTAS", clue: "Parte posterior do tronco", category: "corpo" },
  { word: "PEITO", clue: "Parte frontal superior do tronco", category: "corpo" },
  { word: "BARRIGA", clue: "Região frontal do abdômen", category: "corpo" },
  { word: "LINGUA", clue: "Órgão muscular da boca relacionado ao paladar e à fala", category: "corpo" },
  { word: "GARGANTA", clue: "Região interna do pescoço por onde passam ar e alimentos", category: "corpo" },
  { word: "RIM", clue: "Órgão responsável por filtrar o sangue e produzir urina", category: "corpo" },
  { word: "BEXIGA", clue: "Órgão que armazena a urina antes da eliminação", category: "corpo" },
  { word: "MUSCULO", clue: "Tecido corporal responsável por produzir movimento", category: "corpo" },
  { word: "OSSO", clue: "Estrutura rígida que compõe o esqueleto", category: "corpo" },
  { word: "PELE", clue: "Maior órgão do corpo humano, responsável por revesti-lo", category: "corpo" },
  { word: "SANGUE", clue: "Tecido líquido que circula pelos vasos do corpo", category: "corpo" },
  { word: "ARQUITETO", clue: "Profissional que projeta edifícios e espaços", category: "profissoes" },
  { word: "PROGRAMADOR", clue: "Profissional que cria e mantém programas de computador", category: "profissoes" },
  { word: "DESIGNER", clue: "Profissional que desenvolve soluções visuais ou funcionais", category: "profissoes" },
  { word: "FOTOGRAFO", clue: "Profissional que registra imagens por meio de fotografia", category: "profissoes" },
  { word: "MECANICO", clue: "Profissional que realiza manutenção e conserto de máquinas ou veículos", category: "profissoes" },
  { word: "ELETRICISTA", clue: "Profissional que instala e repara sistemas elétricos", category: "profissoes" },
  { word: "PEDREIRO", clue: "Profissional que trabalha diretamente na execução de construções", category: "profissoes" },
  { word: "CARPINTEIRO", clue: "Profissional que trabalha na fabricação de estruturas e objetos de madeira", category: "profissoes" },
  { word: "PADEIRO", clue: "Profissional que prepara pães e outros produtos de padaria", category: "profissoes" },
  { word: "GARCOM", clue: "Profissional que atende clientes e serve alimentos e bebidas", category: "profissoes" },
  { word: "BARBEIRO", clue: "Profissional especializado no corte de cabelo e barba", category: "profissoes" },
  { word: "VETERINARIO", clue: "Profissional que cuida da saúde dos animais", category: "profissoes" },
  { word: "FARMACEUTICO", clue: "Profissional especializado em medicamentos e sua utilização", category: "profissoes" },
  { word: "PSICOLOGO", clue: "Profissional que estuda e trabalha com comportamento e processos mentais", category: "profissoes" },
  { word: "CIENTISTA", clue: "Profissional dedicado à investigação e produção de conhecimento científico", category: "profissoes" },
  { word: "ASTRONAUTA", clue: "Profissional treinado para viajar e trabalhar no espaço", category: "profissoes" },
  { word: "AGRICULTOR", clue: "Profissional que trabalha no cultivo da terra", category: "profissoes" },
  { word: "PESCADOR", clue: "Profissional que captura peixes e outros animais aquáticos", category: "profissoes" },
  { word: "COSTUREIRO", clue: "Profissional que confecciona ou ajusta peças de roupa", category: "profissoes" },
  { word: "MUSICO", clue: "Profissional que toca instrumentos ou trabalha com música", category: "profissoes" },
  { word: "MONITOR", clue: "Tela utilizada para exibir imagens produzidas por um computador", category: "tecnologia" },
  { word: "NOTEBOOK", clue: "Computador portátil com tela e teclado integrados", category: "tecnologia" },
  { word: "TABLET", clue: "Dispositivo portátil com tela sensível ao toque", category: "tecnologia" },
  { word: "ROTEADOR", clue: "Equipamento responsável por encaminhar dados em uma rede", category: "tecnologia" },
  { word: "MODEM", clue: "Equipamento usado para estabelecer conexão com uma rede de comunicação", category: "tecnologia" },
  { word: "CABO", clue: "Meio físico usado para transmitir energia ou dados", category: "tecnologia" },
  { word: "USB", clue: "Padrão de conexão usado para dados e energia entre dispositivos", category: "tecnologia" },
  { word: "BLUETOOTH", clue: "Tecnologia sem fio usada para conectar dispositivos próximos", category: "tecnologia" },
  { word: "WIFI", clue: "Tecnologia de rede sem fio usada para conectar dispositivos à internet", category: "tecnologia" },
  { word: "NAVEGADOR", clue: "Programa usado para acessar páginas e serviços da internet", category: "tecnologia" },
  { word: "APLICATIVO", clue: "Programa desenvolvido para executar funções específicas", category: "tecnologia" },
  { word: "ARQUIVO", clue: "Conjunto de dados armazenado com um nome em um dispositivo", category: "tecnologia" },
  { word: "PASTA", clue: "Estrutura usada para organizar arquivos em um sistema", category: "tecnologia" },
  { word: "ANTIVIRUS", clue: "Programa usado para detectar e remover softwares maliciosos", category: "tecnologia" },
  { word: "BACKUP", clue: "Cópia de segurança utilizada para recuperar dados", category: "tecnologia" },
  { word: "PIXEL", clue: "Menor unidade que compõe uma imagem digital em uma tela", category: "tecnologia" },
  { word: "CODIGO", clue: "Conjunto de instruções escritas em uma linguagem de programação", category: "tecnologia" },
  { word: "COMPILADOR", clue: "Programa que traduz código-fonte para outra forma executável", category: "tecnologia" },
  { word: "REDE", clue: "Conjunto de dispositivos conectados para compartilhar dados e recursos", category: "tecnologia" },
  { word: "DADOS", clue: "Informações armazenadas ou processadas por sistemas", category: "tecnologia" },
  { word: "SENSOR", clue: "Dispositivo capaz de detectar alterações no ambiente", category: "tecnologia" },
  { word: "HEMISFERIO", clue: "Metade de uma esfera, como as divisões Norte e Sul da Terra", category: "geografia" },
  { word: "FRONTEIRA", clue: "Linha ou região que separa dois territórios", category: "geografia" },
  { word: "TERRITORIO", clue: "Área delimitada sob domínio ou administração", category: "geografia" },
  { word: "REGIAO", clue: "Área definida por características geográficas ou administrativas", category: "geografia" },
  { word: "ESTADO", clue: "Divisão administrativa de um país em determinados sistemas políticos", category: "geografia" },
  { word: "MUNICIPIO", clue: "Divisão administrativa governada localmente", category: "geografia" },
  { word: "BAIRRO", clue: "Parte de uma cidade com identidade e limites próprios", category: "geografia" },
  { word: "VILAREJO", clue: "Pequeno núcleo habitado menor que uma cidade", category: "geografia" },
  { word: "METROPOLE", clue: "Cidade de grande importância econômica, política ou cultural", category: "geografia" },
  { word: "URBANIZACAO", clue: "Processo de crescimento das cidades e da população urbana", category: "geografia" },
  { word: "MIGRACAO", clue: "Deslocamento de pessoas de uma região para outra", category: "geografia" },
  { word: "POPULACAO", clue: "Conjunto de habitantes de uma determinada área", category: "geografia" },
  { word: "DENSIDADE", clue: "Relação entre quantidade de habitantes e área ocupada", category: "geografia" },
  { word: "CLIMA", clue: "Conjunto de condições atmosféricas médias de uma região", category: "geografia" },
  { word: "RELEVO", clue: "Conjunto das formas da superfície terrestre", category: "geografia" },
  { word: "BACIA", clue: "Área drenada por um rio principal e seus afluentes", category: "geografia" },
  { word: "DELTA", clue: "Formação na foz de um rio causada pelo acúmulo de sedimentos", category: "geografia" },
  { word: "CANION", clue: "Vale profundo com paredes íngremes escavado geralmente por um rio", category: "geografia" },
  { word: "CINZA", clue: "Cor intermediária entre o preto e o branco", category: "cores" },
  { word: "MARROM", clue: "Cor comum da madeira e da terra", category: "cores" },
  { word: "BEGE", clue: "Cor clara próxima ao tom da areia", category: "cores" },
  { word: "DOURADO", clue: "Cor que lembra o brilho do ouro", category: "cores" },
  { word: "PRATEADO", clue: "Cor metálica que lembra a prata", category: "cores" },
  { word: "VIOLETA", clue: "Cor próxima ao roxo no espectro visível", category: "cores" },
  { word: "TURQUESA", clue: "Cor azul-esverdeada que lembra certas águas tropicais", category: "cores" },
  { word: "HANDEBOL", clue: "Esporte coletivo em que a bola é conduzida principalmente com as mãos", category: "esportes" },
  { word: "FUTSAL", clue: "Modalidade semelhante ao futebol praticada em quadra", category: "esportes" },
  { word: "BEISEBOL", clue: "Esporte de taco e bola muito popular nos Estados Unidos", category: "esportes" },
  { word: "RUGBY", clue: "Esporte coletivo de contato jogado com bola oval", category: "esportes" },
  { word: "BOXE", clue: "Esporte de combate baseado principalmente em golpes com os punhos", category: "esportes" },
  { word: "JUDO", clue: "Arte marcial e esporte de combate de origem japonesa", category: "esportes" },
  { word: "KARATE", clue: "Arte marcial japonesa baseada em golpes e técnicas de defesa", category: "esportes" },
  { word: "SKATE", clue: "Esporte praticado sobre uma prancha com quatro rodas", category: "esportes" },
  { word: "PATINACAO", clue: "Esporte ou atividade praticada com patins", category: "esportes" },
  { word: "ESCALADA", clue: "Atividade esportiva de subir paredes naturais ou artificiais", category: "esportes" },
  { word: "REMO", clue: "Esporte aquático em que embarcações são movidas com remos", category: "esportes" },
  { word: "CANOAGEM", clue: "Esporte aquático praticado em canoas ou caiaques", category: "esportes" },
  { word: "GOLFE", clue: "Esporte em que se tenta colocar uma bola em buracos com poucas tacadas", category: "esportes" },
  { word: "PINGUEPONGUE", clue: "Esporte de mesa jogado com pequenas raquetes e uma bola leve", category: "esportes" },
  { word: "CAMINHAO", clue: "Veículo grande utilizado principalmente para transporte de cargas", category: "transporte" },
  { word: "VAN", clue: "Veículo maior que um carro, usado para transportar pessoas ou cargas", category: "transporte" },
  { word: "TAXI", clue: "Veículo usado para transporte individual mediante pagamento", category: "transporte" },
  { word: "TRATOR", clue: "Veículo de grande força usado principalmente em atividades agrícolas", category: "transporte" },
  { word: "HELICOPTERO", clue: "Aeronave que voa por meio de rotores", category: "transporte" },
  { word: "NAVIO", clue: "Grande embarcação usada para transportar pessoas ou cargas", category: "transporte" },
  { word: "SUBMARINO", clue: "Embarcação capaz de navegar submersa", category: "transporte" },
  { word: "CANOA", clue: "Pequena embarcação estreita movida geralmente por remos", category: "transporte" },
  { word: "CAIAQUE", clue: "Embarcação estreita movida com remo de duas pás", category: "transporte" },
  { word: "BONDE", clue: "Veículo urbano que circula sobre trilhos", category: "transporte" },
  { word: "PATINETE", clue: "Veículo leve com plataforma e guidão", category: "transporte" },
  { word: "AMBULANCIA", clue: "Veículo destinado ao transporte de pessoas em atendimento médico", category: "transporte" },
  { word: "TAMBOR", clue: "Instrumento de percussão com corpo oco e membrana tensionada", category: "musica" },
  { word: "SAXOFONE", clue: "Instrumento de sopro metálico muito associado ao jazz", category: "musica" },
  { word: "TROMPETE", clue: "Instrumento de sopro de metal com som brilhante", category: "musica" },
  { word: "VIOLINO", clue: "Instrumento de cordas tocado normalmente com arco", category: "musica" },
  { word: "VIOLONCELO", clue: "Instrumento de cordas de maior porte tocado com arco", category: "musica" },
  { word: "HARPA", clue: "Instrumento de cordas com estrutura triangular", category: "musica" },
  { word: "ACORDEAO", clue: "Instrumento de fole e teclas também conhecido como sanfona", category: "musica" },
  { word: "PANDEIRO", clue: "Instrumento de percussão circular muito usado na música brasileira", category: "musica" },
  { word: "RITMO", clue: "Organização temporal dos sons em uma composição musical", category: "musica" },
  { word: "MELODIA", clue: "Sequência de notas percebida como uma unidade musical", category: "musica" },
  { word: "HARMONIA", clue: "Combinação simultânea de sons que acompanha ou sustenta uma melodia", category: "musica" },
  { word: "REFRAO", clue: "Parte de uma música que geralmente se repete", category: "musica" },
  { word: "DIA", clue: "Período de aproximadamente vinte e quatro horas", category: "tempo" },
  { word: "HORA", clue: "Unidade de tempo equivalente a sessenta minutos", category: "tempo" },
  { word: "MINUTO", clue: "Unidade de tempo equivalente a sessenta segundos", category: "tempo" },
  { word: "SEGUNDO", clue: "Unidade básica de medida de tempo", category: "tempo" },
  { word: "MADRUGADA", clue: "Período entre a meia-noite e o amanhecer", category: "tempo" },
  { word: "MANHA", clue: "Período do dia entre o amanhecer e o meio-dia", category: "tempo" },
  { word: "TARDE", clue: "Período do dia entre o meio-dia e o anoitecer", category: "tempo" },
  { word: "NOITE", clue: "Período do dia marcado pela ausência de luz solar direta", category: "tempo" },
  { word: "ONTEM", clue: "Dia imediatamente anterior ao atual", category: "tempo" },
  { word: "AMANHA", clue: "Dia imediatamente posterior ao atual", category: "tempo" },
  { word: "CALENDARIO", clue: "Sistema ou objeto usado para organizar dias, meses e anos", category: "tempo" },
  { word: "DECADA", clue: "Período de dez anos", category: "tempo" },
  { word: "SECULO", clue: "Período de cem anos", category: "tempo" },
  { word: "MILENIO", clue: "Período de mil anos", category: "tempo" },
  { word: "MARTELO", clue: "Ferramenta usada principalmente para bater ou pregar", category: "objetos" },
  { word: "CHAVEDEFENDA", clue: "Ferramenta usada para apertar ou soltar parafusos", category: "objetos" },
  { word: "SERROTE", clue: "Ferramenta manual com lâmina dentada usada para cortar", category: "objetos" },
  { word: "FURADEIRA", clue: "Ferramenta elétrica usada para fazer furos", category: "objetos" },
  { word: "LANTERNA", clue: "Objeto portátil que produz luz", category: "objetos" },
  { word: "MOCHILA", clue: "Bolsa carregada nas costas por meio de alças", category: "objetos" },
  { word: "CARTEIRA", clue: "Objeto usado para guardar dinheiro, cartões e documentos", category: "objetos" },
  { word: "GARRAFA", clue: "Recipiente de gargalo estreito usado para armazenar líquidos", category: "objetos" },
  { word: "COPO", clue: "Recipiente usado para beber líquidos", category: "objetos" },
  { word: "PRATO", clue: "Utensílio usado para servir alimentos", category: "objetos" },
  { word: "GARFO", clue: "Utensílio com dentes usado para levar alimentos à boca", category: "objetos" },
  { word: "FACA", clue: "Utensílio de lâmina usado para cortar", category: "objetos" },
  { word: "COLHER", clue: "Utensílio de formato côncavo usado para comer ou servir", category: "objetos" },
  { word: "PANELA", clue: "Recipiente usado para cozinhar alimentos", category: "objetos" },
  { word: "BALDE", clue: "Recipiente aberto com alça usado para carregar líquidos ou materiais", category: "objetos" },
  { word: "CORDA", clue: "Conjunto resistente de fibras torcidas usado para amarrar ou puxar", category: "objetos" },
  { word: "CADEADO", clue: "Fechadura portátil usada para prender ou proteger objetos", category: "objetos" },
  { word: "IMÃ", clue: "Objeto que produz um campo capaz de atrair certos metais", category: "objetos" },
  { word: "REGUA", clue: "Instrumento reto usado para medir ou traçar linhas", category: "objetos" },
  { word: "BORRACHA", clue: "Objeto usado para apagar marcas de lápis", category: "objetos" },
  { word: "CADERNO", clue: "Conjunto de folhas encadernadas usado para escrever", category: "objetos" },
  { word: "ENVELOPE", clue: "Invólucro de papel usado para guardar cartas ou documentos", category: "objetos" },
  { word: "CANUDO", clue: "Tubo fino usado para beber líquidos", category: "objetos" },
  { word: "FONE", clue: "Dispositivo usado para ouvir áudio próximo aos ouvidos", category: "objetos" },
  { word: "CELULA", clue: "Unidade estrutural e funcional básica dos seres vivos", category: "ciencia" },
  { word: "DNA", clue: "Molécula que armazena grande parte da informação genética dos seres vivos", category: "ciencia" },
  { word: "RNA", clue: "Molécula envolvida em diversos processos de expressão da informação genética", category: "ciencia" },
  { word: "ENERGIA", clue: "Capacidade de realizar trabalho ou provocar transformações", category: "ciencia" },
  { word: "MASSA", clue: "Grandeza física relacionada à quantidade de matéria de um corpo", category: "ciencia" },
  { word: "FORCA", clue: "Interação capaz de alterar o movimento ou deformar um corpo", category: "ciencia" },
  { word: "VELOCIDADE", clue: "Grandeza que relaciona deslocamento e tempo", category: "ciencia" },
  { word: "ACELERACAO", clue: "Taxa de variação da velocidade ao longo do tempo", category: "ciencia" },
  { word: "PRESSAO", clue: "Grandeza que relaciona força aplicada e área", category: "ciencia" },
  { word: "TEMPERATURA", clue: "Grandeza física associada ao estado térmico de um corpo", category: "ciencia" },
  { word: "OXIGENIO", clue: "Elemento químico essencial à respiração da maioria dos seres vivos", category: "ciencia" },
  { word: "HIDROGENIO", clue: "Elemento químico mais abundante do universo", category: "ciencia" },
  { word: "CARBONO", clue: "Elemento químico fundamental para a química da vida", category: "ciencia" },
  { word: "NITROGENIO", clue: "Elemento químico que compõe a maior parte da atmosfera terrestre", category: "ciencia" },
  { word: "REACAO", clue: "Processo em que substâncias se transformam em outras", category: "ciencia" },
  { word: "ENZIMA", clue: "Molécula que acelera reações químicas nos seres vivos", category: "ciencia" },
  { word: "BACTERIA", clue: "Microrganismo unicelular encontrado em muitos ambientes", category: "ciencia" },
  { word: "VIRUS", clue: "Agente infeccioso que depende de células para se reproduzir", category: "ciencia" },
  { word: "FOSSIL", clue: "Vestígio ou resto preservado de organismo do passado", category: "ciencia" },
  { word: "PLANETA", clue: "Corpo celeste que orbita uma estrela e possui forma aproximadamente esférica", category: "ciencia" },
  { word: "GALAXIA", clue: "Grande conjunto de estrelas, gás, poeira e matéria escura", category: "ciencia" },
  { word: "UNIVERSO", clue: "Conjunto de toda matéria, energia, espaço e tempo conhecidos", category: "ciencia" },
  { word: "ORBITA", clue: "Trajetória de um corpo ao redor de outro pela ação da gravidade", category: "ciencia" },
  { word: "COMETA", clue: "Corpo celeste de gelo e poeira que pode formar uma cauda ao se aproximar do Sol", category: "ciencia" },
  { word: "ASTEROIDE", clue: "Corpo rochoso menor que um planeta que orbita uma estrela", category: "ciencia" },
  { word: "IDADEMEDIA", clue: "Período histórico europeu situado entre a Antiguidade e a Idade Moderna", category: "historia" },
  { word: "ILUMINISMO", clue: "Movimento intelectual que valorizou razão, ciência e liberdade", category: "historia" },
  { word: "REPUBLICA", clue: "Forma de governo em que o chefe de Estado não é um monarca hereditário", category: "historia" },
  { word: "ESCRAVIDAO", clue: "Sistema em que pessoas são tratadas como propriedade e privadas de liberdade", category: "historia" },
  { word: "ABOLICAO", clue: "Ato de extinguir oficialmente uma prática ou instituição, como a escravidão", category: "historia" },
  { word: "CONSTITUICAO", clue: "Conjunto fundamental de normas que organiza um Estado", category: "historia" },
  { word: "CIVILIZACAO", clue: "Sociedade complexa com organização política, cultural e econômica", category: "historia" },
  { word: "DINASTIA", clue: "Sequência de governantes pertencentes à mesma família", category: "historia" },
  { word: "FARAO", clue: "Título usado pelos governantes do antigo Egito", category: "historia" },
  { word: "SAMURAI", clue: "Membro da classe guerreira do Japão feudal", category: "historia" },
  { word: "VIKING", clue: "Nome dado a povos nórdicos conhecidos por navegação, comércio e expedições", category: "historia" },
  { word: "CRUZADAS", clue: "Expedições militares de caráter religioso ocorridas na Idade Média", category: "historia" },
  { word: "REFORMA", clue: "Movimento religioso europeu do século dezesseis que rompeu com a Igreja Católica", category: "historia" },
  { word: "INDUSTRIALIZACAO", clue: "Processo de expansão da produção baseada em máquinas e fábricas", category: "historia" },
  { word: "IMIGRACAO", clue: "Entrada de pessoas em um país ou região para viver nele", category: "historia" },
  { word: "PRONOME", clue: "Classe de palavras que substitui ou acompanha um substantivo", category: "linguagem" },
  { word: "ADVERBIO", clue: "Classe de palavras que modifica verbo, adjetivo ou outro advérbio", category: "linguagem" },
  { word: "PREPOSICAO", clue: "Palavra que estabelece relação entre dois termos da oração", category: "linguagem" },
  { word: "CONJUNCAO", clue: "Palavra usada para ligar termos ou orações", category: "linguagem" },
  { word: "ARTIGO", clue: "Classe de palavras que acompanha o substantivo e pode determiná-lo", category: "linguagem" },
  { word: "SUJEITO", clue: "Termo da oração sobre o qual geralmente se declara algo", category: "linguagem" },
  { word: "PREDICADO", clue: "Parte da oração que contém o que se declara sobre o sujeito", category: "linguagem" },
  { word: "FRASE", clue: "Enunciado com sentido completo, com ou sem verbo", category: "linguagem" },
  { word: "ORACAO", clue: "Enunciado estruturado em torno de um verbo ou locução verbal", category: "linguagem" },
  { word: "PERIODO", clue: "Enunciado formado por uma ou mais orações", category: "linguagem" },
  { word: "SILABA", clue: "Unidade sonora pronunciada em uma única emissão de voz", category: "linguagem" },
  { word: "VOGAL", clue: "Som da fala produzido sem obstrução significativa do ar", category: "linguagem" },
  { word: "CONSOANTE", clue: "Som da fala produzido com alguma obstrução à passagem do ar", category: "linguagem" },
  { word: "DITONGO", clue: "Encontro de vogal e semivogal na mesma sílaba", category: "linguagem" },
  { word: "RIMA", clue: "Repetição ou semelhança de sons no final ou interior de versos", category: "linguagem" },
  { word: "POESIA", clue: "Forma de expressão literária marcada pelo uso artístico da linguagem", category: "linguagem" },
  { word: "NARRADOR", clue: "Voz responsável por contar os acontecimentos de uma narrativa", category: "linguagem" },
  { word: "PERSONAGEM", clue: "Ser que participa dos acontecimentos de uma narrativa", category: "linguagem" },
  { word: "PARAGRAFO", clue: "Trecho de texto formado por uma ou mais frases relacionadas", category: "linguagem" },
  { word: "VERDADE", clue: "Conceito relacionado à correspondência entre uma afirmação e a realidade", category: "filosofia" },
  { word: "JUSTICA", clue: "Conceito ligado à distribuição adequada de direitos, deveres e consequências", category: "filosofia" },
  { word: "LIBERDADE", clue: "Capacidade de agir e escolher dentro de determinadas condições", category: "filosofia" },
  { word: "VIRTUDE", clue: "Qualidade moral considerada positiva em uma pessoa", category: "filosofia" },
  { word: "CONSCIENCIA", clue: "Capacidade de perceber a si mesmo, o ambiente e os próprios pensamentos", category: "filosofia" },
  { word: "RAZAO", clue: "Faculdade humana ligada ao pensamento lógico e à compreensão", category: "filosofia" },
  { word: "CONHECIMENTO", clue: "Compreensão adquirida por experiência, estudo ou raciocínio", category: "filosofia" },
  { word: "DUVIDA", clue: "Estado de incerteza diante de uma afirmação ou escolha", category: "filosofia" },
  { word: "ARGUMENTO", clue: "Conjunto de razões usado para sustentar uma conclusão", category: "filosofia" },
];
