/**
 * Banco de palavras compartilhado (PT-BR) usado pelo Palavras Cruzadas e pelo
 * Caça-Palavras. Cada entrada tem a palavra em MAIÚSCULAS sem acentos/espaços
 * (para digitação e busca na grade) e uma dica em português para o Palavras
 * Cruzadas (o Caça-Palavras usa só `word`).
 *
 * Para adicionar novas palavras, basta incluir um novo item no array abaixo —
 * nenhum outro arquivo precisa mudar.
 */

export interface WordBankEntry {
  word: string;
  clue: string;
  category: string;
}

export const WORD_BANK: WordBankEntry[] = [
  { word: "GATO", clue: "Animal doméstico que mia", category: "animais" },
  { word: "CACHORRO", clue: "Melhor amigo do homem", category: "animais" },
  { word: "LEAO", clue: "Rei da selva", category: "animais" },
  { word: "TIGRE", clue: "Felino listrado da Ásia", category: "animais" },
  { word: "ELEFANTE", clue: "Mamífero com tromba", category: "animais" },
  { word: "GIRAFA", clue: "Animal de pescoço longo", category: "animais" },
  { word: "MACACO", clue: "Primata que gosta de bananas", category: "animais" },
  { word: "COELHO", clue: "Animal de orelhas compridas que pula", category: "animais" },
  { word: "CAVALO", clue: "Animal usado para montaria", category: "animais" },
  { word: "GALINHA", clue: "Ave que põe ovos", category: "animais" },
  { word: "PATO", clue: "Ave aquática que faz quá-quá", category: "animais" },
  { word: "URSO", clue: "Animal grande que hiberna", category: "animais" },
  { word: "LOBO", clue: "Animal selvagem que uiva", category: "animais" },
  { word: "RAPOSA", clue: "Animal astuto de cauda peluda", category: "animais" },
  { word: "TARTARUGA", clue: "Animal de casco lento", category: "animais" },
  { word: "BORBOLETA", clue: "Inseto colorido que sai do casulo", category: "animais" },
  { word: "ABELHA", clue: "Inseto que produz mel", category: "animais" },
  { word: "ARANHA", clue: "Animal de oito patas que tece teia", category: "animais" },
  { word: "PEIXE", clue: "Animal que vive na água e tem guelras", category: "animais" },
  { word: "GOLFINHO", clue: "Mamífero marinho muito inteligente", category: "animais" },
  { word: "TUBARAO", clue: "Predador temido dos oceanos", category: "animais" },
  { word: "COBRA", clue: "Réptil sem pernas", category: "animais" },
  { word: "JACARE", clue: "Réptil de rios que tem muitos dentes", category: "animais" },
  { word: "PINGUIM", clue: "Ave que não voa e vive no gelo", category: "animais" },
  { word: "CORUJA", clue: "Ave de rapina que enxerga à noite", category: "animais" },
  { word: "ZEBRA", clue: "Animal africano com listras", category: "animais" },
  { word: "CANGURU", clue: "Animal australiano que carrega filhote na bolsa", category: "animais" },
  { word: "FORMIGA", clue: "Inseto que vive em colônias organizadas", category: "animais" },
  { word: "ARVORE", clue: "Planta de tronco e copa", category: "natureza" },
  { word: "FLOR", clue: "Parte colorida e perfumada da planta", category: "natureza" },
  { word: "RIO", clue: "Curso de água que deságua no mar", category: "natureza" },
  { word: "MONTANHA", clue: "Grande elevação de terreno", category: "natureza" },
  { word: "OCEANO", clue: "Grande massa de água salgada", category: "natureza" },
  { word: "FLORESTA", clue: "Área com muitas árvores", category: "natureza" },
  { word: "DESERTO", clue: "Região seca e arenosa", category: "natureza" },
  { word: "VULCAO", clue: "Montanha que pode expelir lava", category: "natureza" },
  { word: "CACHOEIRA", clue: "Queda d'água natural", category: "natureza" },
  { word: "PRAIA", clue: "Faixa de areia à beira-mar", category: "natureza" },
  { word: "ILHA", clue: "Terra cercada de água por todos os lados", category: "natureza" },
  { word: "NUVEM", clue: "Massa de vapor no céu", category: "natureza" },
  { word: "CHUVA", clue: "Água que cai do céu", category: "natureza" },
  { word: "NEVE", clue: "Precipitação branca e gelada", category: "natureza" },
  { word: "VENTO", clue: "Ar em movimento", category: "natureza" },
  { word: "SOL", clue: "Astro que ilumina a Terra de dia", category: "natureza" },
  { word: "LUA", clue: "Satélite natural da Terra", category: "natureza" },
  { word: "ESTRELA", clue: "Ponto luminoso visível no céu à noite", category: "natureza" },
  { word: "PEDRA", clue: "Fragmento sólido e duro da natureza", category: "natureza" },
  { word: "AREIA", clue: "Material fino encontrado na praia", category: "natureza" },
  { word: "MESA", clue: "Móvel onde se faz as refeições", category: "casa" },
  { word: "CADEIRA", clue: "Móvel usado para sentar", category: "casa" },
  { word: "SOFA", clue: "Móvel estofado da sala", category: "casa" },
  { word: "CAMA", clue: "Móvel usado para dormir", category: "casa" },
  { word: "JANELA", clue: "Abertura da parede com vidro", category: "casa" },
  { word: "PORTA", clue: "Estrutura usada para entrar e sair", category: "casa" },
  { word: "TELHADO", clue: "Cobertura da casa", category: "casa" },
  { word: "PAREDE", clue: "Estrutura vertical que separa cômodos", category: "casa" },
  { word: "COZINHA", clue: "Cômodo onde se prepara comida", category: "casa" },
  { word: "BANHEIRO", clue: "Cômodo com chuveiro e vaso sanitário", category: "casa" },
  { word: "ESPELHO", clue: "Objeto que reflete a imagem", category: "casa" },
  { word: "CHAVE", clue: "Objeto que abre fechaduras", category: "casa" },
  { word: "LAMPADA", clue: "Objeto que ilumina os cômodos", category: "casa" },
  { word: "GELADEIRA", clue: "Eletrodoméstico que mantém alimentos frios", category: "casa" },
  { word: "TRAVESSEIRO", clue: "Usado para apoiar a cabeça ao dormir", category: "casa" },
  { word: "COBERTOR", clue: "Usado para se aquecer na cama", category: "casa" },
  { word: "VASO", clue: "Recipiente usado para plantas", category: "casa" },
  { word: "TAPETE", clue: "Peça de tecido colocada no chão", category: "casa" },
  { word: "ARROZ", clue: "Cereal branco muito consumido no Brasil", category: "comida" },
  { word: "FEIJAO", clue: "Combina com arroz no prato brasileiro", category: "comida" },
  { word: "PAO", clue: "Feito de farinha, comum no café da manhã", category: "comida" },
  { word: "QUEIJO", clue: "Derivado do leite", category: "comida" },
  { word: "LEITE", clue: "Bebida branca tirada da vaca", category: "comida" },
  { word: "OVO", clue: "Alimento posto pelas galinhas", category: "comida" },
  { word: "BANANA", clue: "Fruta amarela e curva", category: "comida" },
  { word: "MACA", clue: "Fruta vermelha ou verde, crocante", category: "comida" },
  { word: "LARANJA", clue: "Fruta cítrica usada em sucos", category: "comida" },
  { word: "ABACAXI", clue: "Fruta tropical com casca espinhosa", category: "comida" },
  { word: "MANGA", clue: "Fruta doce e suculenta de caroço grande", category: "comida" },
  { word: "MORANGO", clue: "Fruta vermelha pequena e doce", category: "comida" },
  { word: "UVA", clue: "Fruta usada para fazer vinho", category: "comida" },
  { word: "MELANCIA", clue: "Fruta grande, verde por fora e vermelha por dentro", category: "comida" },
  { word: "CHOCOLATE", clue: "Doce feito de cacau", category: "comida" },
  { word: "BOLO", clue: "Doce assado, comum em aniversários", category: "comida" },
  { word: "SORVETE", clue: "Sobremesa gelada e doce", category: "comida" },
  { word: "PIZZA", clue: "Prato italiano redondo com cobertura", category: "comida" },
  { word: "MACARRAO", clue: "Massa comum em pratos italianos", category: "comida" },
  { word: "CAFE", clue: "Bebida quente e escura, muito estimulante", category: "comida" },
  { word: "AGUA", clue: "Líquido essencial à vida", category: "comida" },
  { word: "SAL", clue: "Tempero branco e granulado", category: "comida" },
  { word: "ACUCAR", clue: "Tempero doce e granulado", category: "comida" },
  { word: "MEL", clue: "Substância doce produzida pelas abelhas", category: "comida" },
  { word: "CABECA", clue: "Parte superior do corpo", category: "corpo" },
  { word: "OLHO", clue: "Órgão da visão", category: "corpo" },
  { word: "NARIZ", clue: "Órgão do olfato", category: "corpo" },
  { word: "BOCA", clue: "Órgão usado para comer e falar", category: "corpo" },
  { word: "ORELHA", clue: "Órgão da audição", category: "corpo" },
  { word: "MAO", clue: "Parte do corpo com dedos usada para pegar", category: "corpo" },
  { word: "BRACO", clue: "Membro superior do corpo", category: "corpo" },
  { word: "PERNA", clue: "Membro inferior do corpo", category: "corpo" },
  { word: "CORACAO", clue: "Órgão que bombeia o sangue", category: "corpo" },
  { word: "CABELO", clue: "Cresce na cabeça", category: "corpo" },
  { word: "DENTE", clue: "Usado para mastigar", category: "corpo" },
  { word: "MEDICO", clue: "Profissional que cuida da saúde", category: "profissoes" },
  { word: "PROFESSOR", clue: "Profissional que ensina", category: "profissoes" },
  { word: "ENGENHEIRO", clue: "Profissional que projeta construções e sistemas", category: "profissoes" },
  { word: "ADVOGADO", clue: "Profissional que atua na área jurídica", category: "profissoes" },
  { word: "DENTISTA", clue: "Cuida da saúde dos dentes", category: "profissoes" },
  { word: "COZINHEIRO", clue: "Prepara refeições profissionalmente", category: "profissoes" },
  { word: "BOMBEIRO", clue: "Profissional que apaga incêndios", category: "profissoes" },
  { word: "POLICIAL", clue: "Profissional que garante a segurança pública", category: "profissoes" },
  { word: "PINTOR", clue: "Profissional que pinta quadros ou paredes", category: "profissoes" },
  { word: "MOTORISTA", clue: "Profissional que dirige veículos", category: "profissoes" },
  { word: "ENFERMEIRO", clue: "Auxilia médicos e cuida de pacientes", category: "profissoes" },
  { word: "PILOTO", clue: "Profissional que conduz aviões", category: "profissoes" },
  { word: "ATOR", clue: "Profissional que interpreta personagens", category: "profissoes" },
  { word: "CANTOR", clue: "Profissional que canta músicas", category: "profissoes" },
  { word: "JORNALISTA", clue: "Profissional que produz notícias", category: "profissoes" },
  { word: "COMPUTADOR", clue: "Máquina usada para processar dados", category: "tecnologia" },
  { word: "CELULAR", clue: "Telefone portátil", category: "tecnologia" },
  { word: "INTERNET", clue: "Rede mundial de computadores", category: "tecnologia" },
  { word: "TECLADO", clue: "Usado para digitar no computador", category: "tecnologia" },
  { word: "MOUSE", clue: "Periférico usado para clicar na tela", category: "tecnologia" },
  { word: "TELA", clue: "Onde as imagens do computador aparecem", category: "tecnologia" },
  { word: "IMPRESSORA", clue: "Equipamento que imprime documentos", category: "tecnologia" },
  { word: "CAMERA", clue: "Equipamento usado para tirar fotos", category: "tecnologia" },
  { word: "ROBO", clue: "Máquina automatizada que imita ações humanas", category: "tecnologia" },
  { word: "SENHA", clue: "Código secreto para acessar uma conta", category: "tecnologia" },
  { word: "BRASIL", clue: "País onde se fala português na América do Sul", category: "geografia" },
  { word: "CIDADE", clue: "Área urbana onde as pessoas vivem", category: "geografia" },
  { word: "PAIS", clue: "Território com governo próprio", category: "geografia" },
  { word: "CAPITAL", clue: "Principal cidade de um estado ou país", category: "geografia" },
  { word: "CONTINENTE", clue: "Grande extensão de terra, como a América", category: "geografia" },
  { word: "MAPA", clue: "Representação gráfica de um território", category: "geografia" },
  { word: "PONTE", clue: "Construção que liga duas margens", category: "geografia" },
  { word: "ESTRADA", clue: "Via usada para viajar de carro", category: "geografia" },
  { word: "AZUL", clue: "Cor do céu em dia claro", category: "cores" },
  { word: "VERMELHO", clue: "Cor do morango maduro", category: "cores" },
  { word: "AMARELO", clue: "Cor do sol e da banana", category: "cores" },
  { word: "VERDE", clue: "Cor das folhas", category: "cores" },
  { word: "ROSA", clue: "Cor associada ao romantismo", category: "cores" },
  { word: "PRETO", clue: "Cor da noite escura", category: "cores" },
  { word: "BRANCO", clue: "Cor da neve", category: "cores" },
  { word: "ROXO", clue: "Cor obtida misturando azul e vermelho", category: "cores" },
  { word: "FUTEBOL", clue: "Esporte mais popular do Brasil", category: "esportes" },
  { word: "VOLEI", clue: "Esporte jogado com uma rede e uma bola", category: "esportes" },
  { word: "BASQUETE", clue: "Esporte com cestas e bola laranja", category: "esportes" },
  { word: "NATACAO", clue: "Esporte praticado na piscina", category: "esportes" },
  { word: "TENIS", clue: "Esporte jogado com raquete", category: "esportes" },
  { word: "CORRIDA", clue: "Prova de velocidade a pé", category: "esportes" },
  { word: "CICLISMO", clue: "Esporte praticado com bicicleta", category: "esportes" },
  { word: "SURFE", clue: "Esporte praticado sobre as ondas", category: "esportes" },
  { word: "CARRO", clue: "Veículo de quatro rodas usado no dia a dia", category: "transporte" },
  { word: "ONIBUS", clue: "Transporte coletivo urbano", category: "transporte" },
  { word: "BICICLETA", clue: "Veículo de duas rodas movido a pedal", category: "transporte" },
  { word: "AVIAO", clue: "Veículo que voa e transporta passageiros", category: "transporte" },
  { word: "TREM", clue: "Veículo que anda sobre trilhos", category: "transporte" },
  { word: "BARCO", clue: "Veículo usado para navegar", category: "transporte" },
  { word: "MOTO", clue: "Veículo de duas rodas com motor", category: "transporte" },
  { word: "METRO", clue: "Transporte subterrâneo das grandes cidades", category: "transporte" },
  { word: "VIOLAO", clue: "Instrumento de cordas dedilhado", category: "musica" },
  { word: "PIANO", clue: "Instrumento de teclas", category: "musica" },
  { word: "BATERIA", clue: "Instrumento de percussão com pratos e tambores", category: "musica" },
  { word: "FLAUTA", clue: "Instrumento de sopro fino e longo", category: "musica" },
  { word: "GUITARRA", clue: "Instrumento de cordas elétrico", category: "musica" },
  { word: "MUSICA", clue: "Arte de combinar sons", category: "musica" },
  { word: "CANCAO", clue: "Composição musical cantada", category: "musica" },
  { word: "VERAO", clue: "Estação mais quente do ano", category: "tempo" },
  { word: "INVERNO", clue: "Estação mais fria do ano", category: "tempo" },
  { word: "OUTONO", clue: "Estação em que as folhas caem", category: "tempo" },
  { word: "PRIMAVERA", clue: "Estação das flores", category: "tempo" },
  { word: "SEMANA", clue: "Período de sete dias", category: "tempo" },
  { word: "MES", clue: "Período de cerca de trinta dias", category: "tempo" },
  { word: "ANO", clue: "Período de doze meses", category: "tempo" },
  { word: "LIVRO", clue: "Objeto usado para leitura", category: "objetos" },
  { word: "CANETA", clue: "Objeto usado para escrever com tinta", category: "objetos" },
  { word: "LAPIS", clue: "Objeto usado para escrever ou desenhar", category: "objetos" },
  { word: "RELOGIO", clue: "Objeto usado para ver as horas", category: "objetos" },
  { word: "BOLSA", clue: "Objeto usado para carregar pertences", category: "objetos" },
  { word: "OCULOS", clue: "Objeto usado para melhorar a visão", category: "objetos" },
  { word: "GUARDACHUVA", clue: "Objeto usado para proteger da chuva", category: "objetos" },
  { word: "TESOURA", clue: "Objeto usado para cortar papel ou tecido", category: "objetos" },
  { word: "AGULHA", clue: "Objeto fino usado para costurar", category: "objetos" },
  { word: "ESPADA", clue: "Arma antiga de lâmina longa", category: "objetos" },
  { word: "BOLA", clue: "Objeto redondo usado em muitos esportes", category: "objetos" },
  { word: "PIPA", clue: "Brinquedo que voa preso a uma linha", category: "objetos" },
  { word: "BONECA", clue: "Brinquedo em forma de pessoa", category: "objetos" },
  { word: "QUEBRACABECA", clue: "Jogo de montar peças que formam uma imagem", category: "objetos" },
  { word: "ORNITORRINCO", clue: "Mamífero australiano que põe ovos e possui bico", category: "animais" },
  { word: "CAMALEAO", clue: "Réptil conhecido pela capacidade de mudar de cor", category: "animais" },
  { word: "HIPOPOTAMO", clue: "Grande mamífero africano que passa muito tempo na água", category: "animais" },
  { word: "RINOCERONTE", clue: "Grande mamífero herbívoro com um ou dois chifres", category: "animais" },
  { word: "CHIMPANZE", clue: "Primata considerado um dos parentes vivos mais próximos do ser humano", category: "animais" },
  { word: "ORANGOTANGO", clue: "Grande primata de pelos alaranjados encontrado na Ásia", category: "animais" },
  { word: "ESCORPIAO", clue: "Aracnídeo que possui ferrão na extremidade da cauda", category: "animais" },
  { word: "CARANGUEJO", clue: "Crustáceo com carapaça e grandes pinças", category: "animais" },
  { word: "LAGARTIXA", clue: "Pequeno réptil frequentemente encontrado em paredes e casas", category: "animais" },
  { word: "SALAMANDRA", clue: "Anfíbio de corpo alongado e cauda geralmente bem desenvolvida", category: "animais" },
  { word: "TAMANDUA", clue: "Mamífero sul-americano especializado em comer formigas e cupins", category: "animais" },
  { word: "CAPIVARA", clue: "Maior roedor do mundo, comum em áreas próximas à água", category: "animais" },
  { word: "JAGUATIRICA", clue: "Felino selvagem de pequeno porte encontrado nas Américas", category: "animais" },
  { word: "PREGUICA", clue: "Mamífero arborícola conhecido por seus movimentos lentos", category: "animais" },
  { word: "BICHO-PREGUICA", clue: "Mamífero que passa grande parte do tempo pendurado em árvores", category: "animais" },
  { word: "ECOSSISTEMA", clue: "Conjunto formado pelos seres vivos e pelo ambiente onde vivem", category: "natureza" },
  { word: "BIODIVERSIDADE", clue: "Variedade de seres vivos existente em determinada região ou no planeta", category: "natureza" },
  { word: "FOTOSSINTESE", clue: "Processo pelo qual plantas produzem matéria orgânica usando luz", category: "natureza" },
  { word: "EVAPORACAO", clue: "Processo em que um líquido passa para o estado gasoso", category: "natureza" },
  { word: "CONDENSACAO", clue: "Processo em que um gás passa para o estado líquido", category: "natureza" },
  { word: "PRECIPITACAO", clue: "Queda de água da atmosfera na forma de chuva, neve ou granizo", category: "natureza" },
  { word: "ATMOSFERA", clue: "Camada de gases que envolve um planeta", category: "natureza" },
  { word: "HORIZONTE", clue: "Linha aparente onde o céu parece encontrar a superfície", category: "natureza" },
  { word: "ARCOIRIS", clue: "Fenômeno óptico colorido que pode surgir após a chuva", category: "natureza" },
  { word: "GELEIRA", clue: "Grande massa de gelo formada pelo acúmulo e compactação de neve", category: "natureza" },
  { word: "ESTALACTITE", clue: "Formação mineral que cresce no teto de cavernas", category: "natureza" },
  { word: "ESTALAGMITE", clue: "Formação mineral que cresce no chão de cavernas", category: "natureza" },
  { word: "GRAVIDADE", clue: "Força que atrai corpos com massa uns em direção aos outros", category: "ciencia" },
  { word: "ELETRON", clue: "Partícula subatômica de carga elétrica negativa", category: "ciencia" },
  { word: "PROTON", clue: "Partícula subatômica de carga elétrica positiva encontrada no núcleo", category: "ciencia" },
  { word: "NEUTRON", clue: "Partícula subatômica sem carga elétrica encontrada no núcleo", category: "ciencia" },
  { word: "ATOMO", clue: "Unidade básica da matéria que conserva as propriedades de um elemento", category: "ciencia" },
  { word: "MOLECULA", clue: "Conjunto de dois ou mais átomos ligados quimicamente", category: "ciencia" },
  { word: "CROMOSSOMO", clue: "Estrutura que contém material genético dentro das células", category: "ciencia" },
  { word: "MITOCONDRIA", clue: "Estrutura celular responsável por grande parte da produção de energia", category: "ciencia" },
  { word: "GRAVITACAO", clue: "Fenômeno de atração entre corpos que possuem massa", category: "ciencia" },
  { word: "ASTRONOMIA", clue: "Ciência que estuda os astros e os fenômenos do universo", category: "ciencia" },
  { word: "BIOLOGIA", clue: "Ciência que estuda os seres vivos", category: "ciencia" },
  { word: "QUIMICA", clue: "Ciência que estuda a matéria, suas propriedades e transformações", category: "ciencia" },
  { word: "FISICA", clue: "Ciência que estuda a matéria, energia, movimento e suas interações", category: "ciencia" },
  { word: "GENETICA", clue: "Área da biologia que estuda a hereditariedade", category: "ciencia" },
  { word: "EVOLUCAO", clue: "Processo de mudança das características das espécies ao longo das gerações", category: "ciencia" },
  { word: "ARQUIPÉLAGO", clue: "Conjunto de ilhas próximas umas das outras", category: "geografia" },
  { word: "PENINSULA", clue: "Porção de terra cercada de água em quase todos os lados", category: "geografia" },
  { word: "CORDILHEIRA", clue: "Grande conjunto ou cadeia de montanhas", category: "geografia" },
  { word: "MERIDIANO", clue: "Linha imaginária que liga os polos da Terra", category: "geografia" },
  { word: "PARALELO", clue: "Linha imaginária traçada paralelamente ao Equador", category: "geografia" },
  { word: "EQUADOR", clue: "Linha imaginária que divide a Terra nos hemisférios Norte e Sul", category: "geografia" },
  { word: "LATITUDE", clue: "Distância angular de um ponto em relação ao Equador", category: "geografia" },
  { word: "LONGITUDE", clue: "Distância angular de um ponto em relação ao meridiano de Greenwich", category: "geografia" },
  { word: "ARIDEZ", clue: "Característica de uma região com pouca disponibilidade de água", category: "geografia" },
  { word: "PLANALTO", clue: "Forma de relevo geralmente elevada e relativamente plana", category: "geografia" },
  { word: "PLANICIE", clue: "Área de relevo predominantemente plano e pouco elevado", category: "geografia" },
  { word: "DEPRESSAO", clue: "Área do relevo mais baixa que as regiões ao seu redor", category: "geografia" },
  { word: "ESTUARIO", clue: "Área onde um rio encontra o mar, geralmente com mistura de águas", category: "geografia" },
  { word: "NASCENTE", clue: "Local onde um rio começa", category: "geografia" },
  { word: "AFLUENTE", clue: "Rio ou curso de água que deságua em outro rio", category: "geografia" },
  { word: "RENASCIMENTO", clue: "Movimento cultural europeu associado à valorização da arte e da cultura clássica", category: "historia" },
  { word: "FEUDALISMO", clue: "Sistema social e econômico predominante na Europa medieval", category: "historia" },
  { word: "ABSOLUTISMO", clue: "Sistema político em que o monarca concentra grande parte do poder", category: "historia" },
  { word: "REVOLUCAO", clue: "Transformação política ou social profunda e geralmente rápida", category: "historia" },
  { word: "COLONIZACAO", clue: "Processo de ocupação e controle de um território por outro povo ou país", category: "historia" },
  { word: "INDEPENDENCIA", clue: "Condição de um território que deixa de estar subordinado a outro Estado", category: "historia" },
  { word: "MONARQUIA", clue: "Forma de governo em que o chefe de Estado é um monarca", category: "historia" },
  { word: "DEMOCRACIA", clue: "Sistema político baseado na participação dos cidadãos nas decisões públicas", category: "historia" },
  { word: "IMPERIO", clue: "Grande Estado formado por diferentes territórios sob um poder central", category: "historia" },
  { word: "ARQUEOLOGIA", clue: "Ciência que estuda sociedades antigas por meio de vestígios materiais", category: "historia" },
  { word: "ANTIGUIDADE", clue: "Período histórico associado às primeiras grandes civilizações", category: "historia" },
  { word: "PREHISTORIA", clue: "Período anterior ao surgimento da escrita", category: "historia" },
  { word: "ALGORITMO", clue: "Sequência de instruções usada para resolver um problema ou realizar uma tarefa", category: "tecnologia" },
  { word: "PROGRAMACAO", clue: "Processo de criação de instruções para computadores", category: "tecnologia" },
  { word: "INTELIGENCIA", clue: "Capacidade de aprender, compreender e resolver problemas", category: "tecnologia" },
  { word: "CRIPTOGRAFIA", clue: "Técnica utilizada para proteger informações por meio de codificação", category: "tecnologia" },
  { word: "PROCESSADOR", clue: "Componente responsável por executar instruções em um computador", category: "tecnologia" },
  { word: "MEMORIA", clue: "Componente usado para armazenar temporariamente dados e instruções", category: "tecnologia" },
  { word: "SERVIDOR", clue: "Computador ou sistema que fornece serviços ou recursos para outros dispositivos", category: "tecnologia" },
  { word: "BANCODEDADOS", clue: "Sistema organizado para armazenar e consultar informações", category: "tecnologia" },
  { word: "SOFTWARE", clue: "Conjunto de programas e instruções executados por um dispositivo", category: "tecnologia" },
  { word: "HARDWARE", clue: "Parte física de um computador ou dispositivo eletrônico", category: "tecnologia" },
  { word: "INTERFACE", clue: "Meio pelo qual uma pessoa interage com um sistema", category: "tecnologia" },
  { word: "AUTOMACAO", clue: "Uso de tecnologia para realizar tarefas com pouca intervenção humana", category: "tecnologia" },
  { word: "METAFORA", clue: "Figura de linguagem que estabelece uma comparação implícita", category: "linguagem" },
  { word: "IRONIA", clue: "Figura de linguagem em que se expressa algo sugerindo sentido diferente", category: "linguagem" },
  { word: "HIPERBOLE", clue: "Figura de linguagem que utiliza exagero para enfatizar uma ideia", category: "linguagem" },
  { word: "ONOMATOPEIA", clue: "Palavra que procura representar um som ou ruído", category: "linguagem" },
  { word: "ANTITESE", clue: "Figura de linguagem que aproxima ideias de sentidos opostos", category: "linguagem" },
  { word: "PARADOXO", clue: "Ideia ou afirmação que parece contraditória, mas pode conter uma verdade", category: "linguagem" },
  { word: "SINONIMO", clue: "Palavra que apresenta significado semelhante ao de outra", category: "linguagem" },
  { word: "ANTONIMO", clue: "Palavra que apresenta significado contrário ao de outra", category: "linguagem" },
  { word: "SUBSTANTIVO", clue: "Classe de palavras usada para nomear seres, objetos, lugares ou conceitos", category: "linguagem" },
  { word: "ADJETIVO", clue: "Classe de palavras que caracteriza ou qualifica um substantivo", category: "linguagem" },
  { word: "VERBO", clue: "Classe de palavras que geralmente indica ação, estado ou fenômeno", category: "linguagem" },
  { word: "FILOSOFIA", clue: "Busca racional pelo conhecimento e pela compreensão de questões fundamentais", category: "filosofia" },
  { word: "ETICA", clue: "Área da filosofia que estuda princípios relacionados ao certo e ao errado", category: "filosofia" },
  { word: "MORAL", clue: "Conjunto de princípios e valores que orientam comportamentos", category: "filosofia" },
  { word: "LOGICA", clue: "Área que estuda princípios do raciocínio válido", category: "filosofia" },
  { word: "EPISTEMOLOGIA", clue: "Área da filosofia dedicada ao estudo do conhecimento", category: "filosofia" },
  { word: "EXISTENCIALISMO", clue: "Corrente filosófica que enfatiza liberdade, escolha e existência humana", category: "filosofia" },
  { word: "EMPIRISMO", clue: "Corrente filosófica que destaca a experiência como fonte do conhecimento", category: "filosofia" },
  { word: "RACIONALISMO", clue: "Corrente filosófica que atribui grande importância à razão", category: "filosofia" },
  { word: "CEREBELO", clue: "Parte do encéfalo relacionada à coordenação dos movimentos e ao equilíbrio", category: "corpo" },
  { word: "CEREBRO", clue: "Principal parte do encéfalo, responsável por diversas funções cognitivas", category: "corpo" },
  { word: "PULMAO", clue: "Órgão responsável pelas trocas gasosas da respiração", category: "corpo" },
  { word: "ESTOMAGO", clue: "Órgão do sistema digestório que participa da digestão dos alimentos", category: "corpo" },
  { word: "INTESTINO", clue: "Órgão do sistema digestório responsável pela absorção de nutrientes e água", category: "corpo" },
  { word: "PANCREAS", clue: "Órgão que produz substâncias importantes para a digestão e hormônios", category: "corpo" },
  { word: "FIGADO", clue: "Órgão que desempenha diversas funções metabólicas e produz a bile", category: "corpo" },
  { word: "ESOFAGO", clue: "Tubo que conduz o alimento da boca até o estômago", category: "corpo" },
  { word: "DIAFRAGMA", clue: "Músculo que participa dos movimentos respiratórios", category: "corpo" },
  { word: "ARTERIA", clue: "Vaso sanguíneo que geralmente leva sangue para fora do coração", category: "corpo" },
  { word: "VEIA", clue: "Vaso sanguíneo que geralmente conduz sangue em direção ao coração", category: "corpo" },
  { word: "ATLETISMO", clue: "Conjunto de modalidades que inclui corridas, saltos e lançamentos", category: "esportes" },
  { word: "GINASTICA", clue: "Esporte que envolve movimentos de força, flexibilidade, equilíbrio e coordenação", category: "esportes" },
  { word: "ESGRIMA", clue: "Esporte de combate praticado com armas brancas específicas", category: "esportes" },
  { word: "ALPINISMO", clue: "Prática esportiva de escalada e ascensão de montanhas", category: "esportes" },
  { word: "MOTOCICLISMO", clue: "Modalidade esportiva que envolve competições com motocicletas", category: "esportes" },
  { word: "PARAQUEDISMO", clue: "Esporte praticado com saltos utilizando um paraquedas", category: "esportes" },
  { word: "TRIATLO", clue: "Competição que combina natação, ciclismo e corrida", category: "esportes" },
  { word: "GUACAMOLE", clue: "Preparação mexicana feita principalmente com abacate", category: "comida" },
  { word: "RATATOUILLE", clue: "Prato francês preparado com diversos vegetais", category: "comida" },
  { word: "ESPAGUETE", clue: "Tipo de massa italiana longa e fina", category: "comida" },
  { word: "PARMEZAO", clue: "Queijo duro de sabor intenso, usado frequentemente ralado", category: "comida" },
  { word: "GORGONZOLA", clue: "Queijo italiano conhecido por suas veias azuladas", category: "comida" },
  { word: "MOZZARELLA", clue: "Queijo italiano de textura macia, muito usado em pizzas", category: "comida" },
  { word: "BRIGADEIRO", clue: "Doce brasileiro feito tradicionalmente com leite condensado e chocolate", category: "comida" },
  { word: "FEIJOADA", clue: "Prato brasileiro preparado tradicionalmente com feijão preto e carnes", category: "comida" },
  { word: "ACARAJE", clue: "Comida baiana feita com massa de feijão-fradinho frita no azeite de dendê", category: "comida" },
  { word: "VATAPA", clue: "Prato de origem afro-brasileira muito associado à culinária baiana", category: "comida" },
  { word: "MOQUECA", clue: "Prato brasileiro preparado tradicionalmente com peixe ou frutos do mar", category: "comida" },
  { word: "AMPULHETA", clue: "Objeto que mede um intervalo de tempo usando areia", category: "objetos" },
  { word: "BINOCULO", clue: "Instrumento óptico usado para observar objetos distantes", category: "objetos" },
  { word: "TELESCOPIO", clue: "Instrumento óptico utilizado para observar objetos distantes no céu", category: "objetos" },
  { word: "MICROSCOPIO", clue: "Instrumento usado para observar estruturas muito pequenas", category: "objetos" },
  { word: "TERMOMETRO", clue: "Instrumento usado para medir temperatura", category: "objetos" },
  { word: "BAROMETRO", clue: "Instrumento utilizado para medir a pressão atmosférica", category: "objetos" },
  { word: "COMPASSO", clue: "Instrumento utilizado para traçar círculos e medir distâncias em desenhos", category: "objetos" },
  { word: "ESQUADRO", clue: "Instrumento usado para traçar e verificar ângulos, especialmente retos", category: "objetos" },
  { word: "PARAFUSO", clue: "Peça metálica rosqueada usada para fixação", category: "objetos" },
  { word: "ENGRENAGEM", clue: "Peça dentada usada para transmitir movimento entre mecanismos", category: "objetos" },
  { word: "ALICATE", clue: "Ferramenta usada para segurar, dobrar ou cortar determinados materiais", category: "objetos" },
  { word: "CHAVEIRO", clue: "Objeto usado para reunir e transportar chaves", category: "objetos" },];
