/**
 * Banco de palavras compartilhado (PT-BR) usado pelo Palavras Cruzadas e pelo
 * Caça-Palavras. Cada entrada tem a palavra em MAIÚSCULAS sem acentos/espaços
 * (para digitação e busca na grade) e uma dica em português para o Palavras
 * Cruzadas (o Caça-Palavras usa só `word`).
 *
 * Para adicionar novas palavras, basta incluir um novo item no array abaixo —
 * nenhum outro arquivo precisa mudar.
 */

export interface WordBankEntry {
  word: string;
  clue: string;
  category: string;
}

export const WORD_BANK: WordBankEntry[] = [
  { word: "GATO", clue: "Animal doméstico que mia", category: "animais" },
  { word: "CACHORRO", clue: "Melhor amigo do homem", category: "animais" },
  { word: "LEAO", clue: "Rei da selva", category: "animais" },
  { word: "TIGRE", clue: "Felino listrado da Ásia", category: "animais" },
  { word: "ELEFANTE", clue: "Mamífero com tromba", category: "animais" },
  { word: "GIRAFA", clue: "Animal de pescoço longo", category: "animais" },
  { word: "MACACO", clue: "Primata que gosta de bananas", category: "animais" },
  { word: "COELHO", clue: "Animal de orelhas compridas que pula", category: "animais" },
  { word: "CAVALO", clue: "Animal usado para montaria", category: "animais" },
  { word: "GALINHA", clue: "Ave que põe ovos", category: "animais" },
  { word: "PATO", clue: "Ave aquática que faz quá-quá", category: "animais" },
  { word: "URSO", clue: "Animal grande que hiberna", category: "animais" },
  { word: "LOBO", clue: "Animal selvagem que uiva", category: "animais" },
  { word: "RAPOSA", clue: "Animal astuto de cauda peluda", category: "animais" },
  { word: "TARTARUGA", clue: "Animal de casco lento", category: "animais" },
  { word: "BORBOLETA", clue: "Inseto colorido que sai do casulo", category: "animais" },
  { word: "ABELHA", clue: "Inseto que produz mel", category: "animais" },
  { word: "ARANHA", clue: "Animal de oito patas que tece teia", category: "animais" },
  { word: "PEIXE", clue: "Animal que vive na água e tem guelras", category: "animais" },
  { word: "GOLFINHO", clue: "Mamífero marinho muito inteligente", category: "animais" },
  { word: "TUBARAO", clue: "Predador temido dos oceanos", category: "animais" },
  { word: "COBRA", clue: "Réptil sem pernas", category: "animais" },
  { word: "JACARE", clue: "Réptil de rios que tem muitos dentes", category: "animais" },
  { word: "PINGUIM", clue: "Ave que não voa e vive no gelo", category: "animais" },
  { word: "CORUJA", clue: "Ave de rapina que enxerga à noite", category: "animais" },
  { word: "ZEBRA", clue: "Animal africano com listras", category: "animais" },
  { word: "CANGURU", clue: "Animal australiano que carrega filhote na bolsa", category: "animais" },
  { word: "FORMIGA", clue: "Inseto que vive em colônias organizadas", category: "animais" },
  { word: "ARVORE", clue: "Planta de tronco e copa", category: "natureza" },
  { word: "FLOR", clue: "Parte colorida e perfumada da planta", category: "natureza" },
  { word: "RIO", clue: "Curso de água que deságua no mar", category: "natureza" },
  { word: "MONTANHA", clue: "Grande elevação de terreno", category: "natureza" },
  { word: "OCEANO", clue: "Grande massa de água salgada", category: "natureza" },
  { word: "FLORESTA", clue: "Área com muitas árvores", category: "natureza" },
  { word: "DESERTO", clue: "Região seca e arenosa", category: "natureza" },
  { word: "VULCAO", clue: "Montanha que pode expelir lava", category: "natureza" },
  { word: "CACHOEIRA", clue: "Queda d'água natural", category: "natureza" },
  { word: "PRAIA", clue: "Faixa de areia à beira-mar", category: "natureza" },
  { word: "ILHA", clue: "Terra cercada de água por todos os lados", category: "natureza" },
  { word: "NUVEM", clue: "Massa de vapor no céu", category: "natureza" },
  { word: "CHUVA", clue: "Água que cai do céu", category: "natureza" },
  { word: "NEVE", clue: "Precipitação branca e gelada", category: "natureza" },
  { word: "VENTO", clue: "Ar em movimento", category: "natureza" },
  { word: "SOL", clue: "Astro que ilumina a Terra de dia", category: "natureza" },
  { word: "LUA", clue: "Satélite natural da Terra", category: "natureza" },
  { word: "ESTRELA", clue: "Ponto luminoso visível no céu à noite", category: "natureza" },
  { word: "PEDRA", clue: "Fragmento sólido e duro da natureza", category: "natureza" },
  { word: "AREIA", clue: "Material fino encontrado na praia", category: "natureza" },
  { word: "MESA", clue: "Móvel onde se faz as refeições", category: "casa" },
  { word: "CADEIRA", clue: "Móvel usado para sentar", category: "casa" },
  { word: "SOFA", clue: "Móvel estofado da sala", category: "casa" },
  { word: "CAMA", clue: "Móvel usado para dormir", category: "casa" },
  { word: "JANELA", clue: "Abertura da parede com vidro", category: "casa" },
  { word: "PORTA", clue: "Estrutura usada para entrar e sair", category: "casa" },
  { word: "TELHADO", clue: "Cobertura da casa", category: "casa" },
  { word: "PAREDE", clue: "Estrutura vertical que separa cômodos", category: "casa" },
  { word: "COZINHA", clue: "Cômodo onde se prepara comida", category: "casa" },
  { word: "BANHEIRO", clue: "Cômodo com chuveiro e vaso sanitário", category: "casa" },
  { word: "ESPELHO", clue: "Objeto que reflete a imagem", category: "casa" },
  { word: "CHAVE", clue: "Objeto que abre fechaduras", category: "casa" },
  { word: "LAMPADA", clue: "Objeto que ilumina os cômodos", category: "casa" },
  { word: "GELADEIRA", clue: "Eletrodoméstico que mantém alimentos frios", category: "casa" },
  { word: "TRAVESSEIRO", clue: "Usado para apoiar a cabeça ao dormir", category: "casa" },
  { word: "COBERTOR", clue: "Usado para se aquecer na cama", category: "casa" },
  { word: "VASO", clue: "Recipiente usado para plantas", category: "casa" },
  { word: "TAPETE", clue: "Peça de tecido colocada no chão", category: "casa" },
  { word: "ARROZ", clue: "Cereal branco muito consumido no Brasil", category: "comida" },
  { word: "FEIJAO", clue: "Combina com arroz no prato brasileiro", category: "comida" },
  { word: "PAO", clue: "Feito de farinha, comum no café da manhã", category: "comida" },
  { word: "QUEIJO", clue: "Derivado do leite", category: "comida" },
  { word: "LEITE", clue: "Bebida branca tirada da vaca", category: "comida" },
  { word: "OVO", clue: "Alimento posto pelas galinhas", category: "comida" },
  { word: "BANANA", clue: "Fruta amarela e curva", category: "comida" },
  { word: "MACA", clue: "Fruta vermelha ou verde, crocante", category: "comida" },
  { word: "LARANJA", clue: "Fruta cítrica usada em sucos", category: "comida" },
  { word: "ABACAXI", clue: "Fruta tropical com casca espinhosa", category: "comida" },
  { word: "MANGA", clue: "Fruta doce e suculenta de caroço grande", category: "comida" },
  { word: "MORANGO", clue: "Fruta vermelha pequena e doce", category: "comida" },
  { word: "UVA", clue: "Fruta usada para fazer vinho", category: "comida" },
  { word: "MELANCIA", clue: "Fruta grande, verde por fora e vermelha por dentro", category: "comida" },
  { word: "CHOCOLATE", clue: "Doce feito de cacau", category: "comida" },
  { word: "BOLO", clue: "Doce assado, comum em aniversários", category: "comida" },
  { word: "SORVETE", clue: "Sobremesa gelada e doce", category: "comida" },
  { word: "PIZZA", clue: "Prato italiano redondo com cobertura", category: "comida" },
  { word: "MACARRAO", clue: "Massa comum em pratos italianos", category: "comida" },
  { word: "CAFE", clue: "Bebida quente e escura, muito estimulante", category: "comida" },
  { word: "AGUA", clue: "Líquido essencial à vida", category: "comida" },
  { word: "SAL", clue: "Tempero branco e granulado", category: "comida" },
  { word: "ACUCAR", clue: "Tempero doce e granulado", category: "comida" },
  { word: "MEL", clue: "Substância doce produzida pelas abelhas", category: "comida" },
  { word: "CABECA", clue: "Parte superior do corpo", category: "corpo" },
  { word: "OLHO", clue: "Órgão da visão", category: "corpo" },
  { word: "NARIZ", clue: "Órgão do olfato", category: "corpo" },
  { word: "BOCA", clue: "Órgão usado para comer e falar", category: "corpo" },
  { word: "ORELHA", clue: "Órgão da audição", category: "corpo" },
  { word: "MAO", clue: "Parte do corpo com dedos usada para pegar", category: "corpo" },
  { word: "BRACO", clue: "Membro superior do corpo", category: "corpo" },
  { word: "PERNA", clue: "Membro inferior do corpo", category: "corpo" },
  { word: "CORACAO", clue: "Órgão que bombeia o sangue", category: "corpo" },
  { word: "CABELO", clue: "Cresce na cabeça", category: "corpo" },
  { word: "DENTE", clue: "Usado para mastigar", category: "corpo" },
  { word: "MEDICO", clue: "Profissional que cuida da saúde", category: "profissoes" },
  { word: "PROFESSOR", clue: "Profissional que ensina", category: "profissoes" },
  { word: "ENGENHEIRO", clue: "Profissional que projeta construções e sistemas", category: "profissoes" },
  { word: "ADVOGADO", clue: "Profissional que atua na área jurídica", category: "profissoes" },
  { word: "DENTISTA", clue: "Cuida da saúde dos dentes", category: "profissoes" },
  { word: "COZINHEIRO", clue: "Prepara refeições profissionalmente", category: "profissoes" },
  { word: "BOMBEIRO", clue: "Profissional que apaga incêndios", category: "profissoes" },
  { word: "POLICIAL", clue: "Profissional que garante a segurança pública", category: "profissoes" },
  { word: "PINTOR", clue: "Profissional que pinta quadros ou paredes", category: "profissoes" },
  { word: "MOTORISTA", clue: "Profissional que dirige veículos", category: "profissoes" },
  { word: "ENFERMEIRO", clue: "Auxilia médicos e cuida de pacientes", category: "profissoes" },
  { word: "PILOTO", clue: "Profissional que conduz aviões", category: "profissoes" },
  { word: "ATOR", clue: "Profissional que interpreta personagens", category: "profissoes" },
  { word: "CANTOR", clue: "Profissional que canta músicas", category: "profissoes" },
  { word: "JORNALISTA", clue: "Profissional que produz notícias", category: "profissoes" },
  { word: "COMPUTADOR", clue: "Máquina usada para processar dados", category: "tecnologia" },
  { word: "CELULAR", clue: "Telefone portátil", category: "tecnologia" },
  { word: "INTERNET", clue: "Rede mundial de computadores", category: "tecnologia" },
  { word: "TECLADO", clue: "Usado para digitar no computador", category: "tecnologia" },
  { word: "MOUSE", clue: "Periférico usado para clicar na tela", category: "tecnologia" },
  { word: "TELA", clue: "Onde as imagens do computador aparecem", category: "tecnologia" },
  { word: "IMPRESSORA", clue: "Equipamento que imprime documentos", category: "tecnologia" },
  { word: "CAMERA", clue: "Equipamento usado para tirar fotos", category: "tecnologia" },
  { word: "ROBO", clue: "Máquina automatizada que imita ações humanas", category: "tecnologia" },
  { word: "SENHA", clue: "Código secreto para acessar uma conta", category: "tecnologia" },
  { word: "BRASIL", clue: "País onde se fala português na América do Sul", category: "geografia" },
  { word: "CIDADE", clue: "Área urbana onde as pessoas vivem", category: "geografia" },
  { word: "PAIS", clue: "Território com governo próprio", category: "geografia" },
  { word: "CAPITAL", clue: "Principal cidade de um estado ou país", category: "geografia" },
  { word: "CONTINENTE", clue: "Grande extensão de terra, como a América", category: "geografia" },
  { word: "MAPA", clue: "Representação gráfica de um território", category: "geografia" },
  { word: "PONTE", clue: "Construção que liga duas margens", category: "geografia" },
  { word: "ESTRADA", clue: "Via usada para viajar de carro", category: "geografia" },
  { word: "AZUL", clue: "Cor do céu em dia claro", category: "cores" },
  { word: "VERMELHO", clue: "Cor do morango maduro", category: "cores" },
  { word: "AMARELO", clue: "Cor do sol e da banana", category: "cores" },
  { word: "VERDE", clue: "Cor das folhas", category: "cores" },
  { word: "ROSA", clue: "Cor associada ao romantismo", category: "cores" },
  { word: "PRETO", clue: "Cor da noite escura", category: "cores" },
  { word: "BRANCO", clue: "Cor da neve", category: "cores" },
  { word: "ROXO", clue: "Cor obtida misturando azul e vermelho", category: "cores" },
  { word: "FUTEBOL", clue: "Esporte mais popular do Brasil", category: "esportes" },
  { word: "VOLEI", clue: "Esporte jogado com uma rede e uma bola", category: "esportes" },
  { word: "BASQUETE", clue: "Esporte com cestas e bola laranja", category: "esportes" },
  { word: "NATACAO", clue: "Esporte praticado na piscina", category: "esportes" },
  { word: "TENIS", clue: "Esporte jogado com raquete", category: "esportes" },
  { word: "CORRIDA", clue: "Prova de velocidade a pé", category: "esportes" },
  { word: "CICLISMO", clue: "Esporte praticado com bicicleta", category: "esportes" },
  { word: "SURFE", clue: "Esporte praticado sobre as ondas", category: "esportes" },
  { word: "CARRO", clue: "Veículo de quatro rodas usado no dia a dia", category: "transporte" },
  { word: "ONIBUS", clue: "Transporte coletivo urbano", category: "transporte" },
  { word: "BICICLETA", clue: "Veículo de duas rodas movido a pedal", category: "transporte" },
  { word: "AVIAO", clue: "Veículo que voa e transporta passageiros", category: "transporte" },
  { word: "TREM", clue: "Veículo que anda sobre trilhos", category: "transporte" },
  { word: "BARCO", clue: "Veículo usado para navegar", category: "transporte" },
  { word: "MOTO", clue: "Veículo de duas rodas com motor", category: "transporte" },
  { word: "METRO", clue: "Transporte subterrâneo das grandes cidades", category: "transporte" },
  { word: "VIOLAO", clue: "Instrumento de cordas dedilhado", category: "musica" },
  { word: "PIANO", clue: "Instrumento de teclas", category: "musica" },
  { word: "BATERIA", clue: "Instrumento de percussão com pratos e tambores", category: "musica" },
  { word: "FLAUTA", clue: "Instrumento de sopro fino e longo", category: "musica" },
  { word: "GUITARRA", clue: "Instrumento de cordas elétrico", category: "musica" },
  { word: "MUSICA", clue: "Arte de combinar sons", category: "musica" },
  { word: "CANCAO", clue: "Composição musical cantada", category: "musica" },
  { word: "VERAO", clue: "Estação mais quente do ano", category: "tempo" },
  { word: "INVERNO", clue: "Estação mais fria do ano", category: "tempo" },
  { word: "OUTONO", clue: "Estação em que as folhas caem", category: "tempo" },
  { word: "PRIMAVERA", clue: "Estação das flores", category: "tempo" },
  { word: "SEMANA", clue: "Período de sete dias", category: "tempo" },
  { word: "MES", clue: "Período de cerca de trinta dias", category: "tempo" },
  { word: "ANO", clue: "Período de doze meses", category: "tempo" },
  { word: "LIVRO", clue: "Objeto usado para leitura", category: "objetos" },
  { word: "CANETA", clue: "Objeto usado para escrever com tinta", category: "objetos" },
  { word: "LAPIS", clue: "Objeto usado para escrever ou desenhar", category: "objetos" },
  { word: "RELOGIO", clue: "Objeto usado para ver as horas", category: "objetos" },
  { word: "BOLSA", clue: "Objeto usado para carregar pertences", category: "objetos" },
  { word: "OCULOS", clue: "Objeto usado para melhorar a visão", category: "objetos" },
  { word: "GUARDACHUVA", clue: "Objeto usado para proteger da chuva", category: "objetos" },
  { word: "TESOURA", clue: "Objeto usado para cortar papel ou tecido", category: "objetos" },
  { word: "AGULHA", clue: "Objeto fino usado para costurar", category: "objetos" },
  { word: "ESPADA", clue: "Arma antiga de lâmina longa", category: "objetos" },
  { word: "BOLA", clue: "Objeto redondo usado em muitos esportes", category: "objetos" },
  { word: "PIPA", clue: "Brinquedo que voa preso a uma linha", category: "objetos" },
  { word: "BONECA", clue: "Brinquedo em forma de pessoa", category: "objetos" },
  { word: "QUEBRACABECA", clue: "Jogo de montar peças que formam uma imagem", category: "objetos" },];
